### ISSUE TITLE
Recommendations for caching poetry dependencies causes the wrong python version to be used for poetry install

### ISSUE THREAD

**Issue by sdb9696** [actions/setup-python#846] opened 2024-04-15 10:48 UTC
**Description:**

The recommendations for caching poetry dependencies causes the wrong python version to be used for `poetry install`.

Because pipx install poetry happens before `setup-python` and [By default, Poetry will try to use the Python version used during Poetry’s installation to create the virtual environment for the current project](https://python-poetry.org/docs/managing-environments/).

Maybe the solution here is to update the docs to make sure that users know to run `poetry env use ${{ steps.setup-python.outputs.python-path }}python` prior to running `poetry install`. I have not tested that works however.

**Action version:**

v5

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

All versions of python affected except the default version installed on the github runner.

**Repro steps:**  

Follow the steps outlined in advance-usage.md for [caching poetry dependencies](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages).

Run `poetry install`

**Expected behavior:**

`poetry install` should use the version of python set by `setup-python` 

**Actual behavior:**

`poetry install` uses the default version of python from the runner os.

**Comment by HarithaVattikuti** [comment] 2024-04-15 22:04
Hello @sdb9696 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by andwaredev** [comment] 2024-04-18 17:37
Hello @sdb9696 – my team ran into this same issue recently. We solved it by pinning the python version in our `pyproject.toml` file, under `[tool.poetry.dependencies]`. See example below.

```toml
[tool.poetry.dependencies]
python = "3.11.4"
```

**Comment by sdb9696** [comment] 2024-04-18 17:54
Thanks @andwaredev but we run our CI against all supported python versions to check there are no issues so not sure this workaround will help.

**Comment by silverwind** [comment] 2024-04-19 20:20
I find it highly concerning that the [recommend](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages) and only working solution is to install poetry before setting up python. It should be the other way around but if one tries that, `setup-python` will fail to find a `poetry`.

This is what I would like to see working:

```yaml
- uses: actions/setup-python@v5
  with:
    python-version: '3.12'
    cache: 'poetry'
- run: pipx install poetry
```

Why does above work with pipenv but not with poetry?

**Comment by silverwind** [comment] 2024-05-02 15:08
> This also makes the assumtion that you have pipx which I do not :)

I think `setup-python` does install pip and its variants currently, right?

**Comment by LaurensBosscher** [comment] 2024-05-17 10:31
This is indeed inconvenient. We install Python and Poetry in the following way:

`
      - name: Install Poetry
        run: |
          python -m pip install poetry
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: poetry
          cache-dependency-path: projects/investment_decision_support_system/poetry.lock
          
      - name: Set Poetry environment
        run: |
          python -m pip install poetry
          cd projects/investment_decision_support_system/
          poetry env use 3.12
`

This triggered the following error:

`
  - Installing xmltodict (0.13.0 9c3ec3c)
  ChefBuildError
  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/opt/pipx/venvs/poetry/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
      main()
    File "/opt/pipx/venvs/poetry/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/pipx/venvs/poetry/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 128, in get_requires_for_build_wheel
      backend = _build_backend()
                ^^^^^^^^^^^^^^^^
    File "/opt/pipx/venvs/poetry/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 70, in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 995, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "/tmp/tmpigmi429k/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
      import setuptools.version
    File "/tmp/tmpigmi429k/.venv/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
      import pkg_resources
    File "/tmp/tmpigmi429k/.venv/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
      register_finder(pkgutil.ImpImporter, find_on_path)
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  
  at /opt/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
`

Do note how the installation is failing because Poetry is using Python **3.10** while the specified Python version is **3.12**.

This took a while to chase down. I'm not sure what exactly depends on Poetry but perhaps it would be possible to integrate those functions into setup-python instead of having a hard dependency on the whole package?

Alternatively, if there's a workaround it would be great if the documentation could be updated.

**Comment by evilhamsterman** [comment] 2024-05-17 17:00
Ultimately we're considering just using actions/cache directly to cache poetry rather than setup-python's built in support

**Comment by till** [comment] 2024-05-21 16:31
I just ran into this issue as well. I used an example in the docs that triggers this bug _beautifully_. Maybe time to ramp up the tests for this action?

**Comment by till** [comment] 2024-05-21 17:21
I am running the following workflow which works:

```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pipx install poetry==1.8.3
    - run: echo "/root/.local/bin" >> $GITHUB_PATH
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: poetry
    - run: pipx install poetry==1.8.3
    - run: poetry install
      working-directory: app
    - run: poetry run flake8
      working-directory: app
```

`pipx` is smart enough not to install poetry again, and somehow it ends up in the correct environment without any hacks.

What I had to do was add `/root/.local/bin` to the `$GITHUB_PATH`, because otherwise it wouldn't be able to find `poetry` anywhere and fail at `actions/setup-python`:

```
[pr/lint]   💬  ::debug::Found 1 files to hash.
[pr/lint]   💬  ::debug::followSymbolicLinks 'true'
[pr/lint]   💬  ::debug::implicitDescendants 'true'
[pr/lint]   💬  ::debug::matchDirectories 'true'
[pr/lint]   💬  ::debug::omitBrokenSymbolicLinks 'true'
[pr/lint]   💬  ::debug::Search path '/Users/till/Documents/workspaces/project/pdf-test'
[pr/lint]   💬  ::debug::Processing Poetry project at /Users/till/Documents/workspaces/project/pdf-test/app
[pr/lint]   ❗  ::error::Unable to locate executable file: poetry. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
[pr/lint]   ❌  Failure - Main actions/setup-python@v5
[pr/lint]   ⚙  ::set-env:: Python_ROOT_DIR=/opt/hostedtoolcache/Python/3.11.8/x64
[pr/lint]   ⚙  ::set-env:: Python2_ROOT_DIR=/opt/hostedtoolcache/Python/3.11.8/x64
[pr/lint]   ⚙  ::set-env:: Python3_ROOT_DIR=/opt/hostedtoolcache/Python/3.11.8/x64
[pr/lint]   ⚙  ::set-env:: LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.11.8/x64/lib
[pr/lint]   ⚙  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.11.8/x64
[pr/lint]   ⚙  ::set-env:: PKG_CONFIG_PATH=/opt/hostedtoolcache/Python/3.11.8/x64/lib/pkgconfig
[pr/lint]   ⚙  ::set-output:: python-version=3.11.8
[pr/lint]   ⚙  ::set-output:: python-path=/opt/hostedtoolcache/Python/3.11.8/x64/bin/python
[pr/lint]   ⚙  ::add-path:: /opt/hostedtoolcache/Python/3.11.8/x64
[pr/lint]   ⚙  ::add-path:: /opt/hostedtoolcache/Python/3.11.8/x64/bin
[pr/lint] exitcode '1': failure
```

**Comment by gowridurgad** [comment] 2024-06-03 06:06
Hi @sdb9696 , It is the expected behaviour, if the setup python tries to install the python version which was not specified in pyproject.toml  file, under  [tool.poetry.dependencies], the poetry install use the python version used during poetry installation from runner. Here's the screenshots for your reference. 
```
[tool.poetry.dependencies]
python = "^3.10.9"
numpy = "^1.22.3"
tqdm = {version = "4.66.4", optional = true }
pandas = "^2.2.2"

```
<img width="769" alt="Screenshot 2024-06-03 at 11 24 52 AM" src="https://github.com/actions/setup-python/assets/159780674/20a6a8c4-fd82-45d8-b16c-2e0c9dd81aa0">

<img width="769" alt="Screenshot 2024-06-03 at 11 27 18 AM" src="https://github.com/actions/setup-python/assets/159780674/2f7d8780-6b62-4985-868a-dcdd0262c235">

**Comment by gowridurgad** [comment] 2024-06-18 12:10
Hi @sdb9696, Just a gentle reminder regarding this issue, We have updated the document. If you have any questions or need further assistance, Please let us know.

**Comment by sdb9696** [comment] 2024-06-18 12:59
> Hi @sdb9696, Just a gentle reminder regarding this issue, We have updated the document. If you have any questions or need further assistance, Please let us know.

Hi @gowridurgad, apologies for the delayed reply I have been away.

I'm not completely sure I follow the expected behaviour point or the point about matching the python version in pyproject.toml.

Your example above is doing `poetry env use "${{ steps.setup-python.outputs.python-path }}"`.  Is that something you added specifically to your test or has it been added to the setup-python codebase since I opened the original issue? My suggestion was to update the docs to include that suggestion and I can see from above that it will work if that's done.

w.r.t the setup-python interpreter not matching the toml spec that is not the issue I was reporting. Our toml specifies `python = ">=3.8.0"` so this isn't the issue I was reporting. The issue is that poetry will not use the setup-python python version unless the user runs  `poetry env use "${{ steps.setup-python.outputs.python-path }}"` before running install.

**Comment by gowridurgad** [comment] 2024-06-24 12:31
Hi @sdb9696, we haven't use the command poetry env use "${{ steps.setup-python.outputs.python-path }}" in workflow file. Poetry seems to be automatically using the Python version set by setup-python, regardless of whether the command is used. However, The Poetry fails to use the setup-python Python version only when there's a mismatch between this version and the one specified in the pyproject.toml file. In such cases, using the poetry env use "${{steps.setup-python.outputs.python-path }}" actually causes the build to fail. here's the screenshots for your reference.
screenshot1: with poetry env use "${{ steps.setup-python.outputs.python-path }}" .

<img width="843" alt="Screenshot 2024-06-19 at 10 57 02 AM" src="https://github.com/actions/setup-python/assets/159780674/7591423c-987c-4a32-98c8-01cdcc546bbe">

screenshot2: without poetry env use "${{ steps.setup-python.outputs.python-path }}" 

<img width="834" alt="Screenshot 2024-06-19 at 11 05 16 AM" src="https://github.com/actions/setup-python/assets/159780674/09fb2ac8-be10-4dae-9505-f010a9c47383">

screenshot3: poetry env use "${{ steps.setup-python.outputs.python-path }}" causes the build to fail if python version didn't 
match version specified in pyproject.toml file.

<img width="1397" alt="Screenshot 2024-06-21 at 6 20 16 PM" src="https://github.com/actions/setup-python/assets/159780674/9242d6fe-11ac-460d-9315-976addbd2e46">

**Comment by andreipetre** [comment] 2024-06-28 11:37
I ran into the same issue. The existing workflow stopped working recently, without any changes to it.

I fixed it by changing how poetry is installed.

```yaml
steps:
  - uses: actions/checkout@v4

  - name: Install poetry
    run: curl -sSL https://install.python-poetry.org | python3 -

  - uses: actions/setup-python@v5
    with:
      python-version: "3.12.3"
      cache: "poetry"

  - name: Install dependencies
    run: poetry install
```

**Comment by gowridurgad** [comment] 2024-07-03 11:35
Hi @andreipetre, Could you please attach link to the build or public repository to reproduce the issue ?
If you are referring to the workflow mentioned in the document, It is working correctly. The workflow outlined in the document and the one you mentioned in your previous comment are functioning identically.

**Comment by sdb9696** [comment] 2024-07-04 14:00
@gowridurgad maybe you're missing the issue because you're fixing the python version in your pyproject.toml. Have you tried this with a loose python specifier of `>=3.8`? Then poetry will use whichever version it was `pipx` installed with and not the version installed by `setup_python`

**Comment by gowridurgad** [comment] 2024-07-09 05:39
Hi @sdb9696, We tried using a loose Python specifier of >=3.8 and Poetry is using the version installed by setup_python. Here is a screenshot for reference.

can you please share your updated workflow link to check  and assist further if anything missed as we are not seeing the issue from our end.

```
[tool.poetry.dependencies]
python = ">=3.8"
requests = "^2.25.1
```
<img width="860" alt="Screenshot 2024-07-05 at 6 18 18 PM" src="https://github.com/actions/setup-python/assets/159780674/a8207509-e716-4707-bb9f-c23ebc7ab78f">

**Comment by sdb9696** [comment] 2024-07-09 09:25
Hi @gowridurgad, I don't have a workflow link to point you to as I ended up using actions/cache directly in the end. Can you point me to the PR/branch you've used to generate the output above and I'll see what the difference is?

**Comment by gowridurgad** [comment] 2024-07-12 05:42
Hi @sdb9696, Here is the link to the repository 
https://github.com/setup-actions-demo/test-setup-python/actions/runs/9868764478/job/27251296773
Please take a look and let us know if you find any differences or have any questions.

**Comment by gowridurgad** [comment] 2024-07-24 13:00
Hi @sdb9696, Just a gentle reminder regarding this issue, If you have any updates, Please let us know.

**Comment by gowridurgad** [comment] 2024-08-05 12:49
Hi @sdb9696, Just a gentle reminder regarding this issue, If you have any updates, Please let us know.

**Comment by sdb9696** [comment] 2024-08-05 13:35
Hi, apologies for the delay. I tried to recreate the issue and couldn’t anymore. It’s possible something has fixed it so I’d say good to close with the doc updates. Many thanks for your time with this.

**Comment by gowridurgad** [comment] 2024-08-09 06:03
Hello @sdb9696 , The [PR](https://github.com/actions/setup-python/pull/908) has been merged and the documentation has been updated.  For reference, you may visit the https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
Thank You !

**Closed by gowridurgad** 2024-08-09 06:03 UTC
Labels: bug

**Comment by liz-is** [comment] 2024-10-11 15:38
Hello - I am running into this issue currently, see [here](https://github.com/ReX-XAI/ReX/actions/runs/11294676206/job/31415680779).

We have specified `python = "^3.10"` in the `pyproject.toml`. `setup-python@v5` installs Python 3.12 as requested, but the Poetry virtualenv is created using python 3.10. Here is the [relevant version of the workflow](https://github.com/ReX-XAI/ReX/blob/399e3cffac35391804bb7277c78a191e55fa79ef/.github/workflows/python-package.yml) that I'm using.

Is there a recommended workaround for this? We do need to specify a minimum Python version in the `pyproject.toml`, but we also want to test on multiple Python versions.
