### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pip (from versions: none) on self-hosted runner

### ISSUE THREAD

**Issue by sukki37** [actions/setup-python#354] opened 2022-03-16 02:43 UTC
**Description:**

**Action version:**
Specify the action version
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**

3.8.10
**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
my action yaml is as follows:
```yaml
name: Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
        
    - name: Test Python
      run: |
        python /mnt/datadisk0/tmp/test.py
```
**Expected behavior:**
A description of what you expected to happen.
no error
**Actual behavior:**
A description of what is actually happening.
<img width="985" alt="image" src="https://user-images.githubusercontent.com/77312370/158506238-4f7754a6-21e6-4ece-9e08-278747e0eca8.png">

**Comment by marko-zivic-93** [comment] 2022-03-25 15:12
Hello @sukki37 
Thank you for reporting this to us.
Could you please provide us with a repo where you have experienced this issue?
We can't reproduce this issue without a link to your repo.
Thanks in advance!

**Comment by marko-zivic-93** [comment] 2022-04-01 08:26
Hello @sukki37 
Could you please provide us with the repo where you experienced this issue?

**Comment by marko-zivic-93** [comment] 2022-04-04 09:34
I will close this issue.
If you experience this issue again or get the chance to provide us with your repo, feel free to post it here or to create another issue for it.

**Closed by marko-zivic-93** 2022-04-04 09:34 UTC
Labels: bug

**Comment by eandersson** [comment] 2022-06-23 20:37
This happens if you try to use an HTTP pip mirror (instead of an HTTPS mirror).
