### ISSUE TITLE
Cannot install either Python version on macOS 14.2.1

### ISSUE THREAD

**Issue by EvgeniyRub** [actions/setup-python#812] opened 2024-02-05 12:27 UTC
**Description:**
Cannot install Python versions into self-hosted runner on macOS

**Action version:**
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

**Platform:**
- [ ] Ubuntu
- [ +] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ +] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
All installed

**Actual behavior:**
`Execute installation script
Check if Python hostedtoolcache folder exist...
Create Python 3.9.18 folder
Copy Python binaries to hostedtoolcache folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading pip...
Looking in links: /var/folders/yg/z8gwyr816hsg7d73dx1cdt7w0000gp/T/tmpeqwvkgf5
Requirement already satisfied: setuptools in /Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages (58.1.0)
Requirement already satisfied: pip in /Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages (23.0.1)
Error: WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Error: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Error: WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Error: WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Error: WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Error: WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Error: ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
Error: ERROR: No matching distribution found for pip
Error: The process '/bin/bash' failed with exit code 1`

**Comment by HarithaVattikuti** [comment] 2024-02-05 18:17
Hello @EvgeniyRub,
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by aparnajyothi-y** [comment] 2024-05-10 13:39
Hello @EvgeniyRub, Thank you once again for creating this issue, we have investigated the issue and we are unable to reproduce the issue for macos-14. 
The error that you are encountering is an SSL error while trying to upgrade pip in a Python installation process on the runner. This error is due to Python being unable to establish a secure connection to the PyPi servers. 
Below are the possibilities that caused the error:
1. Check the firewall rules to ensure that connections to PyPi servers (https://pypi.org) are allowed. 
2. Check If pip is using a proxy, you might need to update the proxy settings or ensure that the proxy server is functioning correctly.

Please share the repro link to investigate further and update as we are not able to reproduce the error from our end. Please find the screenshots for reference.
<img width="1002" alt="image" src="https://github.com/actions/setup-python/assets/147696841/4b1788d1-22fa-4e70-8595-f6ea9f4636c3">

**Comment by aparnajyothi-y** [comment] 2024-05-27 07:42
Hello @EvgeniyRub,  please confirm if the above-provided information helped to resolved the issue and share the repro link to further investigate the exact issue as we are unable to reproduce the issue.

**Comment by aparnajyothi-y** [comment] 2024-06-20 12:46
Hello @EvgeniyRub, please confirm if the above-provided information helped to resolved the issue and share the repro link to further investigate the exact issue as we are unable to reproduce the issue.

**Comment by aparnajyothi-y** [comment] 2024-07-03 13:07
Hello @EvgeniyRub, Proceeding to close this issue as we don't hear anything from you for a long time after two reminders. 
Please feel free to reach us to reopen this issue in case any clarifications needed:)

**Closed by aparnajyothi-y** 2024-07-03 13:07 UTC
Labels: bug
