### ISSUE TITLE
Version 3.10.11 with arch arm64 not found even thought it is in the list

### ISSUE THREAD

**Issue by CGHoussem** [actions/setup-python#686] opened 2023-06-18 14:08 UTC
**Description:**
I am self-hosting a GitHub runner on my raspberry pi (it's arch is  aarch64, which is amd64). I linked my GitHub workflow in order to run on the Raspberry PI but unfortunately I couldn't get the workflow to go beyond the python setup task. Even though the python version I have set exists in the list provided by the error (https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json)

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
3.10.11

**Repro steps:**  
```
- name: Set up Python
  uses: actions/setup-python@v3
  with:
    python-version: '3.10.11'
```

**Expected behavior:**
Download and use the python version 3.10.11

**Actual behavior:**
```
Run actions/setup-python@v3
  with:
    python-version: 3.10.11
    token: ***
Version 3.10.11 was not found in the local cache
Error: Version 3.10.11 with arch arm64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by dmitry-shibanov** [comment] 2023-06-19 08:05
Hello @CGHoussem. Thank you for your report. I think it is an expected behaviour because as I can see through logs that it tries to install python 3.10.11 with architecture arm64 for Linux which is not supported.

**Comment by CGHoussem** [comment] 2023-06-19 11:15
Hey @dmitry-shibanov ,

Thanks for your response, I understand from the error that that version of Python doesn't exist for the architecture arm64, but why does it exist in the availability list: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Comment by dmitry-shibanov** [comment] 2023-06-19 12:54
@CGHoussem. It exists only for macOS as universal package but we do not have python with arm64 for Ubuntu.

**Comment by CGHoussem** [comment] 2023-06-19 13:13
@dmitry-shibanov Oh I haven't noticed the "darwin" platform, what is the latest available image for linux platforms with arm64 architecture then?

**Comment by dmitry-shibanov** [comment] 2023-06-19 13:49
Unfortunately we do not provide python with arm64 architecture for Linux. We have feature request about it but for now we do not have hosted images with arm64 for that. 

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2023-06-19 13:49 UTC
Labels: bug
