### ISSUE TITLE
Restore Python 2.7

### ISSUE THREAD

**Issue by dirkf** [actions/setup-python#689] opened 2023-06-22 16:17 UTC
**Description:**
Python 2.7 support was removed

**Action version:**
4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
2.7

**Repro steps:**  
```
uses: actions/setup-python@v4
with:
   python-version: 2.7
...
```

**Expected behavior:**
The necessary tests should run under Python 2.7

**Actual behavior:**
Python 2.7 is no longer available.

Fortunately this bug can be solved just by reverting #672. You could make it an option, but that's unnecessary extra work (like #672 in the first place).

**Comment by dmitry-shibanov** [comment] 2023-06-23 12:21
Hello @dirkf. Thank you for your report. We're not planing to revert changes regarding to python 2.7. The support for python 2.7 was ended January 1, 2020. We had announcements and added warning to the action for the usage of python 2.7. 

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2023-06-23 12:21 UTC
Labels: bug, needs triage

**Comment by dirkf** [comment] 2023-06-23 12:25
Why was it important to waste your and our time doing this so as to break existing workflows?

**Comment by hugovk** [comment] 2023-06-23 16:58
It might not look like it, but maintaining old stuff still takes a lot of time and energy, that can be better spent working on new stuff and maintaining less old stuff.

Python 2.7 has been end of life for three and a half years, with years more notice before that. It's no surprise this was coming.

**Comment by dirkf** [comment] 2023-06-23 17:36
No surprise but still pointless.

The "end-of-life" thing that you mention is the supplier's view, not the user's. You can be sure that people now running workflows with Python 2 have a valid reason for doing so and "upgrade to Python >2" is not a helpful suggestion.

This is a real fancy, as well as core, package, concerning which the contributors here are the experts: shouldn't you provide some guidance or work-arounds to keep users' workflows running despite your breakage rather than leaving it to every affected user to invent a solution? Having to do that would alter the balance that you describe against "maintaining old stuff".

**Comment by hugovk** [comment] 2023-06-23 18:16
The #672 linked to above contains guidance on Docker-based workarounds.

**Comment by dirkf** [comment] 2023-06-24 00:27
Yes, and kudos to https://github.com/actions/setup-python/issues/672#issuecomment-1582725639.

Advice or work-arounds should have been provided by the project rather than by victims of the change.

It won't be a surprise that I agree entirely with https://github.com/actions/setup-python/issues/672#issuecomment-1602918550.

**Comment by jvanasco** [comment] 2023-06-27 12:45
> It might not look like it, but maintaining old stuff still takes a lot of time and energy, that can be better spent working on new stuff and maintaining less old stuff.

The proper method to end support is to bump the version and leave the precompiled binaries as-is, not yank it from pinned versions that affect existing integrations.  This is not just the status quo across the industry, but an explicit directive in Github's own best-practices for Actions.  You should know that.

No one expects Python2.7 to be maintained or supported.  Everyone expects industry best-practices and Github's own claimed standards to be upheld, which would have frozen the existing support in legacy versions. 

This should have been implemented in a v5, and had no effect on v1-v4. 

I'm moving to other platforms.  The precedent this sets for the Github platform is deeply troubling.  The status and duration of Python2.7 being EOL is irrelevant.  I could care less about Python2.7 - but after Github's support confirmed to me that `setup-actions` is an official repo - I have zero trust in this platform.

The only precedent this sets is "Github can not be trusted to implement it's own standards,  Your CI/Actions may break at any point in time, because we may make an arbitrary decision to retroactively drop support from pinned versions".
