### ISSUE TITLE
Python.h missing on windows

### ISSUE THREAD

**Issue by Martmists-GH** [actions/setup-python#390] opened 2022-04-21 14:11 UTC
**Description:**
As seen here: [link](https://github.com/Martmists-GH/kpy-plugin/runs/6113425728?check_suite_focus=true#step:6:84) Python.h is missing on windows runs.

**Action version:**
v3

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
3.9, 3.10

**Repro steps:**  
Example repo: https://github.com/Martmists-GH/kpy-plugin

**Expected behavior:**
Python.h can be used as normal

**Actual behavior:**
Python.h reported missing

**Comment by marko-zivic-93** [comment] 2022-04-26 07:29
Hello @Martmists-GH 
The way to find the root cause is to increase logging level of gradle (see https://docs.gradle.org/current/userguide/logging.html) and get the exact clang options used to build the binary (namely -I flag) and next compare it with the actual location of python.h. Workaround should be the setting the CFLAGS environment variable manually

**Comment by dsame** [comment] 2022-04-29 04:52
Hello @Martmists-GH i see the branch with the failed build does not exist anymore but the master branch is green.
Please confirm the problem still exists and requires the investigation. 
Could you please provide an actual repro-step of the failed build?

**Comment by Martmists-GH** [comment] 2022-04-29 08:33
- Use setup-python to provide python
- Use `platform.get_paths()` to get the path to Python's headers and write to a file used for compilation
- Compile something using those headers.

My solution ended up being to simply cross-compile from a macos host.

**Comment by dsame** [comment] 2022-05-02 07:24
@Martmists-GH 
can you please give us a repo, so we can investigate the original issue in order to prevent the other users from the same problem? Don't hesitate to say "no" in case it is not easy task for you.

**Comment by marko-zivic-93** [comment] 2022-05-05 07:10
Hello @Martmists-GH 
I will close this issue for now. If you have any comments or concerns please feel free to leave a comment here or to create a new issue.

**Closed by marko-zivic-93** 2022-05-05 07:10 UTC
Labels: bug

**Comment by Martmists-GH** [comment] 2022-06-13 23:06
https://github.com/Martmists-GH/kpy-plugin/actions/runs/2462890729 here's a run failing due to a missing Python.h, and it also specifies the path used on windows. (Note that it states a second path called "github-mingw64" but this is only used when cross-compiling, and as such should be ignored)
