### ISSUE TITLE
Virtualenv Issues Under Windows

### ISSUE THREAD

**Issue by s0undt3ch** [actions/setup-python#44] opened 2019-12-20 15:50 UTC
I seem to be having problems, under windows, when using `nox` which creates a virtualenv based off of the available Python to install dependencies into it and run tests against it.

The workflow test run can be seen [here](https://github.com/s0undt3ch/pip-tools-compile-impersonate/runs/358351947)

``` 
nox > Command c:\hostedtoolcache\windows\python\2.7.16\x64\python.exe -m virtualenv D:\a\pip-tools-compile-impersonate\pip-tools-compile-impersonate\.nox\tests-2-7 -p python2.7 failed with exit code 100:
Traceback (most recent call last):

  File "D:/a/pip-tools-compile-impersonate/pip-tools-compile-impersonate/.nox/tests-2-7/lib/python2.7/site.py", line 769, in <module>

    main()

  File "D:/a/pip-tools-compile-impersonate/pip-tools-compile-impersonate/.nox/tests-2-7/lib/python2.7/site.py", line 757, in main

    aliasmbcs()

  File "D:/a/pip-tools-compile-impersonate/pip-tools-compile-impersonate/.nox/tests-2-7/lib/python2.7/site.py", line 513, in aliasmbcs

    import locale, codecs

  File "D:\a\pip-tools-compile-impersonate\pip-tools-compile-impersonate\.nox\tests-2-7\lib\python2.7/locale.py", line 19, in <module>

    import functools

ImportError: No module named functools

Already using interpreter C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/opt/bin/python2.7.exe

  No LICENSE.txt / LICENSE found in source


New python executable in D:\a\pip-tools-compile-impersonate\pip-tools-compile-impersonate\.nox\tests-2-7\Scripts\python2.7.exe

Also creating executable in D:\a\pip-tools-compile-impersonate\pip-tools-compile-impersonate\.nox\tests-2-7\Scripts\python.exe

ERROR: The executable D:\a\pip-tools-compile-impersonate\pip-tools-compile-impersonate\.nox\tests-2-7\Scripts\python2.7.exe is not functioning

ERROR: It thinks sys.prefix is u'd:\\a\\pip-tools-compile-impersonate\\pip-tools-compile-impersonate' (should be u'd:\\a\\pip-tools-compile-impersonate\\pip-tools-compile-impersonate\\.nox\\tests-2-7')

ERROR: virtualenv is not compatible with this system or executable

Note: some Windows users have reported this error when they installed Python for "Only this user" or have multiple versions of Python installed. Copying the appropriate PythonXX.dll to the virtualenv Scripts/ directory may fix this problem.

Running virtualenv with interpreter C:\ProgramData\Chocolatey\bin\python2.7.exe

nox > Session tests-2.7 failed.
```

**Comment by dvc94ch** [comment] 2020-01-07 15:32
Having this issue too

**Comment by nikita-bykov** [comment] 2021-11-03 09:44
Hello @s0undt3ch! We apologize for such a late reply.
Is this issue still relevant?

**Comment by nikita-bykov** [comment] 2021-11-12 08:02
Hello @s0undt3ch! I'm going to close the issue because we haven't received a response from you and unfortunately cannot continue our investigation.
If the issue is still relevant, please provide us with steps to reproduce it.
Thank you!

**Closed by nikita-bykov** 2021-11-12 08:02 UTC
Labels: bug
