### ISSUE TITLE
Python 3.9 + Windows: Does not handle long paths like other versions

### ISSUE THREAD

**Issue by pradyunsg** [actions/setup-python#267] opened 2021-11-12 09:39 UTC
**Description:**
Python 3.9 seems to behave differently from other Python versions, when handling long paths on Windows. This looks suspiciously like [non-LongPathAware behaviour](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?).

**Action version:**
Specify the action version: v2?

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.9

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

```yml
name: Release
on:
  push:

jobs:
  windows:
    name: ${{ matrix.python }} / ${{ matrix.os }}
    strategy:
      matrix:
        os: [Windows]
        python:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - run: python -c "from pathlib import Path; (Path.cwd() / ('a'*131) / ('a'*131)).mkdir(parents=True)"
```

- https://github.com/pradyunsg/testing-grounds/actions/runs/1452413343 for the run output/behaviour.
- https://github.com/pradyunsg/testing-grounds/tree/c409e864e107f9cfead32d440a569e96144fda0a for the GitHub actions configuration.

Noticed since this was causing errors in pip's test suite: https://github.com/pypa/pip/runs/4187290412?check_suite_focus=true

**Expected behavior:**
Python 3.9 behaves like other Python versions, and handles long paths on Windows.

**Actual behavior:**
Python 3.9 fails when handling long paths on Windows.

**Comment by pradyunsg** [comment] 2021-11-12 09:43
Oh, and this seems to be a somewhat-recent change, since `pip` had the same-ish setup working 5 days ago: https://github.com/pypa/pip/runs/4130255296?check_suite_focus=true

**Comment by layday** [comment] 2021-11-12 19:24
This is related to the upgrade to 3.9.8 which is the first Python version to have been released with https://github.com/python/cpython/commit/06935bd68e3d89a4cc3f08c1d15eaa651b79a523.  The same warning/failure will appear in Python 3.10 next month.

**Comment by layday** [comment] 2021-11-12 19:24
Also experiencing this at pypa/build.

**Comment by layday** [comment] 2021-11-12 19:37
Okay, that actually appears to be a manifestation of the issue with paths - I didn't look close enough, sorry.

**Comment by uranusjr** [comment] 2021-11-15 08:22
Make pipx the third PyPA project being affected 🙂

**Comment by nikita-bykov** [comment] 2021-11-16 14:35
Hello @pradyunsg! We were be able to reproduce this issue on windows-latest hosted image, but it also reproduces on the local Windows machine. It looks like the issue is not related to setup-python action, but to Python 3.9.8.
As a workaround, you can install Python 3.9.9 using setup-python action. Also next week this Python version will be available in GitHub hosted images and version 3.9 will point to 3.9.9.

**Comment by uranusjr** [comment] 2021-11-16 16:16
What steps are needed to reproduce this locally? I don’t recall 3.9.9 containing a fix for this, so we may want to report this to upstream CPython so they can investigate properly. Even if the bug is fixed in 3.9.9, the fact that it manifests but disappears on its own is enough reason for it to be more thoroughly investigated.

**Comment by nikita-bykov** [comment] 2021-12-10 09:02
Hello @uranusjr, I installed Python 3.9.8 on my Windows machine using `choco` and executed the following command from repro steps:
```
python -c "from pathlib import Path; (Path.cwd() / ('a'*131) / ('a'*131)).mkdir(parents=True)"
```
I got the same error as in https://github.com/pradyunsg/testing-grounds/runs/4187901999?check_suite_focus=true

**Comment by uranusjr** [comment] 2021-12-10 14:42
I tracked this down: https://bugs.python.org/issue45777

So yes, 3.9.8 is the only broken release, it’s built with faulty configuration. The solution is to use 3.9.9 (or anything but 3.9.8).

**Comment by layday** [comment] 2021-12-10 14:55
So this is supposed to be fixed in 3.9.9? Because 3.9.9 is failing for pypa/build on Windows.

**Comment by uranusjr** [comment] 2021-12-10 17:14
Yes, the 3.9.9 build of CPython is supposed to work (if you have LongPathsEnabled set correctly system-wide, of course; that is always a prerequisite).

**Comment by nikita-bykov** [comment] 2021-12-13 11:28
@layday I'm going to close the issue because it related to Python 3.9.8 and not to setup-python.
If you have any questions feel free to contact us.

**Closed by nikita-bykov** 2021-12-13 11:28 UTC
Labels: bug
