### ISSUE TITLE
How to setup pip cache?!? (And please enable github Discussions)

### ISSUE THREAD

**Issue by jedie** [actions/setup-python#194] opened 2021-03-26 18:44 UTC
The github discussion is not enabled in this project. So i just create this issues:

How can i setup cache for pip in actions?

**Comment by mrlubos** [comment] 2021-07-09 11:14
Hey @jedie, would this help? https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d

**Comment by hugovk** [comment] 2021-11-12 06:05
Good news, simpler caching is coming soon in https://github.com/actions/setup-python/pull/266!

**Comment by nikita-bykov** [comment] 2021-11-12 09:31
Thank you for opening issue! [This PR](https://github.com/actions/setup-python/pull/266) includes caching for pip and pipenv  dependencies.
I'm going to close this issue as duplicate of #226

**Closed by nikita-bykov** 2021-11-12 09:31 UTC
Labels: feature request
