### ISSUE TITLE
PIP_ROOT_USER_ACTION=ignore ignored: pip still issues error messages about running it as root

### ISSUE THREAD

**Issue by RoFz** [actions/setup-python#930] opened 2024-08-28 15:35 UTC
**Description:**
setup-action@v5 and python-version: 3.11 leads to pip's warnings about running as root, which should have been suppressed by [the install script](https://github.com/actions/python-versions/blob/main/installers/nix-setup-template.sh) on self-hosted runner and GHES 3.12.8.

**Action version:**
@v5

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
python 3.11 (3.11.9)

**Repro steps:**  

1. job running under an ubuntu:jammy container image, as root (without 'options: --user ...)
2. setup-python step like so:
```
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
```

**Expected behavior:**
No warnings, since the [the install script](https://github.com/actions/python-versions/blob/main/installers/nix-setup-template.sh) seems to properly export PIP_ROOT_USER_ACTION=ignore.

**Actual behavior:**
pip throws the known errors (warnings?) about running it as root:

```
Error: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behavior with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  Error: WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
```

This is related to https://github.com/actions/setup-python/issues/513, which, although initially opened as a feature request and closed as such, is still receiving updates from people impacted by the same problem.

**Comment by RoFz** [comment] 2024-08-28 15:36
Additional note: also tried with setup-python@v4 and specific python versions 3.11.9 and 3.11.8.

**Comment by priyagupta108** [comment] 2024-08-29 14:41
Hello @RoFz 👋,
Thank you for reporting this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by priya-kinthali** [comment] 2024-09-20 11:21
Hello @RoFz 👋,
Thankyou for reporting the issue! 
**The warning about the pip cache** within Docker containers arises because the directory `/github/home/.cache/pip` is either not owned by or not writable by the current user. The ownership and permissions might not align with the user running the pip command.
To resolve this issue, please try the following step before the setup-python action: 
```yaml                                                                                                                                                                                                    
 -name: Change ownership of /github/home
  run: sudo chown -R $(whoami) /github/home        
 ```  
**Regarding the warning related to running pip as root:** It appears that the `setup-python` action correctly sets the `PIP_ROOT_USER_ACTION=ignore` environment variable. However, the warning related to pip root user is still observed when attempting to upgrade pip outside of the setup-python action as well, as seen in this [GitHub Actions Run](https://github.com/setup-actions-demo/python-demo/actions/runs/10940923338/job/30374394876).
This behaviour is due to the fact that setting `PIP_ROOT_USER_ACTION=ignore` works only for `pip version` >=22.1, as per the [pip release notes](https://pip.pypa.io/en/stable/news/#b1-2022-04-30). It looks like the base environment includes `pip` 22.0.2 when setting up the environment. 
Therefore, this is expected behaviour and is not related to the `setup-python` action.
Hope this clarifies the situation.

**Comment by maikelvdh** [comment] 2024-09-27 10:43
@priya-kinthali the `PIP_ROOT_USER_ACTION` has no effect for the called `ensurepip` command which is printing this respective warning. Reason seems that this module is sanitising the environment context, see: https://github.com/python/cpython/blob/main/Lib/ensurepip/__init__.py#L97-L106.

**Comment by priya-kinthali** [comment] 2024-10-01 08:04
Hello @RoFz 👋,
I hope the suggested workaround has addressed the issue related to the pip cache warning.

Thank you, @maikelvdh, for your valuable insights regarding the pip cache warning 😊. As you correctly pointed out, the warning from the `ensurepip` command is due to the environment context being sanitized. 
>PIP_ROOT_USER_ACTION has no effect for the called ensurepip command which is printing this respective warning. 

Additionally, the PIP_ROOT_USER_ACTION=ignore variable is correctly set and functions as expected for pip versions >=23.0.2 in the `setup-python` action.
Since this behaviour is inherent to `pip` and not specifically related to the `setup-python` action, I am proceeding to close this issue. Please feel free to reopen this issue or create a new one incase of any further concerns.

Thank you for your patience! 😊

**Closed by priya-kinthali** 2024-10-01 08:04 UTC
Labels: bug
