### ISSUE TITLE
pip is configured with locations that require TLS/SSL

### ISSUE THREAD

**Issue by mathoyus** [actions/setup-python#217] opened 2021-06-10 08:44 UTC
root@ubuntu:/Python-3.7.1# pip3 install -r requirements.txt
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
root@ubuntu:/Python-3.7.1# pip install -r requirements.txt 
The program 'pip' is currently not installed. You can install it by typing:
apt-get install python-pip
root@ubuntu:/Python-3.7.1# 
**already configure python with ssl,also install a lot ssl-lig all kind** 
./configure --prefix=/usr/local/python3 --with-openssl=/usr/local/openssl
make
make install

**Comment by konradpabjan** [comment] 2021-06-15 13:30
Closing as this is a duplicate of https://github.com/actions/setup-python/issues/93

**Closed by konradpabjan** 2021-06-15 13:30 UTC
Labels: duplicate
