### ISSUE TITLE
is python 3.12.4 download assets broken

### ISSUE THREAD

**Issue by zoezhangmattr** [actions/setup-python#887] opened 2024-06-10 07:04 UTC
### Description

not sure where to report this issue. 

i am trying to build the image locally, using the packages in this repo
but failed 
Downloading package from https://github.com/actions/python-versions/releases/download/3.12.4-9442300799/python-3.12.4-linux-22.04-x64.tar.gz to /tmp/python-3.12.4-linux-22.04-x64.tar.gz
gzip: stdin: not in gzip format
==> /usr/bin/tar: Child returned status 1
==> /usr/bin/tar: Error is not recoverable: exiting now
==>  /usr/bin/bash: ./setup.sh: No such file or directory

when i download above gz file, i cant extract it either

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

not related to public runner

### Is it regression?

not sure

### Expected behavior

should be able to install 

### Actual behavior

gzip: stdin: not in gzip format
==> /usr/bin/tar: Child returned status 1
==> /usr/bin/tar: Error is not recoverable: exiting now
==>  /usr/bin/bash: ./setup.sh: No such file or directory

### Repro steps

run the packer build locally

**Comment by mikhailkoliada** [comment] 2024-06-10 11:25
transferring tl setup-python, it has nothing to do with the image-generation scripts

**Comment by fr33z3** [comment] 2024-06-10 11:44
Any news about that issue? My workflows are completely broken

**Comment by mbdevpl** [comment] 2024-06-10 12:17
I also think this is the root cause: https://github.com/actions/setup-python/issues/886 - and may be fixed there.

Workaround: https://github.com/actions/setup-python/issues/886#issuecomment-2157956036

**Comment by HarithaVattikuti** [comment] 2024-06-10 13:42
Hello @zoezhangmattr  
Thankyou for creating this issue. we are working on the fix and will get back to you sooner.

**Comment by aparnajyothi-y** [comment] 2024-06-12 03:26
Hello Everyone, we merged the fix for this issue. Please validate from your end and confirm.

**Comment by aparnajyothi-y** [comment] 2024-07-03 10:45
Hello @zoezhangmattr, The issue has been resolved, and new artifacts have been released. Our tests have confirmed their functionality, so we are closing this issue. Please validate your workflow again and feel free to contact us to reopen the issue if you encounter any problems.

**Closed by aparnajyothi-y** 2024-07-03 10:45 UTC
Labels: bug
