### ISSUE TITLE
CMake PythonLibs picking up wrong version

### ISSUE THREAD

**Issue by bjaraujo** [actions/setup-python#186] opened 2021-02-02 20:01 UTC
**Describe the bug**

When 

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.x
        architecture: x64

CMake seems to get the correct PythonInterp but the wrong PythonLibs. I wanted version 3.8.7 for both.

-- Found PythonLibs: C:/hostedtoolcache/windows/Python/3.9.1/x64/libs/python39.lib (found suitable version "3.9.1", minimum required is "3.0") 
-- Found PythonInterp: C:/hostedtoolcache/windows/Python/3.8.7/x64/python.exe (found suitable version "3.8.7", minimum required is "3.0") 

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)
3.8 and 3.9

**To Reproduce**

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**Screenshots**

**Additional context**

**Comment by pjb7687** [comment] 2021-02-08 01:22
I have a similar problem. In my case, CMake picks up the python with the wrong architecture.

I had a look at the relevant CMake file:
https://github.com/Kitware/CMake/blob/master/Modules/FindPythonInterp.cmake#L114-L119

and found that the script tries to find Python executable in the system registry (`FindPythonLibs.cmake` script also works in the same way). I think removing all the other registry entries might help.

**Comment by bjaraujo** [comment] 2021-02-09 10:34
I worked around this issue by passing the version to CMake I want in the command line. So if I specify a version:
 -DMY_PYTHON_VERSION=3.8.2 for example, I changed the CMake to call find_package with EXACT REQUIRED. If a version is not specified it just picks up any version as before.

**Comment by pjb7687** [comment] 2021-02-09 13:30
To be clear: I am using MSYS2 shell.
I solved this issue by manually adding the python executable to PATH:
```
export PATH=`cygpath "${pythonLocation}"`:$PATH
```
After that CMake finds the right one.

**Comment by nikita-bykov** [comment] 2021-12-30 11:19
Hello @bjaraujo! We apologize for such a late reply.
If the issue is still relevant to you, could you please provide repro steps?

**Comment by vlad-nn** [comment] 2022-01-06 00:07
Hi! I have similar problem for GH Windows build. 
In .yml file I have:

```
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pip'
```

In cmake I have:

`find_package(Python3 COMPONENTS Interpreter Development)`

GH logs tell this:

```
Run actions/setup-python@v2
  with:
    python-version: 3.8
    cache: pip
    token: ***
  env:
    BUILD_TYPE: Release
Successfully setup CPython (3.8.10)
```

And then this:

`-- Found Python3: C:/hostedtoolcache/windows/Python/3.10.1/x64/python3.exe (found version "3.10.1") found components: Interpreter Development `

As you see, setup-python@v2 correctly finds Python 3.8, but CMake finds Python 3.10.

The same yml/cmake works correctly in Ubuntu build.

**Comment by nikita-bykov** [comment] 2022-01-06 10:10
Hello @vlad-nn! 
Could you please provide a public repository with repro steps so we can investigate the issue in more detail?

**Comment by vlad-nn** [comment] 2022-01-06 19:41
Hi @nikita-bykov, 

Here it is: https://github.com/vlad-nn/PythonVersionDemo

As you can see in actions log (https://github.com/vlad-nn/PythonVersionDemo/runs/4731282330):

- 'Setup Python' step selects ver. 3.8.10:
`Successfully setup CPython (3.8.10)`

- while cmake in 'Configure CMake' step finds ver. 3.10.1:

```
-- Python3_EXECUTABLE = C:/hostedtoolcache/windows/Python/3.10.1/x64/python3.exe
-- Python3_STDLIB     = C:\hostedtoolcache\windows\Python\3.10.1\x64\Lib
-- Python3_STDARCH    = C:\hostedtoolcache\windows\Python\3.10.1\x64\Lib
-- Python3_SITELIB    = C:\hostedtoolcache\windows\Python\3.10.1\x64\Lib\site-packages
-- Python3_INCLUDE_DIRS = C:/hostedtoolcache/windows/Python/3.10.1/x64/include
-- Python3_LIBRARY_DIRS = C:/hostedtoolcache/windows/Python/3.10.1/x64/libs
-- Python3_RUNTIME_LIBRARY_DIRS = C:/hostedtoolcache/windows/Python/3.10.1/x64
```

**Comment by nikita-bykov** [comment] 2022-01-12 09:25
@vlad-nn, I have tested this behavior in your repository and investigated the CMake documentation, it looks like the issue is how CMake looks for Python versions on Windows. 
To solve your issue you should set variable `Python3_FIND_REGISTRY` with value `LAST` or `NEVER`, it will allow CMake to look for Python in environment variables first ([link to documentation](https://cmake.org/cmake/help/git-stage/module/FindPython3.html#:~:text=Python3_FIND_REGISTRY,Never%20try%20to%20use%20registry)):
```
set(Python3_FIND_REGISTRY "LAST")
```
For example, in the repository that you provided, in the `CMakeLists.txt` file, I added this command before `find_package` and CMake determined the Python version correctly.
[This comment](https://github.com/actions/setup-python/issues/121#issuecomment-777748504) describes this behavior in more detail.

**Comment by vlad-nn** [comment] 2022-01-12 18:25
@nikita-bykov, thank you so much for your help! Very appreciated.

**Comment by nikita-bykov** [comment] 2022-01-17 12:20
Hello @bjaraujo! This issue is not related to setup-python action (more details in my [comment](https://github.com/actions/setup-python/issues/186#issuecomment-1010828971) above), so I'm going to close it, but if you have any questions, feel free to contact us.

**Closed by nikita-bykov** 2022-01-17 12:20 UTC
Labels: bug
