### ISSUE TITLE
Uncached python version getting uncompressed in repo dir

### ISSUE THREAD

**Issue by phoolish** [actions/setup-python#106] opened 2020-07-08 22:05 UTC
**Describe the bug**
Ran into an issue if the python version needs to be downloaded, the tar'd file is uncompressed in the same directory as the `- uses: actions/checkout@v2` step. This caused our python linter to fail. We had to reorder the steps, so that the `setup-python` action was run before the checkout step.

`/bin/tar xz --warning=no-unknown-keyword -C ./UUID -f /home/runner/work/_temp/UUID`

**Which version of the action are you using?**

- [x] `v2`

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
3.6.10

**To Reproduce**
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.10
      - run: pip install flake8
      - run: flake8 .
```

**Solved by**
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.10
      - uses: actions/checkout@v2
      - run: pip install flake8
      - run: flake8 .
```

**Comment by konradpabjan** [comment] 2020-07-10 11:15
Looks like a duplicate of https://github.com/actions/setup-python/issues/101

This is being fixed but the root cause is the same. Downloads of Python will be uncompressed in the runner temp directory

**Comment by MaksimZhukov** [comment] 2020-07-21 11:34
Hello @phoolish !
We have provided a solution for this issue. Please see this [issue](https://github.com/actions/setup-python/issues/101) for more details

**Closed by MaksimZhukov** 2020-07-21 11:34 UTC
Labels: bug
