### ISSUE TITLE
Continued problem  from https://github.com/actions/cache/issues/1031

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [actions/setup-python#570] opened 2022-12-20 15:47 UTC
Yes, and we posted at https://github.com/orgs/community/discussions?discussions_q=PySide2
The suggestion given at [this](https://github.com/actions/cache/issues/1031) issue was not the remedy to fix CI testing. 

**Description:**

We are having an issue, possibly with caching on our repo https://github.com/Qiskit/qiskit-metal. Our CI suddenly broke because one of our dependencies, PySide2, is not in our environment. We didn't make any changes to our pipeline file. It is clear that something is going wrong with the environment that GitHub Actions is creating for us, but we are unaware of where the issue is actually coming from and how to diagnose it, given that GitHub is controlling the environment. Based on this issue, we are writing to you, but in addition, we are going to consult with the GitHub Actions [Customer Support](https://github.com/orgs/community/discussions?discussions_q=PySide2).

We deleted all old caches and had GitHub create a new cache entry. Unfortunately, the same issue persists. We also tried creating our environment locally identically to how it is being created by GitHub Actions, and the environment was created without issue and was able to import PySide2.

We implemented the suggestion by response to cache-issue-1031, unfortunately, that did not fix the problem: 
Hi @obrienpja, I checked your previous successful runs and recent failed runs and found you are running apt install for installing specific dependencies which has probably broken with the latest ubuntu release. This has happened now because the tag ubuntu-latest points to ubuntu-22.04 instead of the previous ubuntu-20.04. Please see [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). For now, try running your workflows with the pinned ubuntu version i.e ubuntu-20.04 in runs-on or use a self-hosted image that runs ubuntu 20.04. Closing this issue as it is not related/relevant to actions/cache.

You can view branch at https://github.com/Qiskit/qiskit-metal/pull/887.

We  wondering why PySide2 is not being imported anymore into the python environment. 

@obrienpja 

**Action version:**
Specify the action version
We had v2, but also tried v3. 

**Platform:**
- [ x] Ubuntu
- [ x] macOS
- [ ] Windows

**Runner type:**
- [ x] Hosted
- [ ] Self-hosted

**Tools version:**
 3.9, 3.10

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
https://github.com/Qiskit/qiskit-metal/pull/887

**Expected behavior:**
A description of what you expected to happen.
CI continue as it was working previously. 

**Actual behavior:**
A description of what is actually happening.
CI is failing for every commit.

**Comment by MaksimZhukov** [comment] 2022-12-20 15:58
Hello @priti-ashvin-shah-ibm ! Thanks for reporting this!
We will investigate the issue and come back to you as soon as we have any updates

**Comment by priti-ashvin-shah-ibm** [comment] 2022-12-20 16:18
> Hello @priti-ashvin-shah-ibm ! Thanks for reporting this! We will investigate the issue and come back to you as soon as we have any updates

@MaksimZhukov ,Thank you for you triage, we are 100% blocked until this is resolved.  We appreciate your time and support regarding this issue.

**Comment by MaksimZhukov** [comment] 2022-12-22 13:54
@priti-ashvin-shah-ibm, the issue is not related to the `setup-python` action or runner images. 

You install `tox` in scope of the [`Install Deps` step](https://github.com/Qiskit/qiskit-metal/blob/main/.github/workflows/main.yml#L39). Tox `3.27.1` was installed during the [last successful build](https://github.com/Qiskit/qiskit-metal/actions/runs/3630793091/jobs/6124579484#step:5:10) and tox `4.0.8` was installed during the [first failed build](https://github.com/Qiskit/qiskit-metal/actions/runs/3686915714/jobs/6239805065#step:5:10). It looks like your tests don't work with the new major version of tox.

To fix the issue, please adjust your tests or install the previous major version of tox:
```yml
      - name: Install Deps
        run: |
          python -m pip install -U git+https://github.com/tox-dev/tox.git@3.28.0 setuptools virtualenv wheel
          sudo apt install libglu1-mesa libglu1-mesa-dev
```

I am closing the issue. Feel free to contact us if you have any questions.

**Closed by MaksimZhukov** 2022-12-22 13:54 UTC
Labels: bug

**Comment by obrienpja** [comment] 2022-12-22 13:55
Thank you @MaksimZhukov!

**Comment by priti-ashvin-shah-ibm** [comment] 2022-12-22 15:33
Thank you, that solved our short term problem of getting CI to work.

**Comment by priti-ashvin-shah-ibm** [comment] 2022-12-22 20:37
The below image is a commit that failed.  The interesting part is that the same commit passed before the merge.  The time between passing and the merge was about 2 weeks.  Also, nothing in github actions was changed.   

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/74020801/209221194-e032f534-5695-4141-ba01-8085d75bf6f7.png">

**Comment by priti-ashvin-shah-ibm** [comment] 2022-12-22 20:41
This is the same commit just before the merge where it passed.

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/74020801/209222251-e2d3549c-ae45-41d1-89c6-55f15a2fde53.png">

**Comment by priti-ashvin-shah-ibm** [comment] 2022-12-22 20:42
So sorry, wrong link was used.
