### ISSUE TITLE
When installing python 3.9 on v2 throws annoying warning that displays as error after actions is completed.

### ISSUE THREAD

**Issue by AraHaan** [actions/setup-python#156] opened 2020-10-20 18:28 UTC
**Describe the bug**
When installing python 3.9 from this action, it complains about the x64 and x86 python script dirs not being in the PATH.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)
3.9 stable

**To Reproduce**
1. Try this in both x86 and x64
```yml
 - uses: actions/setup-python@v2
   with:
     python-version: '3.9'
     architecture: 'x86'
```
2. Wait for it to download and install.
3. Notice that after it tries to upgrade pip that it throws an warning that is annoying to see.
4. Notice that after the action is 100% completed on the job that it shows up as an error as shown in the screenshot below.

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.
(RUN) -> https://github.com/AraHaan/pthmgr/actions/runs/317209470
(Repo) -> https://github.com/AraHaan/pthmgr/

**Screenshots**
![image](https://user-images.githubusercontent.com/15173749/96628067-c2caa700-12df-11eb-990a-cb888139d972.png)

**Additional context**
I would like this problem fixed somehow, I think that is also supposed to be added to the path as well temporarily so it can shut up.

**Comment by cclauss** [comment] 2020-10-20 19:31
Duplicate of #146

**Closed** 2020-11-09 22:16 UTC
Labels: duplicate
