### ISSUE TITLE
Python3.9 on aarch64 for macOS 13.4.1.

### ISSUE THREAD

**Issue by tvorogme** [actions/setup-python#696] opened 2023-07-03 19:38 UTC
**Description:**
  Error: The version '3.9' with architecture 'arm64' was not found for macOS 13.4.1.

**Action version:**
 'actions/setup-python@v4' (SHA:bd6b4b6205c4dbad673328db7b31b7fab9e241c0)

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
(aarch64, macOS, Python3.9)

**Repro steps:**  
```
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
```

**Expected behavior:**
Successfully installed python

**Actual behavior:**
Error message

**Comment by dusan-trickovic** [comment] 2023-07-04 10:43
Hello, @tvorogme ! Thank you for creating this issue, we'll investigate it and see what can be done :)

**Comment by tvorogme** [comment] 2023-07-06 08:39
@dusan-trickovic hey! When approximately can we expect a fix? I really need this container for cross-platform distribution of the package.

**Comment by dusan-trickovic** [comment] 2023-07-14 17:36
Hello again, @tvorogme ! I just wanted to check in with you and ask you if you could please try using Python version such as `3.10.11` in your workflow? From the description of your problem, it seems as though that version of Python just simply doesn't exist for your specific architecture in the versions repository (while there is an `arm64` option for `3.10.11` for `darwin`).

Newer versions (such as `3.11` and `3.12` `alpha` and `beta`) also seem to have support for `arm64`, but I suggested `3.10.11` as it is the closest to the one you need. If it won't affect your own personal requirements for the project, I would suggest trying to use the suggested version and seeing if that fixes the error you've encountered.

If you encounter any more issues (similar to this or otherwise), please don't hesitate to reach out again. On the other hand, if this solved your issue, you can also let us know about it so that we can close it.

Thank you very much for your cooperation :)

**Comment by tvorogme** [comment] 2023-07-15 08:07
@dusan-trickovic hey! Glad you right back.

Thanks for the idea, but it doesn't work for me. We are developing a package that should be available on: Windows / Linux / macOS. Since we work with pybind11 we are tied to the major python releases, so we support py3.9 / py3.10 / py3.11. If we make a package for py3.10 it means it won't work for py3.9.

As a temporary solution, I made a [separate workflow](https://github.com/disintar/tonpy/blob/main/.github/workflows/wheels.yml#L128) just for macOS *aarch64* / *x86_64* that installs python3.9 from brew, because it's not working from `actions/setup-python`. But it's very ugly. 

Your workflow works for all other versions, and it's very cool.

You also can look at [status of python versions](https://devguide.python.org/versions/), the Python3.9 is not `end-of-life` status.

<img width="910" alt="Screenshot 2023-07-15 at 11 01 42 AM" src="https://github.com/actions/setup-python/assets/19264196/b868d612-5239-4931-9941-92f34a12a200">

**Comment by dusan-trickovic** [comment] 2023-07-17 08:23
Hello again @tvorogme ! I just wanted to drop an update here and say that, at this time, we only have `arm64` support for versions `3.10` and later. Therefore, although `3.10` and `3.11` fit this criteria, `3.9` unfortunately doesn't, though we will investigate that too in the future.

Thank you very much for your time and cooperation :)

**Comment by richard-scott** [comment] 2023-10-28 13:32
I can't believe this is still a problem 3 years after Python started supporting the M1 architecture.

However, it's not just Apple hardware having problems as I have issues with major version numbers such as version '3.10' with architecture 'arm64' was not found for Debian 12.

**Comment by rwader-swi** [comment] 2024-03-13 07:53
i'm getting the same for 3.9 on Debian 😞

**Comment by ianspektor** [comment] 2024-03-13 14:39
For anyone else with this problem, we resolved to drop setup-python and just install python, pip, and poetry manually. Full working example here: https://github.com/google/temporian/blob/main/.github/workflows/publish.yaml

```
build-macos-arm:
    runs-on: macos-13-xlarge
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          brew update
          brew install python@${{ matrix.python-version }}

      - name: Install pip
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python${{ matrix.python-version }} get-pip.py

      - name: Install poetry
        run: pip install poetry
```

**Comment by richard-scott** [comment] 2024-03-13 14:53
Are you all using v5 of the Action??

`uses: actions/setup-python@v5`

**Comment by ianspektor** [comment] 2024-03-13 15:28
We were using v4 before switching to the manual installations, haven't tried v5 on arm

**Comment by bswck** [comment] 2024-04-22 19:07
[Ran into the same issue with Python 3.8](https://github.com/bswck/lazy_importing/actions/runs/8789482932/job/24119337850).

**Comment by mjurbanski-reef** [comment] 2024-04-23 08:54
I also just got hit by this for all 3.7-3.9 version while using macos-latest successfully for year or so in GHA.
I'm testing library that deals with some low level filesystem handling at times, hence why testing on multiple platforms on multiple python versions is essential and not optional.

As indicate above, I can understand python versions beyond EoL not working, but it is disapointing to see others stopped working as well.
To make matters worse, since my workflow uses multiple repositories and jobs, it seems I'm only seeing this error out on some, and not others, probably caused by [incremental rollout of macos 14]( https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/) .

I also test pypy3.9 and pypy3.10 - should I expect pypy3.9 to stop working on macos-latest any day now as well?

**Comment by pd-nisse** [comment] 2024-04-23 17:11
We observe the same issue as @mjurbanski-reef - we've been running Python 3.8 + 3.9 successfully last year, but it appears the macos 14 rollout broke the CI together with the missing python arm builds last night.
```
  Version 3.8 was not found in the local cache
  Error: The version '3.8' with architecture 'arm64' was not found for macOS 14.4.1.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by armingh2000** [comment] 2024-04-23 17:29
Same here:
  Error: The version '3.9' with architecture 'arm64' was not found for macOS 14.4.1.

**Comment by hugovk** [comment] 2024-04-23 18:37
> EDIT:
> I think they are removing 3.9 and 3.10 support for macos 14.

See upthread, macOS 14 never had 3.9 and 3.10: https://github.com/actions/setup-python/issues/696#issuecomment-1637587760

> I just wanted to drop an update here and say that, at this time, we only have `arm64` support for versions `3.10` and later. Therefore, although `3.10` and `3.11` fit this criteria, `3.9` unfortunately doesn't, though we will investigate that too in the future.

---

> They also removed 3.9 and 3.10 supports in the docs last week ([1](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md?rgh-link-date=2024-04-23T17%3A29%3A04Z), [2](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md?rgh-link-date=2024-04-23T17%3A29%3A04Z).)

I don't think think those docs every claimed 3.9 or 3.10 support? I don't see it in the Git log.

**Comment by armingh2000** [comment] 2024-04-23 20:07
> I don't think think those docs every claimed 3.9 or 3.10 support? I don't see it in the Git log.

Yes @hugovk, you are right. I misunderstood [this](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md#cached-tools) with not supporting 3.10. 

Also, is there going to be a support matrix?

**Comment by sitic** [comment] 2024-04-24 07:16
This should be fixed by PR
- actions/python-versions#259

see https://github.com/actions/setup-python/issues/808#issuecomment-1950058596:
> > [actions/python-versions#214](https://github.com/actions/python-versions/pull/214) enabled 3.8 & 3.9 for macOS arm64. It's probably a matter of starting the builds there ?
> 
> The build for 3.8 & 3.9 was broken by [actions/python-versions#223](https://github.com/actions/python-versions/pull/223) I opened [actions/python-versions#259](https://github.com/actions/python-versions/pull/259) so it's now a matter for maintainers to review that PR then start a build.

**Comment by aparnajyothi-y** [comment] 2024-08-21 13:03
Hello Everyone, We have already added arm64 support for Python version 3.9. Please find the attached screenshot for reference. Please validate from your end and confirm. 

<img width="1044" alt="Screenshot 2024-08-20 at 6 56 37 PM" src="https://github.com/user-attachments/assets/313ff6cd-4e57-4ec5-bb87-32e472381024">

**Comment by hugovk** [comment] 2024-08-24 13:56
Confirmed, thanks!

https://github.com/hugovk/Pillow/actions/runs/10504390275/job/29101211666

**Comment by aparnajyothi-y** [comment] 2024-08-29 04:04
Thanks @hugovk for the confirmation and proceeding to close the issue as issue addressed and confirmed.

**Closed by aparnajyothi-y** 2024-08-29 04:04 UTC
Labels: bug
