### ISSUE TITLE
Cross-OS Version Cache Pollution

### ISSUE THREAD

**Issue by Kurt-von-Laven** [actions/setup-python#589] opened 2023-01-18 10:59 UTC
**Description:**
A cache saved on one version of a given OS can be restored on a different version of that OS. Package managers and individual packages typically assume the OS version wasn't swapped out from under them, so this can produce a wide variety of issues. See actions/cache#543 for evidence that this is a real problem with GitHub Actions in general and the officially recommended solution.

**Action version:**
v4.5.0

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**
All

**Repro steps:**  

1. Save a cache on ubuntu-20.04, for example.
2. Attempt to restore the cache on ubuntu-22.04.

**Expected behavior:**
The cache misses and is saved again.

**Actual behavior:**
The cache hits and is restored.

**Comment by e-korolevskii** [comment] 2023-01-18 13:46
Hello @Kurt-von-Laven! Thank you for reporting this!
We will investigate the issue and get back to you as soon as we have updates.

**Comment by e-korolevskii** [comment] 2023-02-09 08:45
Hello @Kurt-von-Laven!
After investigation, we were unable to reproduce the issue.
I will now close this issue as a [duplicate](https://github.com/actions/setup-python/issues/432).
You can add comments here or open a new issue if this doesn't solve your problem.

Have a nice day!

**Closed by e-korolevskii** 2023-02-09 08:45 UTC
Labels: bug
