### ISSUE TITLE
Install fails: regression in v4 compared do v3

### ISSUE THREAD

**Issue by adrinjalali** [actions/setup-python#634] opened 2023-03-27 08:31 UTC
**Description:**
We noticed a while ago that some of our actions are failing due to failing `import` statements. After investigating, @benjaminbossan managed to have a minimal reproducible which you can see here: https://github.com/BenjaminBossan/mops/pull/10

Somehow `pip install .` doesn't properly install the package in `site-packages` with v4, while it does with v3. The PR linked above shows two actions, the difference being the version of `setup-python`, one passing the other one failing.

**Action version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
Explained here: https://github.com/BenjaminBossan/mops/pull/10

**Expected behavior:**
Package should be installed properly.

**Actual behavior:**
Files are missing from the installation folder.

**Comment by e-korolevskii** [comment] 2023-03-27 08:59
Hello @adrinjalali 
Thank you for your report. We'll investigate the issue and get back to you.

**Comment by dmitry-shibanov** [comment] 2023-03-27 09:14
Hello @adrinjalali. Thank you for your report. I think it's an expected behaviour because previously if python-version is empty the action will set it to `3.x`. For setup-python@v4 it will try to find `.python-version` and if it is not found it will use default python on the machine. Could you please try to specify `python-version: 3.x` ?

**Comment by adrinjalali** [comment] 2023-03-27 09:51
Thanks for the quick response. That kinda fix the issue, but only if we set the python version to  >=3.10. It fails with <=3.9.

Tested in the same PR: https://github.com/BenjaminBossan/mops/pull/10, the last 4 runs show the difference.

**Comment by dmitry-shibanov** [comment] 2023-05-08 23:18
Hello @adrinjalali. For now I'm going to close the issue because it was an expected change made in v4.

**Closed by dmitry-shibanov** 2023-05-08 23:18 UTC
Labels: bug

**Comment by adrinjalali** [comment] 2023-05-09 08:48
@dmitry-shibanov is the expected behavior that we can't install the package correctly in older python versions? 

If you have a look at the last 4 commits here (https://github.com/BenjaminBossan/mops/pull/10) you see that this issue is not fixed, and I don't think the expected behavior is that it fails for older python versions.
