### ISSUE TITLE
subprocess.Popen issues with pypy actions

### ISSUE THREAD

**Issue by olliemath** [actions/setup-python#784] opened 2023-12-28 16:28 UTC
**Description:**

Calling `import venv; venv.create("venv", with_pip=True)` fails for the pypy actions, but not for cpython or for manually (via apt) installed pypy binaries.

Specifically the `subprocess.Popen` step of that command fails (although it succeeds outside of the venv 

**Action version:**
v5

**Platform:**
- [ ] Ubuntu

**Runner type:**
- [ ] Hosted

**Tools version:**
pypy 3.9 and 3.10

**Repro steps:**  

See the yaml in this repo: https://github.com/olliemath/actions-example/blob/main/.github/workflows/ci.yml

Here is an example of the passing/failing jobs: https://github.com/olliemath/actions-example/actions/runs/7349327941

**Expected behavior:**

Expected the subprocess.Popen command to work as expected during the "ensurepip" phase of venv creation.

**Actual behavior:**

The subprocess.Popen exits with status code 127

**Comment by nulano** [comment] 2023-12-28 23:23
I think this may be caused by https://foss.heptapod.net/pypy/pypy/-/issues/4019 which should be fixed in PyPy 7.3.14 released 3 days ago (your log is still showing 7.3.13). I would guess this will be fixed on GHA when that version is cached in the next `ubuntu-latest` image.

**Comment by olliemath** [comment] 2023-12-30 12:47
Ah, thanks - that's helpful - I guess my finding it coincided with the version in apt being newer than the version in the actions. I'll keep this open until 7.3.14 makes it into ubuntu-latest and if that works will close

**Comment by aparnajyothi-y** [comment] 2024-01-01 04:32
Hello @olliemath, Thank you for creating this issue, we will investigate further:)

**Comment by mahabaleshwars** [comment] 2024-01-11 11:51
Hello @olliemath, PyPy version 7.3.14 is updated in the ubuntu-latest PR. It will be available once the PR is merged to main branch. 
<img width="906" alt="Screenshot 2024-01-11 at 17 13 38" src="https://github.com/actions/setup-python/assets/147705296/1382f442-50b5-4037-8c92-339edd356998">

**Comment by mahabaleshwars** [comment] 2024-01-17 13:59
Hi @olliemath, The issue is resolved with the version PyPy 7.3.14 which is default in the ubuntu-latest. I am closing the issue. Let us know if you still find the issue unresolved.

![Image](https://github.com/actions/setup-python/assets/147705296/79c5e0ca-936e-413f-80c6-92ce4a6d35c9)

**Closed** 2024-04-18 12:54 UTC
Labels: bug
