### ISSUE TITLE
Python 3.9 beta adding source to tree

### ISSUE THREAD

**Issue by adamchainz** [actions/setup-python#117] opened 2020-07-17 11:24 UTC
**Describe the bug**

When adding `3.9.0-beta.4` (as announced in #20) to my project apig-wsgi (https://github.com/adamchainz/apig-wsgi/pull/158), I got an error on 3.9 only from Pytest:

```

2020-07-17T11:06:44.2808745Z ==================================== ERRORS ====================================
2020-07-17T11:06:44.2809998Z _ ERROR collecting 9a5dbe51-7fe1-4ab4-89ee-1c8ead1d420a/lib/python3.9/test/test_capi.py _
...
2020-07-17T11:06:44.2816009Z E   AttributeError: 'builtin_function_or_method' object has no attribute '__dict__'
```

It looks like the Python 3.9 source tree is instaled inside my runner directory in a UUID-named directory, and pytest is searching that for tests.

I could tell pytest to not search that directory for tests, but I'm not sure there won't be other repercussions of the source tree being there for other tools. Not to mention this will probably affect any project using pytest.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**

As above

**To Reproduce**

As above

**Run/Repo Url**

https://github.com/adamchainz/apig-wsgi/pull/158

**Screenshots**

n/a

**Additional context**
n/a

**Comment by konradpabjan** [comment] 2020-07-17 13:51
This looks like a duplicate of https://github.com/actions/setup-python/issues/101 and https://github.com/actions/setup-python/issues/106 

We're working on a fix. This effects all non-cached versions of Python that must be downloaded and installed during the run. If you're using cached versions that come preinstalled on our hosted runners (such as `3.8.3`), this does not effect them.

**Closed by konradpabjan** 2020-07-17 13:51 UTC
Labels: duplicate

**Comment by adamchainz** [comment] 2020-07-19 13:10
Thank you. I've subscribed to the relevant issues.

**Comment by MaksimZhukov** [comment] 2020-07-21 11:31
Hello @adamchainz !
We have provided a solution for this issue. Please see this [issue](https://github.com/actions/setup-python/issues/101) for more details
