### ISSUE TITLE
pytest failing in python jobs with generic `line 1:  1950 Killed pytest`

### ISSUE THREAD

**Issue by GitToby** [actions/setup-python#612] opened 2023-02-14 12:07 UTC
**If this is the wrong place to look for assistance on this pytest issue, please advise where I should ask.**

---

**Description:**
When running pytests after setting up python they seem to be killed off by a shell process I have no control over:

```
2023-02-14T11:40:01.3053346Z ============================= test session starts ==============================
2023-02-14T11:40:01.3064479Z platform linux -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0 -- /opt/hostedtoolcache/Python/3.10.9/x64/bin/python
2023-02-14T11:40:01.3066165Z cachedir: .pytest_cache
2023-02-14T11:40:01.3066880Z benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
2023-02-14T11:40:01.3116999Z rootdir: /home/runner/work/data-processing-benchmarks/data-processing-benchmarks, configfile: pyproject.toml, testpaths: test
2023-02-14T11:40:01.3117546Z plugins: benchmark-4.0.0
2023-02-14T11:40:01.7657138Z collecting ... collected 2 items
2023-02-14T11:40:01.7657637Z 
2023-02-14T11:43:10.3632115Z /home/runner/work/_temp/29afaf1a-12f3-4d18-ad63-ddf9001f4ef3.sh: line 1:  1950 Killed                  pytest
2023-02-14T11:43:10.3651862Z test/test_performance.py::test_pandas 
2023-02-14T11:43:10.3983142Z ##[error]Process completed with exit code 137.
```
[job link](https://github.com/GitToby/data-processing-benchmarks/actions/runs/4173401460/jobs/7225676938#step:10:21),  other [jobs](https://github.com/GitToby/data-processing-benchmarks/actions/workflows/main.yaml) failed with similar issues

**Action version:**
setup-python@v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Seen in both [py3.10](https://github.com/GitToby/data-processing-benchmarks/actions/runs/4173401460/jobs/7225676938#step:10:21) and [3.11](https://github.com/GitToby/data-processing-benchmarks/actions/runs/4173218910/jobs/7225284968#step:10:21) explicitly. Trying to run with `python-version: [ "pypy3.8", "3.8", "pypy3.9", "3.9", "3.10", "3.11" ]`

**Repro steps:**  
Public repo: [GitToby/data-processing-benchmarks](https://github.com/GitToby/data-processing-benchmarks/actions)

**Expected behavior:**
Pytest should run & produce benchmarks with pytest-benchmark. (note: removed benchmark as I thought that may be an issue, no luck).

pytests run locally no issue, incl with benchmarks.

**Actual behavior:**
Job is failing with something along the lines of:
```
/home/runner/work/_temp/29afaf1a-12f3-4d18-ad63-ddf9001f4ef3.sh: line 1:  1950 Killed                  pytest
```

**Comment by MaksimZhukov** [comment] 2023-02-14 14:04
Hello @GitToby! Thank you for reporting this!
We will investigate the issue and get back to you as soon as we have updates.

**Comment by GitToby** [comment] 2023-02-15 01:28
simmilar issue: #350

**Comment by GitToby** [comment] 2023-02-19 20:32
@MaksimZhukov anoy luck? Even some pointers would be great to get me understanding what may be going on under the hood would be great

**Comment by dmitry-shibanov** [comment] 2023-02-20 15:04
Hello @GitToby. Sorry for the late response. It looks like the issue comes from the pytest library or your set up because I've tried to use the default python on the machine and got the same error. I think it fails because you are using large chunks of data and it takes up a lot of memory

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2023-02-20 15:04 UTC
Labels: bug

**Comment by GitToby** [comment] 2023-02-22 03:29
what do you mean "default python"? I ran the pytest command (as described in the yaml def w/ win 3.10 and 3.11) and it worked for me on both a win10 machine and Mac M1 machine.

**Comment by dmitry-shibanov** [comment] 2023-02-22 11:59
I mean that I used the python which one is built not from our side and I could reproduce the same behaviour. Besides, the action works as expected it sets up python without any issues. For me it looks like it is the issue with your set up or it goes out of memory.
