### ISSUE TITLE
Error Relocating...symbol not found

### ISSUE THREAD

**Issue by shellscape** [actions/setup-python#383] opened 2022-04-11 16:39 UTC
**Description:**

Using `ubuntu-latest` with the following config:

```yaml
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
```

In a separate step, I'm running a sanity check:

```yaml
      - name: Sanity Check
        run: |
          echo git `git version`;
          echo branch `git branch --show-current`;
          echo node `node -v`;
          echo pnpm `pnpm -v`
          echo python `python --version`
```

**Action version:** v3
Specify the action version

```
Run actions/setup-python@v3
  with:
    python-version: 3.x
    token: ***
/usr/bin/docker exec  5ebe4 b6fa9dcde1886c2178b0171516e8629bbd2a121bebb90e9f148423 sh -c "cat /etc/*release | grep ^ID"
Successfully setup CPython (3.10.4)
```

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
See above

**Expected behavior:**
Python version output

**Actual behavior:**

Sanity check output:

```
git git version 2.34.1
branch
node v16.14.2
pnpm 6.32.3
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __fprintf_chk: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __printf_chk: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __memcpy_chk: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __vsnprintf_chk: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: preadv64v2: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __vfprintf_chk: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: sem_clockwait: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: fcntl64: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __strcpy_chk: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __open64_2: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __sprintf_chk: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __realpath_chk: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: pwritev64v2: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __memmove_chk: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __sched_cpualloc: symbol not found
Error relocating /__t/Python/3.10.4/x64/lib/libpython3.10.so.1.0: __sched_cpufree: symbol not found
python
```

**Comment by dmitry-shibanov** [comment] 2022-04-11 17:13
Hello @shellscape. Thank you for your report. What docker image are you using?

**Comment by shellscape** [comment] 2022-04-11 17:16
I'm not. I'm specifying `runs-on: ubuntu-latest` in the action.

**Comment by dmitry-shibanov** [comment] 2022-04-11 17:34
Could you please share a link to the public repository? I've tried to reproduce the issue but everything works as expected.

**Comment by shellscape** [comment] 2022-04-11 17:39
My apologies, I've been context switching frequently this morning; This workflow is using a container. This is within a private repo which I cannot grant you access to unfortunately. Here's the Dockerfile for the container:

```golang
FROM golang:1.18 AS go
WORKDIR /temp/go
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM node:16-alpine
RUN apk add --update bash curl git libc6-compat
RUN npm install pnpm -g && pnpm add aws-cdk -g
ENV GOPATH /go
ENV PATH $GOPATH/bin:$PATH
COPY --from=go $GOPATH $GOPATH

CMD ["/bin/bash"]
```

**Comment by dmitry-shibanov** [comment] 2022-04-11 18:02
I think the issue is expected because containers are based on alpine, that is why it has issues. For ubuntu container it works as expected. The setup-python uses versions configured in [python-versions](https://github.com/actions/python-versions)

**Comment by shellscape** [comment] 2022-04-11 18:18
> because containers are based on alpine, that is why it has issues

Would it be possible to elaborate, and perhaps provide references? I'm not intimately familiar with setting up python in either environment, nor `setup-python` and I don't know why it's expected nor why alpine has a bearing on it.

**Comment by dmitry-shibanov** [comment] 2022-04-11 18:36
Python versions are built on hosted runners GitHub actions provides. It's macOS-10.15, ubuntu-18.04, ubuntu-20.04. For Windows the python-versions repository does not build, it downloads installation executables. 

I think the issue is expected, because python is built for ubuntu images, that is why it gets error for alpine images.

**Comment by shellscape** [comment] 2022-04-11 18:48
I see. It may be worthwhile to add that information to the readme here.

**Comment by dmitry-shibanov** [comment] 2022-04-20 12:48
Hello @shellscape. We updated documentation with note about python versions in scope of this [pull request](https://github.com/actions/setup-python/pull/388). 

For now I'm going to close the issue. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2022-04-20 12:48 UTC
Labels: documentation
