### ISSUE TITLE
Action doesn't work on macos if you uninstall Homebrew

### ISSUE THREAD

**Issue by Israphel** [actions/setup-python#290] opened 2021-12-07 22:00 UTC
**Description:**
Action fails on macos if you uninstall Homebrew before.

**Action version:**
v2

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Tested with 3.8 and 3.9

**Repro steps:**  
Run a shell script uninstalling Homebrew:

```
#!/usr/bin/env bash

# Download and run the uninstall script.
curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
chmod +x ./uninstall.sh
sudo ./uninstall.sh --force

# Clean up Homebrew directories.
sudo rm -rf /usr/local/Homebrew
sudo rm -rf /usr/local/Caskroom
sudo rm -rf /usr/local/bin/brew
```

Now use this action to setup python, and try to use pip install something after.

**Expected behavior:**
Python should work.

**Actual behavior:**
You get:

```
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/runner/hostedtoolcache/Python/3.9.9/x64/bin/python
  Reason: image not found
```

**Use case:**
We're testing an Ansible playbook that, among other things, installs Homebrew (if not present) and then uses it to install packages. The first part would be untested on CI if we don't uninstall Homebrew first (included by default on GHA).
Ansible can still be installed/used without running this Setup Python Action, but it will be running with Python 2.7 and you can't use another Action for caching a virtualenv; which saves aprox 5 minutes in Ansible installation alone.

**Comment by nikita-bykov** [comment] 2021-12-08 06:51
Hello @Israphel, thanks for reporting!
We will take a look at this issue.

**Comment by Sergey-Murtazin** [comment] 2021-12-27 15:08
Hi, @Israphel!

I've analyzed ways to solve your problem and found this one

To make it work you need
1. wget MacPorts
2. After this you can uninstall `brew`. Because `wget` was installed with `brew`. And `brew` uninstallation removes `wget`
3. Install `MacPorts`
4. Use it to install `gettext`
5. Soft link necessary lib from `gettext` installation folder to the place where python wants to see it
6. Use python as you wanted

You can view my WF [here](https://github.com/Sergey-Murtazin/Python-HelloWorld/runs/4642202625?check_suite_focus=true)

**Comment by Israphel** [comment] 2021-12-28 16:43
hey, that solution looks cool. I'll give it a try

**Comment by melinaurruchua** [comment] 2022-01-04 17:32
@Sergey-Murtazin Hello
we replicated your steps in the following script:

```shell
#!/usr/bin/env zsh
install_macports() {
  # Download MacPort
  wget https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-10.15-Catalina.pkg
  # Install MacPorts
  sudo installer -pkg ./MacPorts-2.7.1-10.15-Catalina.pkg -target /
}
uninstall_homebrew(){
  # Download and run the uninstall script.
  curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
  chmod +x ./uninstall.sh
  sudo ./uninstall.sh --force
}
# Install gettext using Mac MacPorts
install_gettext(){
  sudo /opt/local/bin/port install gettext
}
symbolic_link_gettext(){
  #Soft link to correct path in gettext
  mkdir -p /usr/local/opt/gettext/lib/
  ln -s /opt/local/lib/libintl.8.dylib /usr/local/opt/gettext/lib/
}
install_macports
uninstall_homebrew
install_gettext
symbolic_link_gettext
```

After that, the action setup-python worked. However, we faced a new issue when trying to use pip:
```
Run pip3 install -r requirements/common.txt
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ansible/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ansible/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ansible/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ansible/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ansible/
Could not fetch URL https://pypi.org/simple/ansible/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ansible/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement ansible==5.0.1 (from versions: none)
ERROR: No matching distribution found for ansible==5.0.1
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Error: Process completed with exit code 1.
```
maybe something else has to be reinstalled after removing homebrew?
We are going to try to install openssl via MacPorts, I will keep updating if there is any news about it

**Comment by Sergey-Murtazin** [comment] 2022-01-26 01:44
Hi

I have investigated several ways to solve the issue, but unfortunately, I have not found a workaround.  
The problem is related to how we [build Python](https://github.com/actions/python-versions/blob/63966c6b23b3aa21d1387d9d7ed4762782a0a853/builders/macos-python-builder.psm1#L49). Python depends on some libraries installed via brew, so you may face issues after removing brew.

**Comment by Israphel** [comment] 2022-01-26 14:50
ok. Meanwhile we made a secondary workflow that uninstalls homebrew and runs Ansible with the included python in macos runner. We can't cache pip dependencies, because that action depends on this one, but it works anyway.

**Comment by Sergey-Murtazin** [comment] 2022-01-31 15:01
I'm going to close this issue.  
If you have any questions, feel free to contact us.

**Closed by Sergey-Murtazin** 2022-01-31 15:01 UTC
Labels: bug
