### ISSUE TITLE
Unable to resolve actions 'actions/setup-python@v4', unable to find version 4

### ISSUE THREAD

**Issue by mukeshkdangi** [actions/setup-python#493] opened 2022-08-30 19:46 UTC
**Description:**
I am unable to setup python on windows 10 getting `Unable to resolve actions 'actions/setup-python@v4', unable to find version 4` error however when i try ctions/setup-python@main it works fine. 

Also the python setup @main is erroring out with error 

```
python 3.6 was found C:\action_runner\_work\_tool\Python..
Deleting C:\action_runner\_work\_tool\
Error: Remove Item: can't find path 'C:\action_runner\_work\_tool\Python\3.6.8\x64.complete' because it doesn't exist .... 

.....

Performing the operation "remove key" on target "Item"
HKEY_CURRENT_USER\software\Microsoft|Windows|CurrentVersion|Unistall\{}
Error At C:\action_runner\_work\_temp|...\setup.ps1 char 13
Remove Item registry::$_-Recurse _force _verbose 
+ Category Info : permission Denied: (HKEY_LOVCAL_MACH....version\Unistall::sting )[Remove -Item], SecurityExec

```

**Action version:**
actions/setup-python@v4 or actions/setup-python@v3. however actions/setup-python@main is working fine

**Platform:**
- [ ] Windows

**Runner type:**
- [ ] Self-hosted, Windows 10

**Comment by vsafonkin** [comment] 2022-08-31 07:25
Hi @mukeshkdangi, we will take a look at this, thank you for your report.

**Comment by panticmilos** [comment] 2022-09-05 16:38
Hi @mukeshkdangi,

I have created a self-hosted windows 10 runner and tried using action with both v4 and main tag and they seem to be working correctly. Could take a look at mine [workflow](https://github.com/panticmilos/setup-python/runs/8193108156?check_suite_focus=true) and see if there is anything different? 3.5 and 3.6 are with the v4 tag, and 3.7 and 3.8 are with the main tag. Also by the error, it could be that you didn't start runner with admin privileges on the self-hosted machine.

**Comment by panticmilos** [comment] 2022-09-12 12:08
hi @mukeshkdangi, just a gentle ping.

**Comment by mukeshkdangi** [comment] 2022-09-16 21:03
Hi @panticmilos issue is still there not sure what's wrong with my setup . but setup-python@main works fine.

**Comment by panticmilos** [comment] 2022-09-29 16:21
Hi @mukeshkdangi,

I will close the issue, for now. It's a weird issue, but in this case, I would say the cause of the issue is related to the self-hosted runner setup. We can continue the conversation here, or you can reopen the issue.

Cheers

**Closed by panticmilos** 2022-09-29 16:21 UTC
Labels: bug

**Comment by nicklas-demayo** [comment] 2022-10-25 15:07
We had a similar issue just recently, and it was related to self-hosted runners... in this case, we simply needed to sync the tags for actions/setup-python and then were good to go!
