### ISSUE TITLE
Python 3.10.2 not recognized on ubuntu-latest

### ISSUE THREAD

**Issue by shakefu** [actions/setup-python#562] opened 2022-12-07 19:05 UTC
**Description:**
Python 3.10.2 cannot be installed.

**Action version:**
v4

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

- 3.10.2

**Expected behavior:**
Python 3.10.2 is installed.

**Actual behavior:**
Python 3.10.2 is not installed.

It seems like it finds the version comparison fine, but fails on the exact string comparison `===` between ...
```
##[debug]x64===x64 && linux===linux
##[debug]x64===x64 && linux===linux
```
... causing it to complain it can't find "arch x64".

Relevant debug logs below:

```
##[debug]Starting: Set up job
Current runner version: '2.299.1'
Operating System
  Ubuntu
  22.04.1
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20221204.2
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20221204.2/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20221204.2
Runner Image Provisioner
  2.0.91.1
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Secret source: Actions

<!-- SNIP -->

Run actions/setup-python@v4
  with:
    python-version: 3.10.2
    check-latest: false
    token: ***
    update-environment: true
  
##[debug]Python is expected to be installed into /opt/hostedtoolcache
##[debug]Semantic version spec of 3.10.2 is 3.10.2
##[debug]isExplicit: 3.10.2
##[debug]explicit? true
##[debug]checking cache: /opt/hostedtoolcache/Python/3.10.2/x64
##[debug]not found
Version 3.10.2 was not found in the local cache
##[debug]Getting manifest from actions/python-versions@main
##[debug]set auth
##[debug]check 3.12.0-alpha.2 satisfies 3.10.2
##[debug]check 3.12.0-alpha.1 satisfies 3.10.2
##[debug]check 3.11.0 satisfies 3.10.2
##[debug]check 3.11.0-rc.2 satisfies 3.10.2
##[debug]check 3.11.0-rc.1 satisfies 3.10.2
##[debug]check 3.11.0-beta.5 satisfies 3.10.2
##[debug]check 3.11.0-beta.4 satisfies 3.10.2
##[debug]check 3.11.0-beta.3 satisfies 3.10.2
##[debug]check 3.11.0-beta.2 satisfies 3.10.2
##[debug]check 3.11.0-beta.1 satisfies 3.10.2
##[debug]check 3.11.0-alpha.7 satisfies 3.10.2
##[debug]check 3.11.0-alpha.6 satisfies 3.10.2
##[debug]check 3.11.0-alpha.5 satisfies 3.10.2
##[debug]check 3.11.0-alpha.4 satisfies 3.10.2
##[debug]check 3.11.0-alpha.3 satisfies 3.10.2
##[debug]check 3.11.0-alpha.2 satisfies 3.10.2
##[debug]check 3.11.0-alpha.1 satisfies 3.10.2
##[debug]check 3.10.9 satisfies 3.10.2
##[debug]check 3.10.8 satisfies 3.10.2
##[debug]check 3.10.7 satisfies 3.10.2
##[debug]check 3.10.6 satisfies 3.10.2
##[debug]check 3.10.5 satisfies 3.10.2
##[debug]check 3.10.4 satisfies 3.10.2
##[debug]check 3.10.3 satisfies 3.10.2
##[debug]check 3.10.2 satisfies 3.10.2
##[debug]x64===x64 && darwin===linux
##[debug]x64===x64 && linux===linux
##[debug]x64===x64 && linux===linux
##[debug]x64===x64 && win32===linux
##[debug]x86===x64 && win32===linux
##[debug]check 3.10.1 satisfies 3.10.2
##[debug]check 3.10.0 satisfies 3.10.2
##[debug]check 3.10.0-rc.2 satisfies 3.10.2
##[debug]check 3.10.0-rc.1 satisfies 3.10.2
##[debug]check 3.10.0-beta.4 satisfies 3.10.2
##[debug]check 3.10.0-beta.3 satisfies 3.10.2
##[debug]check 3.10.0-beta.2 satisfies 3.10.2
##[debug]check 3.10.0-beta.1 satisfies 3.10.2
##[debug]check 3.10.0-alpha.7 satisfies 3.10.2
##[debug]check 3.10.0-alpha.6 satisfies 3.10.2
##[debug]check 3.10.0-alpha.5 satisfies 3.10.2
##[debug]check 3.10.0-alpha.4 satisfies 3.10.2
##[debug]check 3.10.0-alpha.3 satisfies 3.10.2
##[debug]check 3.10.0-alpha.2 satisfies 3.10.2
##[debug]check 3.10.0-alpha.1 satisfies 3.10.2
##[debug]check 3.9.15 satisfies 3.10.2
##[debug]check 3.9.14 satisfies 3.10.2
##[debug]check 3.9.13 satisfies 3.10.2
##[debug]check 3.9.12 satisfies 3.10.2
##[debug]check 3.9.11 satisfies 3.10.2
##[debug]check 3.9.10 satisfies 3.10.2
##[debug]check 3.9.9 satisfies 3.10.2
##[debug]check 3.9.8 satisfies 3.10.2
##[debug]check 3.9.7 satisfies 3.10.2
##[debug]check 3.9.6 satisfies 3.10.2
##[debug]check 3.9.5 satisfies 3.10.2
##[debug]check 3.9.4 satisfies 3.10.2
##[debug]check 3.9.3 satisfies 3.10.2
##[debug]check 3.9.2 satisfies 3.10.2
##[debug]check 3.9.2-rc.1 satisfies 3.10.2
##[debug]check 3.9.1 satisfies 3.10.2
##[debug]check 3.9.1-rc.1 satisfies 3.10.2
##[debug]check 3.9.0 satisfies 3.10.2
##[debug]check 3.9.0-rc.2 satisfies 3.10.2
##[debug]check 3.9.0-rc.1 satisfies 3.10.2
##[debug]check 3.9.0-beta.5 satisfies 3.10.2
##[debug]check 3.9.0-beta.4 satisfies 3.10.2
##[debug]check 3.8.15 satisfies 3.10.2
##[debug]check 3.8.14 satisfies 3.10.2
##[debug]check 3.8.13 satisfies 3.10.2
##[debug]check 3.8.12 satisfies 3.10.2
##[debug]check 3.8.11 satisfies 3.10.2
##[debug]check 3.8.10 satisfies 3.10.2
##[debug]check 3.8.9 satisfies 3.10.2
##[debug]check 3.8.8 satisfies 3.10.2
##[debug]check 3.8.7 satisfies 3.10.2
##[debug]check 3.8.6 satisfies 3.10.2
##[debug]check 3.8.5 satisfies 3.10.2
##[debug]check 3.8.4 satisfies 3.10.2
##[debug]check 3.8.3 satisfies 3.10.2
##[debug]check 3.8.2 satisfies 3.10.2
##[debug]check 3.8.1 satisfies 3.10.2
##[debug]check 3.8.0 satisfies 3.10.2
##[debug]check 3.7.15 satisfies 3.10.2
##[debug]check 3.7.14 satisfies 3.10.2
##[debug]check 3.7.13 satisfies 3.10.2
##[debug]check 3.7.12 satisfies 3.10.2
##[debug]check 3.7.11 satisfies 3.10.2
##[debug]check 3.7.10 satisfies 3.10.2
##[debug]check 3.7.9 satisfies 3.10.2
##[debug]check 3.7.8 satisfies 3.10.2
##[debug]check 3.7.7 satisfies 3.10.2
##[debug]check 3.7.6 satisfies 3.10.2
##[debug]check 3.7.5 satisfies 3.10.2
##[debug]check 3.7.1 satisfies 3.10.2
##[debug]check 3.6.15 satisfies 3.10.2
##[debug]check 3.6.14 satisfies 3.10.2
##[debug]check 3.6.13 satisfies 3.10.2
##[debug]check 3.6.12 satisfies 3.10.2
##[debug]check 3.6.11 satisfies 3.10.2
##[debug]check 3.6.10 satisfies 3.10.2
##[debug]check 3.6.9 satisfies 3.10.2
##[debug]check 3.6.8 satisfies 3.10.2
##[debug]check 3.6.7 satisfies 3.10.2
##[debug]check 3.5.10 satisfies 3.10.2
##[debug]check 3.5.9 satisfies 3.10.2
##[debug]check 3.5.4 satisfies 3.10.2
##[debug]check 3.4.10 satisfies 3.10.2
##[debug]check 3.4.4 satisfies 3.10.2
##[debug]check 3.3.7 satisfies 3.10.2
##[debug]check 3.3.5 satisfies 3.10.2
##[debug]check 3.2.5 satisfies 3.10.2
##[debug]check 3.1.4 satisfies 3.10.2
##[debug]check 3.0.1 satisfies 3.10.2
##[debug]check 2.7.18 satisfies 3.10.2
##[debug]check 2.7.17 satisfies 3.10.2
Error: Version 3.10.2 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
##[debug]Node Action run completed with exit code 1
##[debug]Finished: run
##[debug]Evaluating condition for step: 'run'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> false
```

**Comment by dmitry-shibanov** [comment] 2022-12-07 21:33
I think it is an expected behaviour because I suppose that ubuntu-latest uses ubuntu-22.04. For ubuntu 22.04 python 3.10.2 does not exist. 

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2022-12-07 21:33 UTC
Labels: bug
