### ISSUE TITLE
Error "Version 3.12 with arch x64 not found".

### ISSUE THREAD

**Issue by wchistow** [actions/setup-python#703] opened 2023-07-20 09:14 UTC
In my file `.github/workflows/mypy.yml` I wrote:

```yml
...

jobs:
  build:

    runs-on: ubuntu-latest  # OS - Ubuntu Linux
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]  # Python version - 3.12

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    ...
```

And got an error `Version 3.12 with arch x64 not found`:

```
Run actions/setup-python@v3
  with:
    python-version: 3.12
    token: ***
Version 3.12 was not found in the local cache
Error: Version 3.12 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by dmitry-shibanov** [comment] 2023-07-20 13:11
Hello @wchistow. Thank you for your report. It is an expected behaviour because the actions tries to find the stable version but only [unstable versions](https://github.com/actions/python-versions/blob/main/versions-manifest.json#L3) are available for now. You can specify 3.12 as 3.12.0-beta.4. Besides, you can specify input: `allow-prereleases: true` and `python-version: 3.12`. You can use it like [this](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases).

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2023-07-20 13:11 UTC
Labels: bug

**Comment by pomponchik** [comment] 2023-10-26 22:35
Hello! This question has become relevant again.
