### ISSUE TITLE
Two dist-info directories for pip on macOS 11 (20230803)

### ISSUE THREAD

**Issue by ilia1243** [actions/setup-python#713] opened 2023-08-09 10:10 UTC
### Description

macOS 11 (20230803) has two dist-info directories installed for pip that causes its unexpected behavior.

See steps to reproduce and AR & ER below.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: https://github.com/actions/runner-images/releases/tag/macOS-11%2F20230803.1
Build: https://github.com/Netcracker/KubeMarine/actions/runs/5806754239

### Is it regression?

Yes, the problem does not reproduce on previous build 20230709.1

### Expected behavior

1. Only one dist-info directory `/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip-23.2.1.dist-info`
2. `pip install pip==23.0` should downgrade the pip package.

### Actual behavior

1. Two dist-info directories
    ```
    /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip-23.1.2.dist-info
    /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip-23.2.1.dist-info
    ```
2. `pip install pip==23.0` "upgrades" the pip package to `23.2.1`.

### Repro steps

Synthetic job configuration:
```
  test-pip:
    runs-on: macos-11
    steps:
      - run: |
          find /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages -name 'pip-*.dist-info'
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          pip show pip
          pip install pip==23.0
          pip show pip
```

**Comment by mikhailkoliada** [comment] 2023-08-09 10:21
@dmitry-shibanov @MaksimZhukov could you take a look? As of build logs it looks like we bring 2 different versions of pip, one with tool cached python and one with pypy

**Comment by ilia1243** [comment] 2023-08-09 12:05
Hello,
Just in case, the problem reproduces without usage of actions/setup-python
https://github.com/Netcracker/KubeMarine/actions/runs/5808735706/job/15746138810
```
jobs:
  test-pip:
    runs-on: macos-11
    steps:
      - run: |
          find /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages -name 'pip-*.dist-info'
          pip3 show pip
          pip3 install pip==23.0
          pip3 show pip
```
AR and ER are the same.

**Comment by MaksimZhukov** [comment] 2023-08-10 11:05
Hello everyone!
We will take a look at the issue and get back to you as soon as we have any updates

**Comment by dmitry-shibanov** [comment] 2023-09-15 13:18
Hello @kurtmckee. Thank you for your help. For now we're investigating it from our side. After that if it is needed we'll transfer it to runner-images.

**Comment by mikhailkoliada** [comment] 2023-09-15 13:18
This is a python-specific issue, it should not belong to the runner-images repo

**Comment by priyagupta108** [comment] 2024-10-17 07:08
Hi @ilia1243 👋,
Thank you for your report. Sorry for the late response. I think this[ pull request](https://github.com/actions/python-versions/pull/268) should resolve your issue. Could you please verify if you are still experiencing the issue? If it has been resolved, we will go ahead and close this issue. Thanks!

**Comment by ilia1243** [comment] 2024-10-17 11:51
Hi @priyagupta108, unfortunately I don't have access to the project anymore where the problem was reproducing. I think it is enough to check that all images don't two `dist` directories, like in the following way https://github.com/actions/setup-python/issues/713#issuecomment-1671201745. If you can check that, please close the issue. Thank you!

**Comment by priyagupta108** [comment] 2024-10-21 03:27
Hi @ilia1243,
I have verified that the issue is now resolved. Below is the output for reference:
<img width="736" alt="Screenshot 2024-10-21 at 8 54 45 AM" src="https://github.com/user-attachments/assets/78134764-a913-4be2-a25d-db7d9bf25449">

As the problem is fixed, I am closing this issue. Please feel free to reach out to us in case of any concerns.
Thank you!

**Closed by priyagupta108** 2024-10-21 03:27 UTC
Labels: bug
