### ISSUE TITLE
Python is not set to the right version for sudo

### ISSUE THREAD

**Issue by antoniogamizbadger** [actions/setup-python#225] opened 2021-07-07 11:26 UTC
**Describe the bug**

If you run a python command with sudo, then it takes the python2.7 version.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**

3.6

**To Reproduce**

1. Run the following action:

~~~

name: Python

on:
  push:
    branches-ignore:
      - 'staging*'
      - 'automated-tests'

jobs:
  python_utils_tests_page_0:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: pip-${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: pip-${{ env.pythonLocation }}

      - name: Packages by default
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py pip==21.0.1
          pip freeze

      - name: Install apt dependencies
        run: |
          echo "PYTHONPATH=/usr/lib/python3/dist-packages" >> $GITHUB_ENV
          sudo apt-get update
          sudo apt-get install gdal-bin
          sudo apt-get install build-essential python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
          sudo apt-get install libmapnik3.0 libmapnik-dev python3-mapnik

      - name: After installing apt dependencies
        run: |
          python -V
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          sudo python get-pip.py pip==21.0.1
          sudo pip freeze
~~~

You will get the following error:

![image](https://user-images.githubusercontent.com/73933988/124751388-dd54b700-df26-11eb-9d00-77d7e7c2ddc3.png)

**Additional context**

All this testing comes from my need to solve this problem -> https://stackoverflow.com/questions/68273934/six-module-is-not-working-correctly-even-though-i-have-locked-the-expected-versi .

**Comment by nikita-bykov** [comment] 2021-11-30 15:18
Hello @antoniogamizbadger! We apologize for such a late reply.

This is the expected behavior for running a Python command with sudo, because sudo uses its own set of directories instead of contents of $PATH environment variable.

`$PATH` without `sudo`:
```
/opt/hostedtoolcache/Python/3.6.15/x64/bin:/opt/hostedtoolcache/Python/3.6.15/x64:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
`$PATH` with `sudo`:
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```
`/opt/hostedtoolcache` folder contains the previously installed Python and it is not presents in the `$PATH` with `sudo`. Therefore, when you run a Python command with `sudo`, you cannot get Python installed by setup-python.

As a workaround we can suggest you to use the following command:
`sudo env "PATH=$PATH" python get-pip.py pip==21.0.1`

I am going to close the issue, but feel free to contact us if you have any questions.

**Closed by nikita-bykov** 2021-11-30 15:18 UTC
Labels: bug
