### ISSUE TITLE
Is it possible to build python versions with '--enable-framework' flag?

### ISSUE THREAD

**Issue by mrclary** [actions/setup-python#155] opened 2020-10-20 01:25 UTC
Well, this is not a bug; probably more a feature request...

When building standalone macOS applications with Python, (using either `py2app` or `PyInstaller`) the python version must be build with `--enable-framework`. For example, when creating a python environment on my local machine, I would use
```
$ PYTHON_CONFIGURE_OPTS=--enable-framework pyenv install <python version>
```
then proceed to build the application bundle.

**Which version of the action are you using?**
- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [x] Mac

**Python Versions**
All versions

**Comment by dmitry-shibanov** [comment] 2023-01-16 11:50
Hello @mrclary. For now I'm going to close the issue as a duplicate of [Python Framework build for macOS](https://github.com/actions/setup-python/issues/58).

**Closed by dmitry-shibanov** 2023-01-16 11:50 UTC
Labels: enhancement
