### ISSUE TITLE
PyPi setup install is broken (again)

### ISSUE THREAD

**Issue by melroy89** [actions/setup-python#620] opened 2023-03-08 21:30 UTC
**Description:**

Unable to install pypi Python using your setup action.. 

```
<html>
  <head><title>502 Bad Gateway</title></head>
  <body bgcolor="white">
  <center><h1>502 Bad Gateway</h1></center>
  <hr><center>nginx/1.14.0 (Ubuntu)</center>
  </body>
  </html>
```

**Action version:**

v4

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted

**Repro steps:**  

Just use your `actions/setup-python@v4`  with `pypy-3.9`

```
jobs:
  test:
    runs-on: ubuntu-latest
    name: Python test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: pypy-3.9
          check-latest: true
          cache: "pip"
```

**Expected behavior:**

No 502 http errors.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/628926/223854649-6222f46e-6908-44a9-b718-5d9e6ce94a8e.png)

**Comment by MaksimZhukov** [comment] 2023-03-09 12:38
Hello @melroy89 !
I have not been able to reproduce the issue with the steps you provided. Could you please provide us with the link to the public repository where the issue appears?
Please also try to specify version like this:
```yml
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
          check-latest: true
          cache: "pip"
```

**Comment by melroy89** [comment] 2023-03-09 13:29
You might didn't noticed I already link this issue to the repo where it occurs.

**Comment by melroy89** [comment] 2023-03-13 17:16
Ow they renamed the package..?

**Comment by dmitry-shibanov** [comment] 2023-04-05 11:56
Hello @melroy89. For now I'm going to close the issue because it looks that now everything works as expected.

**Closed by dmitry-shibanov** 2023-04-05 11:56 UTC
Labels: bug

**Comment by melroy89** [comment] 2023-04-05 21:00
Yea so for others who might read this in the future. They renamed `pypy3.9` to: `pypy-3.9`.
