### ISSUE TITLE
Python installation is giving error when using window based self hosted runner

### ISSUE THREAD

**Issue by jaisnow** [actions/setup-python#619] opened 2023-03-07 15:22 UTC
**Description:**
I have followed [action/setup-python](https://github.com/actions/setup-python/blob/main/.github/workflows/test-python.yml) file's python installation code in windows based self hosted runner and I am getting python installation error for the below given code

**Code**
```
name: Pylint

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on:
      - self-hosted
    steps:  
      - name: checkout repo contect
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.0
          architecture: x64
        env:
          RUNNER_TOOL_CACHE: /opt/hostedtoolcache  
      - run: |
          whoami
          ls -l /opt/hostedtoolcache
          python --versione
      
      - name: execute py script
        run:
          python test.py
```
**Error:**
![image](https://user-images.githubusercontent.com/62672781/223465353-63f017a5-8e87-49a9-8109-3558bb5f18e7.png)

Please let me know if you know how to resolve this python installation issue.
Thanks

**Comment by EvgeniyRub** [comment] 2023-04-10 16:00
Hi, I have this issue too on Windows 11, all prepared according the documentation

**Comment by dmitry-shibanov** [comment] 2023-04-11 16:20
Hello everyone. I've tried to reproduce the issue but everything works as expected.

Hello @jaisnow. Possibly you have an issue because It's impossible to change env variable through action step.

**Comment by dmitry-shibanov** [comment] 2023-04-24 22:17
Hello everyone. For now I'm going to close the issue. If you get any additional information feel free to ping us.

**Closed by dmitry-shibanov** 2023-04-24 22:17 UTC
Labels: bug
