### ISSUE TITLE
python.h missing

### ISSUE THREAD

**Issue by bmahlbrand** [actions/setup-python#221] opened 2021-07-02 17:28 UTC
**Describe the bug**
pybind/include/pybind11/detail/common.h:124:10: fatal error: Python.h: No such file or directory
  124 | #include <Python.h>

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)
3.8

**To Reproduce**
1. run setup action
2. run cmake w/something dependent on the system headers
3. :(

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**Screenshots**
![image](https://user-images.githubusercontent.com/5303952/124309817-4f00bf80-db39-11eb-8faa-16391ed244b4.png)

**Additional context**

**Comment by nikita-bykov** [comment] 2021-12-17 12:32
Hello @bmahlbrand! We apologize for such a late reply.
If the issue is still relevant, could you please describe the repro steps in more detail?

**Comment by nikita-bykov** [comment] 2021-12-23 14:12
Hello @bmahlbrand, I'm going to close the issue because we haven't received a response from you.
If the issue is still relevant, feel free to contact us.
Thank you!

**Closed by nikita-bykov** 2021-12-23 14:12 UTC
Labels: bug
