### ISSUE TITLE
Support get manifest from local

### ISSUE THREAD

**Issue by retzero** [actions/setup-python#463] opened 2022-07-15 09:34 UTC
**Description:**
We ran into a rate limit issue while running our GitHub Enterprise Server instance.
There are several topics discussed below, but they are not suitable for us.
https://github.com/actions/setup-python/pull/219, https://github.com/actions/setup-python/pull/427, https://github.com/actions/setup-python/pull/316

The rate limit problem seems to be caused by importing the manifest file located on github.com.
Wouldn't the problem go away if the action import a local manifest file instead?

I suggest using a local file instead of calling the api to github.com if the hosted runner has a specific environment variable (eg, `SETUP_PYTHON_MANIFEST_FILE_LOCATION`).

https://github.com/actions/setup-python/blob/main/src/install-python.ts#L19
```diff
+ # pseudo code
+ if (SETUP_PYTHON_MANIFEST_FILE_LOCATION is set) {
+   const manifest: tc.IToolRelease[] = getManifestFromLocal(
+   ...
+ } else {
  const manifest: tc.IToolRelease[] = await tc.getManifestFromRepo(
```

**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?**

**Comment by retzero** [comment] 2022-07-20 15:29
@IvanZosimov 

Thank you for the feedback. I'm looking for a more efficient way to solve the rate limit problem. This is our situation.

- Our company do not allow enabling GitHub Connect for some reasons.
- We have tens of thousands of build requests per day.
- And we're operating 500+ self-hosted runners.
- There is only one IP exposed to the outside due to the company's NAT configuration.
- We want to avoid including GitHub.com's PAT in our development source code.
- Currently, we're using self hosted runners w/ python tool cache set as guided [here](https://docs.github.com/en/enterprise-server@2.22/admin/github-actions/managing-access-to-actions-from-githubcom/setting-up-the-tool-cache-on-self-hosted-runners-without-internet-access#about-the-included-setup-actions-and-the-runner-tool-cache).
  - Hundreds of developers demand different python versions, so we have to caching tens of GB of full stable versions. 
  - It is expensive(time-consuming) to use ephemeral options and/or re-initialize the toolcache where changes occur in every build.

**Comment by brcrista** [comment] 2022-08-05 16:52
Duplicate of https://github.com/actions/setup-python/issues/229

**Closed by brcrista** 2022-08-05 16:52 UTC
Labels: feature request

**Comment by brcrista** [comment] 2022-08-05 16:54
> We want to avoid including GitHub.com's PAT in our development source code.

Definitely don't put it in your source code.  You would store it as a [secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets) in your repo.
