### ISSUE TITLE
Gives obscure error when /etc/lsb-release doesn't exist

### ISSUE THREAD

**Issue by ezyang** [actions/setup-python#490] opened 2022-08-24 14:54 UTC
We have self-hosted runners and we tried to use setup-python to install Python. It reported:

```
Run actions/setup-python@v4
Version 3.9 was not found in the local cache
Error: Version 3.[9](https://github.com/pytorch/torchdynamo/runs/7996970629?check_suite_focus=true#step:3:10) with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

This is weird, because clearly this version exists.

The real problem, is that the self hosted runner doesn't have /etc/lsb-release, and so all of the `platform_version` qualified versions are being disqualified. It would be good if we reported this problem accurately when it occurred.

**Comment by vsafonkin** [comment] 2022-08-24 15:40
Hi @ezyang, we will take a look at this, thank you.

**Comment by panticmilos** [comment] 2022-08-31 14:02
hi @ezyang, we are not supporting all of the Linux distros as you are probably aware, https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-setup-python-with-a-self-hosted-runner. 

I was able to reproduce this issue, and it's probably caused by some of the support libraries, but since it's not one of the officially supported distributions, we will not fix it. For that reason I will close this issue, if you have any concerns, or questions, regarding this topic please continue the conversation here or create a new issue :)

**Closed by panticmilos** 2022-08-31 14:02 UTC
Labels: bug
