### ISSUE TITLE
error on self hosted runner

### ISSUE THREAD

**Issue by weiztech** [actions/setup-python#215] opened 2021-05-23 03:01 UTC
I'm using this link as reference `https://github.com/actions/setup-python#using-setup-python-with-a-self-hosted-runner` 

the error message:
```
Execute installation script
Check if Python hostedtoolcache folder exist...
Deleting Python 3.8.5
Create Python 3.8.5 folder
Copy Python binaries to hostedtoolcache folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading PIP...
Error: ./setup.sh: line 52: ./python: cannot execute binary file: Exec format error
Error: The process '/usr/bin/bash' failed with exit code 126
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Setting Up Python version 3.8.5
```

OS: ubuntu 20.04
python-version: "3.8.5"  architecture: "x64"

**Comment by jvesely** [comment] 2021-11-02 21:22
Doesn't work on macos either:
```
Run actions/setup-python@v2.2.2
  with:
    python-version: 3.7
    architecture: x64
    token: ***
Version 3.7 was not found in the local cache
Version 3.7 is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.7.12-116024/python-3.7.12-darwin-x64.tar.gz"
Extract downloaded archive
/usr/bin/tar xz -C /Users/psyneulink/actions-runner/_work/_temp/33e27390-041b-4f3b-ab05-d9f99dc6ea25 -f /Users/psyneulink/actions-runner/_work/_temp/02f7a641-fc92-4575-9e56-cfd015f13e2c
Execute installation script
Check if Python hostedtoolcache folder exist...
Deleting Python 3.7.12
Create Python 3.7.12 folder
Copy Python binaries to hostedtoolcache folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading PIP...
Error: dyld[25949]: Library not loaded: /Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/libpython3.7m.dylib
  Referenced from: /Users/psyneulink/actions-runner/_work/_tool/Python/3.7.12/x64/bin/python3.7
  Reason: tried: '/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/libpython3.7m.dylib' (no such file), '/usr/local/lib/libpython3.7m.dylib' (no such file), '/usr/lib/libpython3.7m.dylib' (no such file)
Error: ./setup.sh: line 52: 25949 Abort trap: 6           ./python -m ensurepip
Error: The process '/bin/bash' failed with exit code 134
```

**Comment by dsame** [comment] 2022-04-26 10:18
Hello @weiztech , do you still have the problem with setup-python on self-hosted runner?

Can you please provide the exact workflow pipeline and build log? It is needed it in order to make sure the expected binary is used on the hosted platform. Thanks.

**Comment by dsame** [comment] 2022-04-27 07:48
Hello @weiztech , @jvesely[ i double checked the action and confirmed it is works as  expected](https://github.com/akv-demo/setup-python-test/runs/6189444697?check_suite_focus=true) 

I want to request @marko-zivic-93 to close the issue as the original issue seems to be resolved at the moment, please feel free to re-open the issue or create new one in case if the problem still exists in your environment

**Closed** 2022-04-27 07:51 UTC
Labels: bug

**Comment by weiztech** [comment] 2022-04-27 08:04
Hi @dsame 

I didn't have time to test it for a moment. since you have confirmed that it's working now, would you let me know the  environment(os, python, setup-python version) info that you use ? so I can check it later.


Thank you

**Comment by dsame** [comment] 2022-04-27 09:01
> Hi @dsame
> 
> I didn't have time to test it for a moment. since you have confirmed that it's working now, would you let me know the environment(os, python, setup-python version) info that you use ? so I can check it later.
> 
> Thank you

Hello @weiztech ,

I used the step

```
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
        env:
          RUNNER_TOOL_CACHE: /opt/hostedtoolcache  
```

there's a workflow yaml used to run the job https://github.com/akv-demo/setup-python-test/actions/runs/2231537802/workflow

**Comment by jvesely** [comment] 2022-04-27 16:41
> Hello @weiztech , @jvesely[ i double checked the action and confirmed it is works as expected](https://github.com/akv-demo/setup-python-test/runs/6189444697?check_suite_focus=true)
> 
> I want to request @marko-zivic-93 to close the issue as the original issue seems to be resolved at the moment, please feel free to re-open the issue or create new one in case if the problem still exists in your environment

Thanks for checking. I no longer have access to the machine that manifested this problem.
I'll reopen, open a new issue if I run into problems.
thanks again for handling this.

**Comment by marko-zivic-93** [comment] 2022-04-28 07:15
Hello @jvesely 
You are very welcome. We are here to help :)
