### ISSUE TITLE
Fail to setup python on windows

### ISSUE THREAD

**Issue by RunningLeon** [actions/setup-python#600] opened 2023-02-06 08:29 UTC
**Description:**
Hi, tried to setup python env on win10, but failed to install python on windows 10
failed line in setup.ps1
```
cmd.exe /c "cd $PythonArchPath && call $PythonExecName $ExecParams /quiet"
if ($LASTEXITCODE -ne 0) {
    Throw "Error happened during Python installation"
}
```
error message:
```
Remove registry entries for Python 3.9(x64)...
Create Python 3.9.13 folder in .\Python
Copy Python binaries to .\Python\3.9.13\x64
Install Python 3.9.13 in .\Python...
python-3.9.13-amd64.exe
DefaultAllUsersTargetDir=.\Python\3.9.13\x64 InstallAllUsers=1
Error happened during Python installation
所在位置 D:\actions-runner\_work\_temp\setup.ps1:127 字符: 5
+     Throw "Error happened during Python installation"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error happened ...on installation:String) [], RuntimeException
    + FullyQualifiedErrorId : Error happened during Python installation
```
##### You can refer to this [link ](https://github.com/open-mmlab/mmdeploy/actions/runs/4101410924/jobs/7074020036)for detailed log info
**Action version:**
Specify the action version
v4
**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x ] Windows

**Runner type:**
- [ ] Hosted
- [ x] Self-hosted

**Tools version:**

python==3.9.13
**Repro steps:**  
1. open windows powershell as admin
2. download and extract https://github.com/actions/python-versions/releases/download/3.9.13-2717571420/python-3.9.13-win32-x64.zip
3. set `ToolcacheRoot`  to a test directory in line 74 of setup.ps1
4. run .\setup.ps1
5.
**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by e-korolevskii** [comment] 2023-02-06 08:38
Hello @RunningLeon! Thank you for reporting this!
We will investigate the issue

**Comment by dmitry-shibanov** [comment] 2023-02-08 13:10
Hello @RunningLeon. Could you please try to update PowerShell or install PowerShell Core ?

**Comment by dmitry-shibanov** [comment] 2023-02-22 14:37
Hello @RunningLeon. Do you have any updates? Does the issue reproduce constantly ?

**Comment by RunningLeon** [comment] 2023-02-23 01:44
> Hello @RunningLeon. Do you have any updates? Does the issue reproduce constantly ?

Hi, still could not fix even update powershell 7.

**Comment by dmitry-shibanov** [comment] 2023-04-11 16:23
Hello @RunningLeon. I tried to reproduce the issue on self-hosted but everything works expected. It looks like an issue with your set up. For now I'm going to close the issue. If you get any additional information feel free to ping us.

**Closed by dmitry-shibanov** 2023-04-11 16:23 UTC
Labels: bug

**Comment by JannemanDev** [comment] 2023-09-15 09:15
Have the same problem. I use a Windows 11 self-hosted runner.
If I try to run `cmd.exe /c "cd C:\actions-runner\_work\_tool\Python\3.10.11\x64 && call python-3.10.11-amd64.exe /quiet"`
by myself (see line 125 in setup.ps1) it starts the installation but it required admin rights. So maybe thats the problem?

**Comment by galabovaa** [comment] 2024-01-30 19:56
I have the same problem on Windows 11 with Python 3.12. 

I tried both my Windows desktop and a Windows VM on another OS and both throw this error. 

My execution policies are unrestricted and I have updated powershell and I still can't get around it. 

Any ideas?
