### ISSUE TITLE
Inter-project dependence on self-hosted runners

### ISSUE THREAD

**Issue by damian-t** [actions/setup-python#228] opened 2021-08-06 08:31 UTC
Actually not sure if this is a bug or a feature :)

When using the same self-hosted runner(s) for various python projects (with individual GH action workflows and jobs), the Python distribution which is used by the setup-python action is the cached `/opt/hostedtoolcache/Python/3.7.9/x64`. If then packages are installed subsequently with pip, they will be installed to the `/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages`. This is problematic, as the same environment may be subsequently used by another Python project in another job causing pip resolver problems at runtime of the action.

Imo expected behaviour of `setup-python` in a job would be a "clean state" python distribution, (e.g. by using venv).

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`

**Environment**
- [x] self-hosted (Ubuntu)
- [ ] Linux
- [ ] Windows
- [ ] Mac

**Python Versions**
Python 3.7.9

**To Reproduce**
Code to reproduce: Have two python projects/repos with two GH action workflows and conflicting packages (between the two projects). In each workflow, have a job with the following steps

```
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python3.7 -m pip install --upgrade pip
          pip install -r requirements.txt
```

**Comment by dsame** [comment] 2022-06-20 20:38
@damian-t to have the python cached is the key feature to speed up the sequential builds. 

I believe we should not trade off the overall performance for sake of the specific kind of the builds which require clean up. 

Instead i suggest you to add the clean up step to your build. Due to the python installation is nothing but just a directory the clean step could be as simple as
```
      - name: Install dependencies
        run: |
          rm -rf /opt/hostedtoolcache/Python/3.7.9/x64
```
or even
```
      - name: Install dependencies
        run: |
          rm -rf /opt/hostedtoolcache/Python
```

Will it work for you? Please explain your requirements in case if i understood them wrong and we will find the solution for sure.

**Comment by dsame** [comment] 2022-06-28 06:00
Hello @damian-t, i am going to close the issue because there's provided solution. Despite it fill free to open new issue or re-open this one in case if you feel the problem is not solved.

**Closed by dsame** 2022-06-28 06:00 UTC
Labels: bug

**Comment by YatinGulati94** [comment] 2022-10-31 05:27
Hey @dsame My python script is taking too much time to execute over self-hosted runner. But when i run the same script over my local machine then its working fine.

Could u help me to resolve the issue.

Time taken over self-hosted runner: approx 3 min.
Time taken over local machin: approx 10 sec

**Comment by YatinGulati94** [comment] 2022-10-31 05:31
Version of action : v2
Self-hosted runner: ubuntu
python: 3.8.10
