### ISSUE TITLE
no such option: --root-user-action

### ISSUE THREAD

**Issue by HKongCC** [actions/setup-python#853] opened 2024-04-25 15:09 UTC
**Description:**
Unable to setup-python@v4. Fails on downloading pip packages, was working yesterday, but the same workflow fails today.

Update: Also appears that yesterday it successfully upgraded pip to 24.0 so it had the --root-user-action argument available, but today the upgrade isn't happening and stays on 22.0.4 properly so the --root-user-action argument is throwing an error.

**Action version:**
setup-python@v4

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.9.13

**Repro steps:**  
Use actions/setup-python@v4, with python version 3.9.13, and x64 architecture

**Expected behavior:**
Setup python successfully

**Actual behavior:**
Fails on pip install with the following message
`no such option: --root-user-action`

**Comment by forgingdestiny** [comment] 2024-04-25 15:59
+1 seeing similar issue on v2 and v4

**Comment by benterem** [comment] 2024-04-25 15:59
+1 same

**Comment by KodiaqQ** [comment] 2024-04-25 16:18
Try to update to Python versions older than 12h ago in actions - https://github.com/actions/python-versions/releases

**Comment by HKongCC** [comment] 2024-04-25 16:21
Good eye @KodiaqQ , looks like this is the breaking PR for those versions https://github.com/actions/python-versions/pull/259

**Comment by KodiaqQ** [comment] 2024-04-25 16:28
> Good eye @KodiaqQ , looks like this is the breaking PR for those versions [actions/python-versions#259](https://github.com/actions/python-versions/pull/259)

Yeah. We've found this PR earlier than a solution with a version switch.

**Comment by tblom** [comment] 2024-04-25 16:40
Same on v5

**Comment by forgingdestiny** [comment] 2024-04-25 16:45
Does anyone know if there will be a new release or something similar to fix? Using a different python version isn't an option for most production builds without going through an upgrade process. 🤔 thinking through alternatives here. the pinned version should prevent this fwiw.

**Comment by HKongCC** [comment] 2024-04-25 16:59
Is there a built-in argument for using a previously tagged version for python-version? This tagged version uses 3.9.13 before the breaking change. `https://github.com/actions/python-versions/tree/3.9.13-2339570595`

**Comment by Rjevski** [comment] 2024-04-25 17:02
@HKongCC had a quick look and doesn't seem like that's the case unfortunately. I temporarily switched my affected projects to use `3.9.19` version which seems unaffected. Obviously hoping that upstream will yank the broken `3.9.13` build so I can roll back my workaround.

**Comment by HarithaVattikuti** [comment] 2024-04-25 20:14
Hello @HKongCC 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by aram-eskandari** [comment] 2024-04-26 07:35
i can confirm what @Rjevski already stated: upgrading from my old version of `3.9.13` to `3.9.19` worked. Whenever this issue is resolved i will revert my project back to `3.9.13`.

**Comment by goharShoukat** [comment] 2024-04-26 11:39
Do we have an ETA on this? Moving Production builds to a newer version is not quite as straightforward!

**Comment by Rjevski** [comment] 2024-04-26 11:44
@goharShoukat you could look into using PyEnv in the meantime? A bit of manual work but should be doable if it's time-critical.

**Comment by goharShoukat** [comment] 2024-04-26 11:48
> @goharShoukat you could look into using PyEnv in the meantime? A bit of manual work but should be doable if it's time-critical.

How do you mean? PyEnv would only let me switch versions of Python but the code and other packages need to be appropriately adjusted if I switch over to a different python version.

**Comment by Rjevski** [comment] 2024-04-26 11:51
@goharShoukat I meant use PyEnv to install 3.9.13 instead of using the GH Actions' broken build. Effectively remove your "setup-python" action and just install & call pyenv like you would on any other Linux machine.

**Comment by priya-kinthali** [comment] 2024-04-26 14:54
Hello @HKongCC ,
Could you please provide a link to a minimal reproduction of the issue/workflow steps? It would be very helpful in addressing your problem. Thank you!

**Comment by sikander27** [comment] 2024-04-26 15:09
+1, facing same issue and looks like this https://github.com/actions/python-versions/commit/29394d004242dde117bb805900c99409a93b689c PR break it :(

**Comment by cognifloyd** [comment] 2024-04-26 19:21
Looks like the `--root-user-action` arg was added in https://github.com/actions/python-versions/pull/223 (https://github.com/actions/python-versions/commit/b539ede4c3ac9de14c32aab0c4fdd0278fe45ec0), and then it was removed for macos runners in https://github.com/actions/python-versions/pull/259 (https://github.com/actions/python-versions/commit/29394d004242dde117bb805900c99409a93b689c), but it is still present for the linux runners.

I'm seeing this failure on ubuntu-20.04:
```
  Version 3.8.10 was not found in the local cache
  Version 3.8.10 is available for downloading
  Download from "https://github.com/actions/python-versions/releases/download/3.8.10-8833490298/python-3.8.10-linux-20.04-x64.tar.gz"
  Extract downloaded archive
  /usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/2f150651-7ec7-4a06-b868-a38da9fd2828 -f /home/runner/work/_temp/9035f184-4c44-46b2-bda5-30215c62bd33
  Execute installation script
  Check if Python hostedtoolcache folder exist...
  Create Python 3.8.10 folder
  Copy Python binaries to hostedtoolcache folder
  Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
  Upgrading pip...
  Looking in links: /tmp/tmp1b6088ml
  Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages (56.0.0)
  Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages (21.1.1)
  Error: Usage:   
    /opt/hostedtoolcache/Python/3.8.10/x64/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
    /opt/hostedtoolcache/Python/3.8.10/x64/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
    /opt/hostedtoolcache/Python/3.8.10/x64/bin/python -m pip install [options] [-e] <vcs project url> ...
    /opt/hostedtoolcache/Python/3.8.10/x64/bin/python -m pip install [options] [-e] <local project path> ...
    /opt/hostedtoolcache/Python/3.8.10/x64/bin/python -m pip install [options] <archive url/path> ...
  
  no such option: --root-user-action
  Error: The process '/usr/bin/bash' failed with exit code 2
```

So, this build of python 3.8.10 has pip 21.1.1, but the `--root-user-action` option was added in https://github.com/pypa/pip/pull/11035 (https://github.com/pypa/pip/commit/2e1112a8141dbdf767505fded918706e9ad61031) which was only released in pip 22.1 and greater.

Where is the version of pip embedded in the python-version build defined? Either the python build needs a newer version of pip, or the linux script needs to use the env var similar to the macos fix.

**Comment by mayeut** [comment] 2024-04-26 19:33
I only expected missing macOS arm64 versions to be added when opening https://github.com/actions/python-versions/pull/259

It seems that rather than adding the missing platform, every platform was rebuilt and published...
 
> Where is the version of pip embedded in the python-version build defined?

The initial version comes from the python sources/binaries (built or fetched depending on OS/platform). It's tightly coupled to the version of python.

> Either the python build needs a newer version of pip, or the linux script needs to use the env var similar to the macos fix.

I do have a PR on the way to fix that on every platform, it will need the maintainers to approve it & rebuild everything once again.

**Comment by Keshapally** [comment] 2024-04-29 04:53
+1

**Comment by aparnajyothi-y** [comment] 2024-04-30 14:00
Hello Everyone, New artifacts have been generated. Please rerun the actions and let us know if you still see any issues.
Thank you @mayeut for your contribution with the PR.

**Comment by goharShoukat** [comment] 2024-04-30 14:26
> Hello Everyone, New artifacts have been generated. Please rerun the actions and let us know if you still see any issues. Thank you @mayeut for your contribution with the PR.

Works for me! Thanks for the quick fix!

**Comment by aparnajyothi-y** [comment] 2024-05-15 13:41
Hello @HKongCC, We are closing this issue as it is fixed and confirmed by everyone. 
Please feel free to reach us if you are still facing the same issue.

**Closed by aparnajyothi-y** 2024-05-15 13:41 UTC
Labels: bug
