### ISSUE TITLE
Error: Version X with arch x64 not found

### ISSUE THREAD

**Issue by kldavis4** [actions/setup-python#162] opened 2020-11-13 22:03 UTC
**Describe the bug**
I am attempting to use setup-python with a self-hosted runner running on an ec2 instance. I am using this ami `ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20201112`. I have followed the instructions [here](https://github.com/actions/setup-python#linux). I am getting the following output when the setup-python action is run:

```
Run actions/setup-python@v2
  with:
    python-version: 3.7.7
    token: ***
  env:
    AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
Version 3.7.7 was not found in the local cache
Version 3.7.7 is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.7.7-20200609.4/python-3.7.7-linux-18.04-x64.tar.gz"
Extract downloaded archive
/bin/tar xz --warning=no-unknown-keyword -C /actions-runner/_work/_temp/f7f341f3-b2b9-4eff-bff0-5b55acb3a0f1 -f /actions-runner/_work/_temp/402c2129-71c1-46e4-9263-3b04a4b9772a
Execute installation script
Check if Python hostedtoolcache folder exist...
Create Python 3.7.7 folder
Copy Python binaries to hostedtoolcache folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading PIP...
Looking in links: /tmp/tmpryj40n3d
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/site-packages (41.2.0)
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/site-packages (19.2.3)
Collecting pip
Using cached https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl
Installing collected packages: pip
Successfully installed pip-20.2.4
Create complete file
Error: Version 3.7.7 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

It's unclear what is actually failing as it seems to be finding the 3.7.7 python version and installs it and then it fails after installing pip.

**Which version of the action are you using?**

- [ ] `v1`
- [X] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [X] self-hosted
- [X] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)
Tried 3.7.7, 3.10.0-alpha.2

**To Reproduce**

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.
NA

**Screenshots**
<img width="1710" alt="Screen Shot 2020-11-13 at 5 00 32 PM" src="https://user-images.githubusercontent.com/370955/99125306-c47f4600-25d1-11eb-9b8d-ef4d88b16bbf.png">

**Additional context**
Here's the script that launches the runner:
```
#!/bin/bash -xe
apt-get update -y
apt-get upgrade -y
${local.apt-get-all-packages}
sudo usermod -a -G docker ubuntu
sudo systemctl start docker
sudo systemctl enable docker
export RUNNER_ALLOW_RUNASROOT=true
export AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
mkdir actions-runner
mkdir /opt/hostedtoolcache
cd actions-runner
curl -O -L https://github.com/actions/runner/releases/download/v${var.runner-version}/actions-runner-linux-x64-${var.runner-version}.tar.gz
tar xzf ./actions-runner-linux-x64-${var.runner-version}.tar.gz
./config.sh --url https://github.com/${var.owner}/${var.repository} --token ${var.github-registration-token} --name "actions-runner-$(hostname)" --unattended
sudo ./svc.sh install
sudo ./svc.sh start
```

**Comment by jolo-dev** [comment] 2020-11-22 18:48
For me the same.
I use https://github.com/nektos/act for testing Github actions locally.

I got 
```bash
[Deploy Powerlevel10k Docs/Python 3.x sample-2]   ❗  ::error::Version 3.x with arch x64 not found%0AThe list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
[Deploy Powerlevel10k Docs/Python 3.x sample-2]   ❌  Failure - Setup python
Error: exit with `FAILURE`: 1
```

and even tried the one from the README

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.x', '3.x']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python my_script.py
```

**Comment by kldavis4** [comment] 2020-12-02 21:15
Found these related issues: #89 and #92

**Comment by kldavis4** [comment] 2020-12-02 21:59
The root of this issue seems to be that the tool-cache library function for fetching the cache directory (https://github.com/actions/toolkit/blob/master/packages/tool-cache/src/tool-cache.ts#L693) is using `RUNNER_TOOL_CACHE` but this is set to `/actions-runner/_work/_tool` instead of `/opt/hostedtoolcache`. Setting `RUNNER_TOOL_CACHE` (within the self-hosted runner or the actions yml) seems to have no effect and I haven't been able to determine yet how the default is getting set.

**Comment by kldavis4** [comment] 2020-12-03 19:08
I was able to figure out a workaround that seems ok. Not fully tested yet for possible side effects.

If I modify the setup script to create a symlink from `/opt/hostedtoolcache` to the directory it expects for `RUNNER_TOOL_CACHE`, everything installs correctly. So my modified script is now:

```
#!/bin/bash -xe
apt-get update -y
apt-get upgrade -y
${local.apt-get-all-packages}
sudo usermod -a -G docker ubuntu
sudo systemctl start docker
sudo systemctl enable docker
export RUNNER_ALLOW_RUNASROOT=true
export AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
mkdir actions-runner
mkdir /opt/hostedtoolcache
cd actions-runner

# Make /actions-runner/_work
mkdir _work

# Link /opt/hostedtoolcache as /actions-runner/_work/_tool
ln -s /opt/hostedtoolcache _work/_tool

curl -O -L https://github.com/actions/runner/releases/download/v${var.runner-version}/actions-runner-linux-x64-${var.runner-version}.tar.gz
tar xzf ./actions-runner-linux-x64-${var.runner-version}.tar.gz
./config.sh --url https://github.com/${var.owner}/${var.repository} --token ${var.github-registration-token} --name "actions-runner-$(hostname)" --unattended
sudo ./svc.sh install
sudo ./svc.sh start
```

**Comment by meiswjn** [comment] 2020-12-21 10:10
Unrelated to the problem of the author, but I initially thought I had the same problem:
I used debian instead of ubuntu, thus it did not work. 

Mabye helpful for other stumbling over this

**Comment by higebu** [comment] 2020-12-23 09:23
@meiswjn You can use Debian with creating `/etc/lsb-release` like Ubuntu. If you use Debian 10, `/etc/lsb-release` should be same as Ubuntu 18.04 like this.

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

**Comment by Segfaultd** [comment] 2021-02-11 09:54
Any chance this issue get attention?

**Comment by Segfaultd** [comment] 2021-03-30 15:34
Still not dead, and still wanting this issue to get attention. Someone alive?

**Comment by thetaiter** [comment] 2021-04-16 16:30
poke

**Comment by IdoPort** [comment] 2021-04-19 08:59
another poke in the wall...

**Comment by cep21** [comment] 2021-05-03 00:00
@kldavis4 How did your workaround end up long term?  Still working well?

**Comment by janjur** [comment] 2021-05-22 14:47
...PPoke

**Comment by epwalsh** [comment] 2021-06-12 21:52
+1

**Comment by codecholeric** [comment] 2021-06-17 11:07
+1

**Comment by adhikariravi** [comment] 2021-06-21 13:06
+1

**Comment by nitrocode** [comment] 2021-06-21 21:20
@kldavis4 I tried your workaround but still no luck.

action
```yaml
      # pre-commit setup
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
          RUNNER_TOOL_CACHE: /opt/hostedtoolcache
```

userdata
```shell
export RUNNER_TOOL_CACHE=/opt/hostedtoolcache
export AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
mkdir -p $AGENT_TOOLSDIRECTORY
mkdir -p /actions-runner/_work
ln -s $AGENT_TOOLSDIRECTORY /actions-runner/_work/_tool
curl -s https://raw.githubusercontent.com/actions/runner/v2.278.0/scripts/create-latest-svc.sh | bash -s org
```

check
```shell
# ls -la /actions-runner/_work/
total 0
drwxr-xr-x 2 root root 19 Jun 21 20:45 .
drwxr-xr-x 3 root root 19 Jun 21 20:45 ..
lrwxrwxrwx 1 root root 20 Jun 21 20:45 _tool -> /opt/hostedtoolcache
```

**Comment by kldavis4** [comment] 2021-06-21 21:55
> @kldavis4 How did your workaround end up long term? Still working well?

@cep21 yes. we still have the workaround in place and haven't run into any issues so far

**Comment by kldavis4** [comment] 2021-06-21 22:08
@nitrocode couple things to check out...

1) I am not specifying any environment variables (AGENT_TOOLSDIRECTORY & RUNNER_TOOL_CACHE). I don't think that should cause a problem but it is different than our current workflows.
2) I'm not totally sure on what directory the userdata runs in. My userdata creates the actions-runner folder in the "current" directory and I'm not confident that it will be the filesystem root directory and not the root user's home
3) what version of ubuntu is your AMI? I'm using `ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64*`

**Comment by nitrocode** [comment] 2021-06-21 22:33
@kldavis4 I'm using Amazon Linux 2 AMI. That's probably the issue. The `platform_version` seems in the manifest seems to be exclusive to Ubuntu with no way to override it.

**Comment by juanjgarcia** [comment] 2021-06-28 18:15
I've been down the rabbit hole and I can't find an elegant solution. It looks like the best bet is to add support here: https://github.com/actions/python-versions/ and then have those new files added to the manifest?

Either way, this is blocking us, and I think its a pretty common situation given the prowess of AWS.

**Comment by neilferreira** [comment] 2021-07-13 05:54
@nitrocode @kldavis4 Do either of you have a solution for Amazon Linux 2 yet?

**Comment by bumbummen99** [comment] 2021-07-13 11:50
On my AWS Linux 2 runner i settled with just installing python myself in a setup script, does work well enough.

**Comment by Baekalfen** [comment] 2021-07-20 21:51
Just for reference, I'm seeing this issues on self-hosted macOS as well.

**Comment by nitrocode** [comment] 2021-07-20 22:58
@bumbummen99 could you share that ? I'd be interested in using that in the interim if it's easy enough to choose a specific python version to install.

**Comment by Baekalfen** [comment] 2021-07-22 13:48
I went down the rabbit hole as well, and like @kldavis4 points out, I link the problem might be related to `_getCacheDirectory`.

And the same workaround "solves" the issue on macOS. Although I haven't thoroughly tested, if it causes any issues down the road.

```sh
rm -rf actions-runner/_work/_tool && ln -s /Users/runner/hostedtoolcache actions-runner/_work/_tool
```

Defining `RUNNER_TOOL_CACHE` didn't affect the process.

**Comment by bumbummen99** [comment] 2021-07-22 16:20
> 
> 
> @bumbummen99 could you share that ? I'd be interested in using that in the interim if it's easy enough to choose a specific python version to install.

It is pretty much using a cannon for a bird. You will have to install python to the OS on which you run the runner (what totally defies the purpose of this package: dynamically using any version).

Should be something like `yum add pythonX.X`

I am using [philips-labs/terraform-aws-github-runner](https://github.com/philips-labs/terraform-aws-github-runner) so i use the following terraform variable to apply it:
https://github.com/philips-labs/terraform-aws-github-runner/blob/68635ddb9e1828d50a5e62ce6c8c5da589d501cd/variables.tf#L170

**Comment by smacke** [comment] 2021-08-14 23:34
> For me the same.
> I use https://github.com/nektos/act for testing Github actions locally.
> 
> I got
> 
> ```shell
> [Deploy Powerlevel10k Docs/Python 3.x sample-2]   ❗  ::error::Version 3.x with arch x64 not found%0AThe list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
> [Deploy Powerlevel10k Docs/Python 3.x sample-2]   ❌  Failure - Setup python
> Error: exit with `FAILURE`: 1
> ```
> 
> and even tried the one from the README
> 
> ```yaml
> jobs:
>   build:
>     runs-on: ubuntu-latest
>     strategy:
>       matrix:
>         python-version: ['2.x', '3.x']
>     name: Python ${{ matrix.python-version }} sample
>     steps:
>       - uses: actions/checkout@v2
>       - name: Setup python
>         uses: actions/setup-python@v2
>         with:
>           python-version: ${{ matrix.python-version }}
>           architecture: x64
>       - run: python my_script.py
> ```

For this, there is a workaround described in an issue filed against act: https://github.com/nektos/act/issues/251

**Comment by c0m** [comment] 2021-09-18 19:49
I'm also running in to this situation with Linode, not exclusive to AWS deployments. Ubuntu 21.04 and 20.10 don't behave, using 20.04 LTS does seem to resolve it.

**Comment by paulo-coutinho** [comment] 2022-01-04 22:23
I get the same error today:

```
Run actions/setup-python@v1
  with:
    python-version: 3.6
    architecture: x64
Error: Version 3.6 with arch x64 not found
Available versions:

3.10.0 (x64)
3.7.12 (x64)
3.8.12 (x64)
3.9.9 (x64)
```

On macOS-latest.

**Comment by vbersier** [comment] 2022-01-27 06:47
Hit the same error today using the docker image provided by https://github.com/tcardonne/docker-github-runner

If I `echo $RUNNER_TOOL_CACHE` in my action, I get the expected output `/opt/hostedtoolcache` so the workaround described by @kldavis4 would not help.

The root cause might be different this time.

**Comment by Displee** [comment] 2022-01-31 12:16
> 

How would I go about doing this? I tried installing Python on the OS and set the config like this:
```
npm config set python /usr/bin/python
```
However, this did not work.

**Comment by babus** [comment] 2022-02-01 07:56
> 

Tried changing the `actions/setup-python@v1` to `actions/setup-python@v2`? I just did and it worked for me somehow. In my case it was 3.9.9 arch 64 missing.

**Comment by edreamleo** [comment] 2022-02-16 12:53
[Leo](https://github.com/leo-editor/leo-editor/branches) appears to be having the same issue (on all branches) on Windows 11. The problem appeared yesterday without any changes to the TravisCI setup. Indeed, it appears on the master branch, which hasn't changed in weeks.

**Comment by dsame** [comment] 2022-05-05 15:29
hello @tkrawczykspoton  

According to last comment https://github.com/actions/setup-python/pull/338 and it seems it was merged 20 days ago.

Let me double check if the build have the issue solved with the PR.
Can you please give us a recent build logs in order to see "Python is expected to be installed into" info message?

**Comment by chadbrewbaker** [comment] 2022-05-09 23:07
Just ran into this today. The nodejs action works out of the box on AmazonLinux2 self hosted runners because it pulls upstream from node. Given GitHub Enterprise is $$$, Microsoft should at minimum support AmazonLinux2 and soon AmazonLinux2022.

**Comment by chadbrewbaker** [comment] 2022-05-09 23:15
@[karthiknadig](https://github.com/karthiknadig) why isn't the GitHub Action team using your Python toolchain binaries? Works like butter on RHEL7 so it should be fine for AWSLinux2.

**Comment by gl72** [comment] 2022-06-02 11:15
Hi there, I am having the same issues on a self-hosted runner on RHEL8.5 instance. I tried already all the workarounds without any luck. I tried with both v2 and v3. I am having no issues on ubuntu runners.
Did anyone try this action on RHEL?

**Comment by dsame** [comment] 2022-06-13 07:29
Hello @chadbrewbaker @gl72 , according to this https://github.com/actions/setup-python/issues/401#issuecomment-1150563156 the only supported distro is Ubuntu. 

Because of took cache Python versions are built against the Ubuntu libraries there's no robust way to choose the version specific to non-Ubuntu distros.

Workarounds: either use python from the distro or switch to Ubuntu for self-hosted agent. Any virtualisation should work.

**Comment by msudgh** [comment] 2022-06-19 18:59
Hi, Any workaround for macOS?

**Comment by dsame** [comment] 2022-06-21 07:45
> Hi, Any workaround for macOS?

MacOS has its tool-cache pre-built pythons and should work out of box. If it does not please check if you use @v3 of setup-python

**Comment by dsame** [comment] 2022-06-27 08:37
Hello @kldavis4  i am going to close this issue because it seems to be resolved and there's no other comments so far. Feel free to open new issue or reopen this one in case of any problem

**Closed by dsame** 2022-06-27 08:37 UTC
Labels: bug

**Comment by Yohlo** [comment] 2022-07-08 21:11
Sorry to reopen but this is happening to me now with `setup-python@v4`. Tried a matrix with all python version >3.9 and they all had the same error. The manifest of python versions also shows the target versions with the same arch but is returning an error. Have tried the workarounds in this issue with no luck :/

self-hosted linux x64

Here's a screenshot:
![image](https://user-images.githubusercontent.com/12708152/178070797-764ac307-194d-4a23-a063-3110ceea8922.png)

**Comment by IvanZosimov** [comment] 2022-07-11 08:27
> Sorry to reopen but this is happening to me now with `setup-python@v4`. Tried a matrix with all python version >3.9 and they all had the same error. The manifest of python versions also shows the target versions with the same arch but is returning an error. Have tried the workarounds in this issue with no luck :/
> 
> self-hosted linux x64
> 
> Here's a screenshot: ![image](https://user-images.githubusercontent.com/12708152/178070797-764ac307-194d-4a23-a063-3110ceea8922.png)

Hi, @Yohlo 👋 ! I tried to reproduce your issue but on my self-hosted Linux runner everything works as expected. May I ask you to create new issue with a broader explanation of your case?

**Comment by tiansu-yu-idealo** [comment] 2022-09-06 19:30
This issue does not seem to be resolved with local testing with [act](https://github.com/nektos/act) running on a MacOS M1 chip machine. 
The actions is set as follows:
```
      - name: Set up Python3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
          architecture: x64
          platform: linux
```
The command to reproduce the issue is 
```
 act --container-architecture linux/arm64
```

**Comment by Vazno** [comment] 2022-11-12 16:35
I am having the same error on ubuntu



**Description:**
I used workflow to auto test code, it was working fine 10 days ago, and now I am having this error:
```
Error: Version 3.10.0 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Action version:**
2-4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

'3.6', '3.7', '3.8', '3.9', '3.10.0'
**Repro steps:**
```
name: Run tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10.0']

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2
        # Setup which version of Python to use
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

        with:
          python-version: ${{ matrix.python-version }}
        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        # Install the package using the setup.py
      - name: Install package
        run: python setup.py install
        # Install pytest (you can use some other testing utility)
      - name: Install pytest, and requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
        # Run the tests. I'm using pytest and the file is in the tests directory.
      - name: Run tests
        run: pytest tests/test*
```
I changed `runs-on: ubuntu-latest` to `runs-on: macos-latest` and it started working.

**Comment by DanielGoldfarb** [comment] 2022-11-22 17:12
Same thing started happening to me.  I have a ***very similar*** workflow structure as show in the above https://github.com/actions/setup-python/issues/162#issuecomment-1312522561 .   

Last time I ran it (22 days ago) it ran fine (and every time before that).  

Ran it today with the same issue:
```
Run actions/setup-python@v2
Version 3.[6](https://github.com/matplotlib/mplfinance/actions/runs/3525419434/jobs/5912308394#step:5:7) was not found in the local cache
Error: Version 3.6 with arch x64 not found
```

What should I do?   I thought this was fixed with #338 
Should this Issue be re-opened?

**Comment by DanielGoldfarb** [comment] 2022-11-22 17:39
I'm not sure why this is closed.  Indeed (based on the last few comments) it does not appear to be fixed.

As per https://github.com/actions/setup-python/issues/541#issuecomment-1314296872 it appears that (at least for me) the following workaround works: 
- set runner image version to `ubuntu-20.04` instead of `ubuntu-latest`.  

However it seems to me that to be considered "fixed" it should work with `ubuntu-latest` as well.

Am I missing something?

@dsame 
Please re-open, or please explain why this is considered resolved?  Maybe I am missing something?  Thank you.

**Comment by antoniodesenvolvedor** [comment] 2022-11-22 20:00
Same thing happening here 

Version 3.6.10 was not found in the local cache
Error: Version 3.[6](https://github.com/gamehive/TapTitans2Server/actions/runs/3526418460/jobs/5914385283#step:7:7).10 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Comment by b0nce** [comment] 2022-11-23 14:31
Same here. Python 3.8.0, Ubuntu 18.04 x64
![image](https://user-images.githubusercontent.com/27873390/203571392-08e21011-d6d3-49b1-914f-4729c430f171.png)
![image](https://user-images.githubusercontent.com/27873390/203571842-963bf463-e370-48f7-a52b-d94cba23bbed.png)

**Comment by pablo-de** [comment] 2022-11-23 15:11
Same problem since today

![image](https://user-images.githubusercontent.com/94941513/203581193-8c723538-fd62-40a5-b16d-440f11d2992d.png)

**Comment by codingdash** [comment] 2022-11-23 16:03
Looks like the latest ubuntu version has some issue, sticking to 20.04 resolved this issue.

From:
```
runs-on: ubuntu-latest
```

To:
```
runs-on: ubuntu-20.04
```

**Comment by PavanMudigondaTR** [comment] 2022-11-23 17:39
same issue here

**Comment by tbrlpld** [comment] 2022-11-23 18:03
Same too

**Comment by abarragan-adtriba** [comment] 2022-12-09 10:18
Thanks for https://github.com/actions/setup-python/issues/162#issuecomment-1325307787 comment for giving a good hint and solution.

To put more certainty to the problem, my issue was with Python 3.8.10, if you check on the list of available versions (https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) you will see that for 3.8.10 the newest version available for ubuntu is 20.04. We have some workflows that use Python 3.11 and those dont fail, that's because there's a 22.04 ubuntu version for that python version.

**Comment by vincerubinetti** [comment] 2023-01-06 16:53
In my case I was doing something stupid. Maybe this will help someone.

```
- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: 3.10
```

`3.10` is just a number and gets interpreted as version `3.1`. Changed it to `"3.10"` and it worked (with `ubuntu-latest`).

**Comment by PavanMudigondaTR** [comment] 2023-01-06 17:48
> In my case I was doing something stupid. Maybe this will help someone.
> 
> ```
> - name: Set up Python
>   uses: actions/setup-python@v4
>   with:
>     python-version: 3.10
> ```
> 
> `3.10` is just a number in yaml and gets interpreted as version `3.1`. Changed it to `"3.10"` and it worked (with `ubuntu-latest`).

good catch !

**Comment by LucaMarconato** [comment] 2023-01-20 12:06
Same problem here since last week, I get
```
 ::error::The version '3.9' with architecture 'arm64' was not found for Ubuntu 22.04.%0AThe list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by abarragan-adtriba** [comment] 2023-01-20 12:12
@fan9704 which platform and version are you using?
@LucaMarconato there's no 3.9 version to choose from

**Comment by LucaMarconato** [comment] 2023-01-20 14:55
@abarragan-adtriba true, I have changed it to "3.9.16" and the problem persists:

```
[Test/test-2        ]   ❗  ::error::Version 3.10.9 with arch arm64 not found%0AThe list of all available versions can be found 
here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
[Test/test-2        ]   ❌  Failure - Main Set up Python 3.10.9
[Test/test-2        ] exitcode '1': failure
[Test/test-2        ] 🏁  Job failed
```
I checked the [link above](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) and I can't find any reference to `arm64`.

**Comment by abarragan-adtriba** [comment] 2023-01-20 15:16
@LucaMarconato how is this a problem if there's no arch arm64 available at all? you are just querying for a non-existing arch, or maybe im missing smth

**Comment by abarragan-adtriba** [comment] 2023-01-23 11:49
> @abarragan-adtriba ubuntu-latest on GitHub Action

@fan9704 , you should have read the thread, in particular: https://github.com/actions/setup-python/issues/162#issuecomment-1344117224

**Comment by fan9704** [comment] 2023-01-23 12:00
Got it thanks your reply

**Comment by LucaMarconato** [comment] 2023-01-23 13:38
@abarragan-adtriba ok I understand. So this seems like a limitation of `act`, I will report there. With `act` one is supposed to be able to obtain a docker image of the same OS that is used in Github for running the actions. From your message I understand that the Apple Silicon chips are not supported.

**Comment by 0x78f1935** [comment] 2023-02-14 11:19
Our Github actions runner is hosted in a contained docker container.
I had the same issues when using the option
```
runs-on: [self-hosted]
```
Changing this too
```
runs-on: ubuntu-latest
```
did the trick for me.

**Comment by abarragan-adtriba** [comment] 2023-02-14 11:23
@0x78f1935 ubuntu-latest is a bad practice as you could have read on the thread, this was the reason people (myself included) got into this problem because that's a dynamic tag.

**Comment by 0x78f1935** [comment] 2023-02-14 11:56
> `ubuntu-latest` is a bad practice as you could have read on the thread,
Didn't see someone mentioning it was bad practice. Perhaps I read past it, but at the end of the day I can see why. Thanks for mentioning this!

In addition the [comment]((https://github.com/actions/setup-python/issues/162#issuecomment-1344117224)) made by [abarragan-adtriba](https://github.com/abarragan-adtriba) was very helpful.

In my case, wanting Python 3.11.1, I should use `ubuntu-22.04` instead.
Again, thanks for pointing this out!

**Comment by Alotab** [comment] 2023-02-17 01:40
> In my case I was doing something stupid. Maybe this will help someone.
> 
> ```
> - name: Set up Python
>   uses: actions/setup-python@v4
>   with:
>     python-version: 3.10
> ```
> 
> `3.10` is just a number in yaml and gets interpreted as version `3.1`. Changed it to `"3.10"` and it worked (with `ubuntu-latest`).

This was the missing piece. It's working now.

**Comment by hiperioncn** [comment] 2025-01-13 06:18
```
jobs:
  schedule_jobs:
    name: Schedule Jobs
    runs-on: ubuntu-latest
```
改为
```
jobs:
  schedule_jobs:
    name: Schedule Jobs
    runs-on: ubuntu-22.04
```
"ubuntu-latest" is not a good configuration method because this version is variable. When a new version comes out, it may cause other incompatibility issues.
