### ISSUE TITLE
In running setup.py, f2py cannot find fortran compiler, only in macos env

### ISSUE THREAD

**Issue by jaclark5** [actions/setup-python#192] opened 2021-03-03 14:08 UTC
**Describe the bug**
I'm not sure if this issue is appropriate here, or if it should be a numpy issue. Since this is the interface between GitHub Actions and python, I expect it fits here. Apologies if not!

When installing a python package with Fortran modules, f2py cannot locate a compiler (only in macos). However, many compilers are available and when attempting to install gfortran with brew, but it halts because it already exists. The compilers available under /usr/bin/ are named with their version number (e.g. gfortran-10), when f2py is looking for an accepts 'gfortran'. 

A solution could be to use a symbolic link, but I don't have permissions. We identified a workaround where installing gfortran with anaconda resolves the problem. Resolving this issue will streamline future use of GitHub Actions with Fortran supplemented Fortran modules.

**Which version of the action are you using?**
- [ ] `v1`
- [X] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [X] Mac

**Python Versions**
Tested for python 3.7 and 3.8

**To Reproduce**
1. Go to Actions of project link listed below.
2. Click on the job: 'Test on macos-latest, Python 3.7'
3. Scroll down to 'Install package'
4. See line 36, no Fortran compiler found
5. Compare to the previous job: 'mac'
6. Click "Run brew install gfortran"
7. See: " Warning: gcc 10.2.0_4 is already installed and up-to-date.
               To reinstall 10.2.0_4, run:
                brew reinstall gcc"

**Run/Repo Url**
https://github.com/jaclark5/despasito/actions/runs/615672042

**Comment by dlilien** [comment] 2021-07-07 14:24
This is probably long irrelevant, but in case anybody else has this issue and runs across this like me...
Actions uses passwordless sudo, which allows you to make a symlink. All I had to do was

`sudo ln -s /usr/local/bin/gfortran-9 /usr/local/bin/gfortran`

**Comment by nikita-bykov** [comment] 2021-12-30 14:34
Hello @jaclark5! We apologize for such a late reply.
You can create symbolic links as @dlilien mentioned earlier.
I was unable to reproduce the issue in your repository. If the issue is still relevant to you, could you please update the steps to reproduce so that we can investigate further?

**Comment by nikita-bykov** [comment] 2022-01-12 09:23
Hello @jaclark5!
Do you have any updates?

**Comment by nikita-bykov** [comment] 2022-01-17 12:20
@jaclark5, unfortunately, we did not receive a response from you, so I'm going to close the issue. Feel free to contact us if you have any questions.

**Closed by nikita-bykov** 2022-01-17 12:20 UTC
Labels: bug
