### ISSUE TITLE
Installing pypy3 failed with "Error: IS_WINDOWS is not defined"

### ISSUE THREAD

**Issue by alex** [actions/setup-python#171] opened 2020-12-17 16:57 UTC
**Describe the bug**

https://github.com/pyca/cryptography/pull/5652/checks?check_run_id=1571744687

```yaml
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.PYTHON.VERSION }}
```

-> 

```
Error: IS_WINDOWS is not defined
```

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**

`pypy3`

**Run/Repo Url**
https://github.com/pyca/cryptography/pull/5652/checks?check_run_id=1571744687

**Comment by alex** [comment] 2020-12-17 16:58
Since this just started happening, I'm guessing it's a regression in the 2.2.0 release.

**Comment by alex** [comment] 2020-12-17 17:00
It also looks like this project's own CI is impacted by this: https://github.com/actions/setup-python/runs/1571081954?check_suite_focus=true

**Comment by jamadden** [comment] 2020-12-17 17:15
Same error [for PyPy2](https://github.com/gevent/gevent/runs/1571842535?check_suite_focus=true#step:5:1).

**Comment by slebon** [comment] 2020-12-17 17:43
Same error on my projects.

**Comment by TimPansino** [comment] 2020-12-17 18:01
Same error here, only on pypy2 and pypy3. Other python versions are unaffected.

**Comment by mrmundt** [comment] 2020-12-17 20:02
Same here for pypy2 and pypy3.

**Comment by maxim-lobanov** [comment] 2020-12-18 07:21
Hello everyone!
Yes, it looks like regression related to 2.2.0 release.
Pull-request with fix https://github.com/actions/setup-python/pull/172 will be merged soon.

As a workaround, I suggest using new syntax for PyPy:
```
pypy-2.7
pypy-3.6
pypy-3.7
pypy-3.7-v7.3.3
```
See more examples in https://github.com/actions/setup-python#specifying-a-pypy-version

2.2.0 release was directed to add support for new PyPy syntax to allow installing PyPy on-flight and specifying exact version. But looks like we got regression in old syntax: https://github.com/actions/setup-python/pull/169

**Comment by konradpabjan** [comment] 2020-12-18 14:30
The new `v2.2.1` release has the correct fixes and the `v2` tag has been updated

There was a small merge conflict between multiple PRs related to webpack and `dist/index.js` that our tests didn't catch 😞 Sorry folks

**Closed by konradpabjan** 2020-12-18 14:30 UTC
Labels: bug

**Comment by leycec** [comment] 2020-12-19 01:25
Thanks for the rapid turnaround, everyone. You rock... as always.
