### ISSUE TITLE
Python version output showing as *** & Cache-latest not working

### ISSUE THREAD

**Issue by AsifNawaz-cnic** [actions/setup-python#473] opened 2022-07-27 09:05 UTC
Hi,

Action version:
v4

Platform:
 Ubuntu
Runner type:
 Hosted
Tools version:
All Python versions.

1) I am fetching python version from github secrets in our github workflows and I am not able to see the version on workflow log as it is showing as "***". 
I have personally come up with a solution "Adding a hidden character between all or any single character on python version string will show the version" 
Hidden Character Uncode : [U+200E] 
In this below command hidden character is implemented after & character.
```
echo ${{ secrets.PYTHON_MIN_VERSION }} | sed 's/./&‎/g'
```

Output:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/107853964/181207137-3cd790ce-f014-4c7a-af93-10a10829b697.png">

Kindly implement similar solution to show python version so it should work with the users who are fetching python version from github secrets, thanks.

2) I am not able to use cache-latest: true on our workflows as it is throwing these errors:  
Unexpected input(s) 'check-latest', valid inputs are ['python-version', 'python-version-file', 'cache', 'architecture', 'token', 'cache-dependency-path', 'update-environment']
 
[Link to github workflow logs](https://github.com/hexonet/ispapicli/runs/7536862175?check_suite_focus=true)

**Comment by dmitry-shibanov** [comment] 2022-07-27 09:35
Hello @AsifNawaz-cnic. Thank you for your report. It's an expected behaviour because a new version was not released and the major tag was not updated.

**Comment by IvanZosimov** [comment] 2022-07-27 10:26
Hi, @AsifNawaz-cnic 👋 I'd like to add here that probably it's better to keep the python version in some version file because secrets usually are used for some secret information that shouldn't appear in the logs. By doing this you will solve all problems at once.

**Comment by AsifNawaz-cnic** [comment] 2022-07-27 11:13
> Hi, @AsifNawaz-cnic 👋 I'd like to add here that probably it's better to keep the python version in some version file because secrets usually are used for some secret information that shouldn't appear in the logs. By doing this you will solve all problems at once.

Thanks for your feedback, I really like your idea but maintaining python-version in a file when dealing with multiple repositories is really complicated and time consuming, so that is why we are using github secrets approach to get the python-version.

**Comment by IvanZosimov** [comment] 2022-08-03 08:31
Hi, @AsifNawaz-cnic 👋 The [new](https://github.com/actions/setup-python/releases/tag/v4.2.0) version of setup-python was released. Now you can use the `check-latest` feature. By now I'm going to close this issue, If you have any additional questions, feel free to ping us.

**Closed by IvanZosimov** 2022-08-03 08:31 UTC
Labels: bug
