### ISSUE TITLE
Python Version 2.7 with arch x64 not found

### ISSUE THREAD

**Issue by albertz** [actions/setup-python#543] opened 2022-11-18 11:00 UTC
**Description:**
I get the error:
```
Run actions/setup-python@v2
  with:
    python-version: 2.7
    token: ***
Version 2.7 was not found in the local cache
Error: Version 2.7 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
I get this for the first time now, and have not changed any code. It has worked since a long time before.

**Action version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Python 2.7

**Repro steps:**  
In my GitHub workflows file, I have:
```
    - uses: actions/setup-python@v2
      with:
        python-version: 2.7
```

**Expected behavior:**
It should work, just like it has in the last year.

**Actual behavior:**
The error above.

**Comment by albertz** [comment] 2022-11-18 11:05
I noticed, similarly I also get:
```
Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found
```

**Comment by albertz** [comment] 2022-11-18 11:06
With Python 3.7, it seems to be fine.

**Comment by albertz** [comment] 2022-11-18 11:08
This is with Ubuntu 22.04 in GitHub Actions.

**Comment by dmitry-shibanov** [comment] 2022-11-18 11:12
Hello @albertz. I think it's an expected behaviour because the action does not provide [python 2.7 for Ubuntu 22.04](https://github.com/actions/python-versions/blob/main/versions-manifest.json#L4279). You can try to specify a previous version of Ubuntu to set up python 2.7.

**Comment by albertz** [comment] 2022-11-18 11:17
Ah, has that changed? We use `runs-on: ubuntu-latest` in GitHub.

**Comment by albertz** [comment] 2022-11-18 11:18
According to https://github.com/actions/runner-images, ubuntu-latest should be Ubuntu 20.04? So why do we get Ubuntu 22.04?

**Comment by dmitry-shibanov** [comment] 2022-11-18 11:19
> Ah, has that changed? We use `runs-on: ubuntu-latest` in GitHub.

Ubuntu latest tag is changing from ubuntu-20.04 to ubuntu-22.04: https://github.com/actions/runner-images/issues/6399

**Comment by albertz** [comment] 2022-11-18 11:20
I see.

Is there any plan to include Python 2.7 and Python 3.6 also for Ubuntu 22.04?

**Comment by dmitry-shibanov** [comment] 2022-11-18 11:21
For now we do not have any plans to include it.

**Comment by albertz** [comment] 2022-11-18 11:25
You can see this issue as a feature request then. :)
Because ideally I would like to run all my other tests on ubuntu-latest, and I have some Python 2.7 and 3.6 tests in there.

**Comment by jvanasco** [comment] 2022-12-01 16:03
@dmitry-shibanov do you know if it is possible to configure a single action file to run python2.7 on ubuntu 20.4, and everything else on ubuntu-latest?  i haven't found any docs/examples to support that, and it would be preferable than running two separate workflow actions.

**Comment by wimglenn** [comment] 2022-12-02 07:21
Workarounds - I changed:

```
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
```

into

```
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - macos-latest
        - windows-latest
```

**Comment by AdamWill** [comment] 2022-12-02 17:59
For other folks running into this, one of the contributors to my project found a pretty elegant way to deal with it using `matrix-os`, see https://github.com/os-autoinst/openQA-python-client/pull/40 :

    jobs:
      build:
        runs-on: ${{ matrix.os }}
        strategy:
          max-parallel: 4
          fail-fast: false
          matrix:
            python-version:
              - "3.6"
              - "3.7"
              - "3.8"
              - "3.9"
              - "3.10"
              - "3.11"
              - "3.12.0-alpha - 3.12.0"
            include:
              - os: "ubuntu-latest"
              - os: "ubuntu-20.04"
                python-version: "3.6"

nice job @kalikiana !

**Comment by rouilj** [comment] 2022-12-05 05:02
I have the same requirements for testing under 2.7 and 3.6.
 It would be useful to keep these around until debian 12 drops.

**Comment by dmitry-shibanov** [comment] 2022-12-06 09:19
Hello everyone. We've added [python 2.7.18 for Ubuntu 22.04](https://github.com/actions/python-versions/pull/208). For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2022-12-06 09:19 UTC
Labels: bug

**Comment by AdamWill** [comment] 2022-12-06 15:56
@dmitry-shibanov 3.6 seems to be quite commonly requested as well - it's the system Python version in several long-term support Linux distros. Can that be added too?

**Comment by rouilj** [comment] 2022-12-06 17:38
@AdamWill I opened #561 for that.
