### ISSUE TITLE
On GitHub hosted runner: `Unable to locate executable file: poetry`

### ISSUE THREAD

**Issue by mbrancato** [actions/setup-python#765] opened 2023-11-12 15:47 UTC
**Description:**
Poetry appears to be required prior to running `actions/setup-python` with `cache: 'poetry'` set. This is on a GitHub hosted runner. I'm sure to fix this poetry needs to be installed before running this action. That said, I generally prefer to do that after installing Python. Also, `actions/cache` against `.venv` works fine without `poetry` being installed.

Given the "advanced usage" shows installing poetry first, maybe listing that as a dependency is the fix here, however, I don't think `poetry` is actually needed unless the virtual env is going into a different location.

https://github.com/actions/setup-python/blob/b64ffcaf5b410884ad320a9cfac8866006a109aa/docs/advanced-usage.md?plain=1#L308-L320

full error:
```
Unable to locate executable file: poetry. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

**Action version:**
v4

**Comment by dmitry-shibanov** [comment] 2023-11-13 09:54
Hello @mbrancato. It is an expected behaviour because the action uses [poetry to get configuration](https://github.com/actions/setup-python/blob/main/src/cache-distributions/poetry-cache.ts#L85). For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2023-11-13 09:54 UTC
Labels: bug, needs triage

**Comment by meteoritt** [comment] 2025-06-15 11:47
I'm have this error: https://github.com/meteoritt/topalias/actions/runs/15662824469/job/44123018652

Run actions/setup-python@v5
Installed versions
Error: Unable to locate executable file: poetry. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
