### ISSUE TITLE
Cannot parse version number from TOML 1.0.0 pyproject.toml file

### ISSUE THREAD

**Issue by Jazzinghen** [actions/setup-python#897] opened 2024-06-19 02:15 UTC
**Description:**
When providing a `pyproject.toml` that uses TOML 1.0.0 entries as `python-version-file` the action fails due to an error within the TOML parser.

**Action version:**
`v5.1.0`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

- Python 3.10 (the one installed by default)
- Python `3.12` (the target version)

**Repro steps:**  
Create a `pyproject.toml` file using a mixed list ([here](https://github.com/mtkennerly/poetry-dynamic-versioning#configuration) is the default value for Poetry Dynamic Versioning):

```toml
[tool.poetry]
name = "test_package"
description = "Test package to setup python on Github"
requires-python = ">=3.12"
license = ""
keywords = []
authors = [
    "Jazzinghen <jazzinghen@test.com>" 
]

[build-system]
requires = ["poetry-core>=1.8.0", "poetry-dynamic-versioning>=1.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = false
strict = true
style = "pep440"
pattern = "default-unprefixed"
tag-branch = "origin/main"

[tool.poetry-dynamic-versioning.substitution]
folders = [{ path = "src" }]
patterns = [
  "(^__version__\\s*(?::.*?)?=\\s*['\"])[^'\"]*(['\"])",
  "(^release\\s*(?::.*?)?=\\s*['\"])[^'\"]*(['\"])",
  { value = "(^__version_tuple__\\s*(?::.*?)?=\\s*\\()[^)]*(\\))", mode = "tuple" },
]

[tool.poetry.dependencies]
python = "^3.12"
``` 

Run the action using the file as "Python version file".

**Expected behavior:**
The action installs Python `>=3.12` in the job's container.

**Actual behavior:**
The action fails with the following error:

```
 Error: Inline lists must be a single type, not a mix of string and inline-table at row 27, col 84, pos 757:
26:    "(^release\\s*(?::.*?)?=\\s*['\"])[^'\"]*(['\"])",
27>   { value = "(^__version_tuple__\\s*(?::.*?)?=\\s*\\()[^)]*(\\))", mode = "tuple" },
                                                                                       ^
28: ]
```

**Comment by JamesParrott** [comment] 2024-06-19 19:30
The dev version of the toml library used by this tool supported Toml 1.0.0-rc1 (that allows mixed types in arrays) since 2019.  
https://github.com/iarna/iarna-toml

This tool must pull the old version from NPM that hasn't been updated in 4 years.  It must enforce Toml 0.5.0 rules, which forbid mixed types in an Array, as the error says.

https://www.npmjs.com/package/@iarna/toml

**Comment by aparnajyothi-y** [comment] 2024-06-20 11:05
Hello @Jazzinghen, Thank you for creating this issue and we will look into it :)

**Comment by Jazzinghen** [comment] 2024-06-21 05:37
@aparnajyothi-y 
Thank you for letting me know.

**Comment by priya-kinthali** [comment] 2024-07-25 05:19
Hello @Jazzinghen 👋,
We have bumped the version of the `@iarna/toml` library from 2.2.5 to 3.0.0, which now includes support for `TOML` 1.0.0. The changes have been merged into the `main` branch and will be reflected in the upcoming release. In the meantime, could you please try using `setup-python@main` and confirm if the issue is resolved? We appreciate your patience and understanding. 
Thanks @JamesParrott for the insights!

**Comment by priya-kinthali** [comment] 2024-08-06 10:44
Hello @Jazzinghen 👋,
Just a gentle reminder to see if you had a chance to test the changes with `setup-python@main`. Has the issue been fixed?Your response is greatly appreciated. Thank you in advance :)

**Comment by priya-kinthali** [comment] 2024-08-20 08:05
Hello @Jazzinghen 👋,
As previously mentioned, the updates to the `@iarna/toml` library have been merged into the `main` branch and will be included in the upcoming release of `setup-python`. Therefore, I am closing this issue. If you encounter any further problems, please feel free to reopen or create a new issue.

Thank you for your understanding and cooperation.

**Closed by priya-kinthali** 2024-08-20 08:05 UTC
Labels: bug

**Comment by Jazzinghen** [comment] 2024-08-22 01:42
@priya-kinthali sorry I haven't replied earlier. I have been swamped by work, so I couldn't check this.
I'll test it out asap and let you know if there are any issues.
