### ISSUE TITLE
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info

### ISSUE THREAD

**Issue by oegedijk** [actions/setup-python#165] opened 2020-12-07 09:12 UTC
**Describe the bug**

When I try to install the `shap` python package with actions/setup-python, I get the following error:

`ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-2o6_dq3n`

Shap installs fine on my local machine, and other packages also work fine on github actions. This behaviour started about two days ago. As a result I cannot run the test suite for my [explainerdashboard](http://github.com/oegedijk/explainerdashboard) package.

**Which version of the action are you using?**

- [ ] `v1`
- [ x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x ] Linux
- [x ] Windows
- [ x] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.6`, `3.7`, `3.8`)

**To Reproduce**
 Run the following github actions scripts:

```yaml
name: test_action

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install flake8 pytest
        pip install shap
```

Then you get the following output:

```
Run python -m pip install --upgrade pip wheel
Collecting pip
  Downloading pip-20.3.1-py2.py3-none-any.whl (1.5 MB)
Collecting wheel
  Downloading wheel-0.36.1-py2.py3-none-any.whl (34 kB)
Installing collected packages: pip, wheel
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
Successfully installed pip-20.3.1 wheel-0.36.1
Collecting flake8
  Downloading flake8-3.8.4-py2.py3-none-any.whl (72 kB)
Collecting pytest
  Downloading pytest-6.1.2-py3-none-any.whl (272 kB)
Collecting attrs>=17.4.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting importlib-metadata
  Downloading importlib_metadata-3.1.1-py3-none-any.whl (9.6 kB)
Collecting iniconfig
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting packaging
  Downloading packaging-20.7-py2.py3-none-any.whl (35 kB)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting py>=1.8.2
  Downloading py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting pycodestyle<2.7.0,>=2.6.0a1
  Downloading pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting pyflakes<2.3.0,>=2.2.0
  Downloading pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting zipp>=0.5
  Downloading zipp-3.4.0-py3-none-any.whl (5.2 kB)
Installing collected packages: zipp, pyparsing, importlib-metadata, toml, pyflakes, pycodestyle, py, pluggy, packaging, mccabe, iniconfig, attrs, pytest, flake8
Successfully installed attrs-20.3.0 flake8-3.8.4 importlib-metadata-3.1.1 iniconfig-1.1.1 mccabe-0.6.1 packaging-20.7 pluggy-0.13.1 py-1.9.0 pycodestyle-2.6.0 pyflakes-2.2.0 pyparsing-2.4.7 pytest-6.1.2 toml-0.10.2 zipp-3.4.0
Collecting shap
  Downloading shap-0.37.0.tar.gz (326 kB)
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-2o6_dq3n
Error: Process completed with exit code 1.
```
**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**Screenshots**

**Additional context**

**Comment by ddangu525** [comment] 2020-12-08 05:06
Sme problem here. The version of pip and shap is not the cause.

**Comment by ddangu525** [comment] 2020-12-08 05:15
Same problem here. The version of pip and shap is not the cause. I also tried to add `--use-deprecated=legacy-resolver` in pip install command, but it didn't work.

**Comment by ddangu525** [comment] 2020-12-14 05:04
I found the reason. Use setuptools<51

**Comment by ddangu525** [comment] 2020-12-14 05:20
I found the reason. Upgrade setuptools.

**Comment by andrewdoss** [comment] 2021-01-04 22:50
ddangu525 is right - upgrade setuptools or your Python version (3.7 worked for me). This is a general packaging issue, not a Shap issue.

**Comment by jprafael** [comment] 2021-01-08 11:45
> I found the reason. Upgrade setuptools.

Can confirm this worked for me as well.

**Comment by kjanko** [comment] 2021-02-10 08:51
Having the same issue, however upgrading setuptools (v53.0.0) does not solve it. Any idea what could be causing it?

**Comment by gregross** [comment] 2021-02-12 19:08
> Having the same issue, however upgrading setuptools (v53.0.0) does not solve it. Any idea what could be causing it?

Same here. Upgrading to setuptools v53.0.0 made no difference.  I'm on Python 3.6.7.

**Comment by oshev** [comment] 2021-04-08 16:32
Thanks, installing numpy first worked for me.

**Comment by tonysinghmss** [comment] 2021-04-21 11:50
I am facing the same issue while installing shap==0.39.0. Details are:
setuptools ==56.0.0
pip==21.0.1
python==3.7.3

**Comment by truethari** [comment] 2021-04-22 02:17
It showed me the same error when I use virtualenv.
### Solution:
Install the requirement packages before use setuptools. `pip install -r requirements.txt`  or one by one.

This works for me.

**Comment by harrylyx** [comment] 2021-07-08 08:29
Thanks, installing numpy first worked for me too.

**Comment by Hysmane** [comment] 2021-09-27 23:39
you  have to pip install numpy first and  to pip install shap....  as  they said...

**Comment by nikita-bykov** [comment] 2021-11-19 13:20
Hello @oegedijk! We apologize for such a late reply.
Is this issue still relevant to you?

**Comment by nikita-bykov** [comment] 2021-12-17 10:14
Hello @oegedijk, I tried to reproduce it and everything works for me as expected.
I'm going to close the issue, but if it is still relevant to you, feel free to contact us.

**Closed by nikita-bykov** 2021-12-17 10:14 UTC
Labels: bug

**Comment by pinnintipraneethkumar** [comment] 2022-01-17 08:39
i am facing same issue while trying to create custom env in open ai gym
![Screenshot 2022-01-17 163903](https://user-images.githubusercontent.com/76033282/149735715-997174f3-3400-4c8e-bb7d-dfd3ac31d8b3.png)

**Comment by Lenyas66** [comment] 2022-02-08 21:35
> Hello @oegedijk, I tried to reproduce it and everything works for me as expected. I'm going to close the issue, but if it is still relevant to you, feel free to contact us.

Hi Nikita,

This issue still seems to exist for me. I raised a new one as well.

https://github.com/ibmdb/python-ibmdb/issues/723

**Comment by asadikani** [comment] 2022-08-28 11:25
1-unzip downloaded file.
2-open command line as administrator.
3-change directory to unzipped folder.
4-run: python setup.py install

**Comment by nikhilrane-21** [comment] 2022-10-31 04:14
> Upgrading from Python 3.6.6 to 3.7 worked for me. 
Yes, I was also having same error, resolved by changing the python version and environment. I guess its the error due to old python's files gone missing.

**Comment by qingfusheng** [comment] 2022-11-03 14:09
I meet this problem too. I uninstall the setuptools and the error gone.

**Comment by guweixin** [comment] 2023-02-23 03:32
I meet this problem too when I install fire. 
I used python==3.10, but fire is only support python3.6-3.9 
so I use conda to build a environment with python3.9
this error gone

**Comment by caiya55** [comment] 2023-04-21 01:52
> I meet this problem too. I uninstall the setuptools and the error gone.

this works for me！

**Comment by sogngenWang** [comment] 2023-04-26 15:19
> I meet this problem too. I uninstall the setuptools and the error gone.

thanks very much , I have waste several hours for this problem

**Comment by Sarthak-Sinha-09** [comment] 2023-05-02 04:08
Hi All,
I am facing the same problem. I am using VS CODE, I have 3 packages in my requirements.txt file Numpy, Pandas, and Seaborn. When I am to do "pip install -r requirements.txt" I am getting the same error.

**Comment by drsuresh8453** [comment] 2023-06-19 07:31
@Sarthak-Sinha-09 , even am facing same error here

**Comment by dmitry-shibanov** [comment] 2023-08-14 09:08
Hello @mohanty-aditya. If it is reproducible from your side could you please provide the link to the public repository and build because we can't reproduce it from our side.

**Comment by Dzone11** [comment] 2024-01-03 13:18
### ERROR: No .egg-info directory found in C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-ih9y6a3d
I wanted to know if this is the same error. This error was raised while running req.txt. I came to understand that "-e ." was the issue. I removed "-e ." and the file ran fine. Does anyone know what the issue is here?
![Screenshot 2024-01-03 184753](https://github.com/actions/setup-python/assets/90634803/6c7d64e8-40e7-48ac-86ee-47377ab2f467)

**Comment by Atefeh197** [comment] 2024-03-13 18:50
> I meet this problem too. I uninstall the setuptools and the error gone.

works for me, thanks!

**Comment by 112292454** [comment] 2025-02-26 18:04
> 我也遇到了这个问题。我卸载了setuptools，错误就消失了。

its worked.
before.i tried to update /upgrade setuptools,but no use
