### ISSUE TITLE
Install not works on Centos 7 container

### ISSUE THREAD

**Issue by DifferentialOrange** [actions/setup-python#527] opened 2022-10-20 13:32 UTC
**Description:**
Install action returns success on `centos:7` container but the result is unusable.

**Action version:**
4

**Platform:**
- [x] Ubuntu (with `centos:7` container)
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.6 to Python 3.10

**Repro steps:**  

```yml
  issue_candidate:
    runs-on: ubuntu-20.04

    container:
      image: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - 'centos:7'
        python:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Check that Python is ok
        run: python --version
```

**Expected behavior:**
Everything is alright or I get an error like "centos is not supported".

**Actual behavior:**
Call fails for all Python versions (example for 3.6):
```
Run python --version
  python --version
  shell: sh -e {0}
  env:
    pythonLocation: /__t/Python/3.6.15/x64
    PKG_CONFIG_PATH: /__t/Python/3.6.15/x64/lib/pkgconfig
    Python_ROOT_DIR: /__t/Python/3.6.15/x64
    Python2_ROOT_DIR: /__t/Python/3.6.15/x64
    Python3_ROOT_DIR: /__t/Python/3.6.15/x64
    LD_LIBRARY_PATH: /__t/Python/3.6.15/x64/lib
python: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /__t/Python/3.6.15/x64/lib/libpython3.6m.so.1.0)
python: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /__t/Python/3.6.15/x64/lib/libpython3.6m.so.1.0)
python: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__t/Python/3.6.15/x64/lib/libpython3.6m.so.1.0)
Error: Process completed with exit code 1.
```

**Comment by marko-zivic-93** [comment] 2022-10-20 13:46
Hello @DifferentialOrange ,
Thank you for your feedback! We will investigate this issue and come back to you as soon as we get some news about the issue :)

**Comment by dmitry-shibanov** [comment] 2022-11-21 10:19
Hello @DifferentialOrange. I think it is an expected behaviour because python versions are built for special OS. Python versions were built for Ubuntu (18.04, 20.04, 22.04), that is why it has issues with Centos 7 because provided versions are not suitable for this OS.

**Comment by DifferentialOrange** [comment] 2022-11-30 12:18
> Hello @DifferentialOrange, just a gentle ping.

So which way you decided to follow? Will you add some OS check with "Only Ubuntu/Windows/MacOS is supported" message fail?

**Comment by dmitry-shibanov** [comment] 2022-11-30 17:42
I'm not sure that we need to add such check in the code because in documentation we state that the action uses python versions are built for specific versions of Ubuntu and macOS. 

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2022-11-30 17:42 UTC
Labels: bug
