### ISSUE TITLE
python 3.7 from setup/python lacking GLIBC_2.28 to run in container

### ISSUE THREAD

**Issue by oleks-popovych** [actions/setup-python#370] opened 2022-04-01 22:00 UTC
**Description:**
I’m trying to launch a workflow inside container on self-hosted runner.

Part of the workflow is python setup via action’s setup/python.

But I’m getting an error after trying to launch anything with installed python:
```
python: /lib/x86_64-linux-gnu/libm.so.6: versionGLIBC_2.29’ not found (required by /__w/_tool/Python/3.7.12/x64/lib/libpython3.7m.so.1.0)
python: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.28' not found (required by /__w/_tool/Python/3.7.12/x64/lib/libpython3.7m.so.1.0)
```
**Action version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ x] Self-hosted

**Tools version:**
python 3.7

**Repro steps:**  
```
name: Testing

on:
  workflow_dispatch:

jobs:
  tests:
    container:
      image: ubuntu:18.04
    # ubuntu 20.04
    runs-on: self-hosted 

    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dev dependencies & build package
      run: |
        wget -qO- https://bootstrap.pypa.io/get-pip.py | python
```

**Expected behavior:**
it doesn't throw the error

**Actual behavior:**
error

**Comment by dsame** [comment] 2022-04-05 07:21
@oleks-popovych why don't you use 20.04 container in order to have recent glibc version installed?
Docker hub has the 20.04 image https://hub.docker.com/_/ubuntu

Please confirm you really need to run your build within 18.04 container.

**Comment by oleks-popovych** [comment] 2022-04-05 08:31
@dsame 
I've tried to, but I have some specific constrains that tight me to ubuntu 18.04.

Also I didn't expect it to be this hard since if I'm trying to run my code on ubuntu 18.04 provided by github (runners) everything works fine.

**Comment by dhvcc** [comment] 2022-04-05 15:51
Isn't this just the container lacking this lib? May be try inspect if this lib is present (or try to install it) before running `setup-python`? At least for me it seems to be the case

**Comment by dsame** [comment] 2022-04-06 07:11
hello @oleks-popovych,
 In case you need to use python3.7 with the clean ubuntu 18.04 docker image the simplest way it instal python 3.7 from some PPA repo:
 
 ```
    - name: Set up Python 3.7
      run: |
        apt update
        apt-get install -y software-properties-common 
        add-apt-repository -y ppa:deadsnakes/ppa
        apt-get install -y python3.7
        ln -s `which python3.7` /usr/local/bin/python
        python --version
```

Also pay attention the docker image provided does not have wget as well and you need to install it either in the separate step
```
   - name: Set up wget
      run: |
        apt-get install -y wget
```
or in the same time as the python package ` apt-get install -y python3.7 wget`

Ideally, to save the time in the workflow i'd create the docker inherited from ubunut:18.04 with the python and wget pre-installed 

Please confirm the suggested solution works for you.

**Comment by dsame** [comment] 2022-04-06 07:14
hello @dhvcc, you are absolutely correct. The latest glibc supported by Ubuntu 18.04 is 2.27

**Comment by oleks-popovych** [comment] 2022-04-06 14:11
@dsame 
it seems that this is a way.

**Comment by dhvcc** [comment] 2022-04-06 15:05
> @dsame @dhvcc but still I don't understand why it's still working with python 3.7 installed via `apt-get`, but not via `setup/python`

I think it's most likely not that setup/python is failing, but rather poetry choosing the wrong bundled version. I mena if you explicitly say `poetry use 3.10` then it works, right?

**Comment by oleks-popovych** [comment] 2022-04-07 08:53
@dhvcc 
I don't even know that `setup/python` uses poetry under the hood. 
could you elaborate more on your advice, since I'm not to how to connect `setup/python` and `poetry`

**Comment by dhvcc** [comment] 2022-04-07 15:41
> @dhvcc I don't even know that `setup/python` uses poetry under the hood. could you elaborate more on your advice, since I'm not to how to connect `setup/python` and `poetry`

Oh, that's a different issue that's not poetry related, sorry haha
Basically what you need to do is to install right glibc version
 before running `setup-python`

**Comment by vsafonkin** [comment] 2022-04-11 12:35
Hi @oleks-popovych, it's difficult to say why it doesn't work properly on your self-hosted runner, I'm trying to reproduce this issue on hosted runner and it works: https://github.com/vsafonkin/test-repo/runs/5970187832?check_suite_focus=true
Could you try to execute `apt-get update` command before `setup-python` step?

**Comment by dhvcc** [comment] 2022-04-12 09:39
> @vsafonkin 
> Thank you for your reply.
> I've already used a suggestion by @dsame to install python via `apt-get` instead of using `setup/python`
> 
> Still I'm confused why underlying system matters when things are running in a container?

Not an underlying (host) system matters. It's the container itself. If libs are missing in a container (which is running Ubuntu 18), then python won't be set up properly

**Comment by vsafonkin** [comment] 2022-04-12 10:44
> Still I'm confused why underlying system matters when things are running in a container?

As I see this issue: the `setup-python` action uses python build from source code, which was built on the hosted runner and downloaded from [python-versions repository](https://github.com/actions/python-versions). As I know, Ubuntu container uses OS kernel from host OS. So using a python that has been built on a  OS kernel with certain versions of the libraries can cause problems when running on another OS kernel.

**Comment by vsafonkin** [comment] 2022-04-18 07:16
Hi @oleks-popovych, I'm going to close this issue, feel free to contact us if you have any concerns, thank you.

**Closed by vsafonkin** 2022-04-18 07:16 UTC
Labels: bug
