### ISSUE TITLE
bad setuptools installation in actions/setup-python@v5

### ISSUE THREAD

**Issue by charles-cooper** [actions/setup-python#842] opened 2024-04-07 13:29 UTC
### Description

since roughly friday (apr 5), test runs using `actions/setup-python@v5` have been erroring out, apparently randomly, with
```python
    import pkg_resources
SyntaxError: source code string cannot contain null bytes
```
here is an example of a failing run: https://github.com/vyperlang/vyper/actions/runs/8583718233/job/23523259737#step:7:85

prior to friday, with no code or workflow changes, the same CI encountered no such errors, here is an example: https://github.com/vyperlang/vyper/actions/runs/8561560272/job/23463040450.

i suspect the issue is a bad python binary or builtins image. force reinstalling setuptools appears to fix the issue, as here: https://github.com/vyperlang/vyper/actions/runs/8588960022

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/vyperlang/vyper/actions/runs/8583718233/job/23523259737#step:7:85

```
2024-04-06T20:48:27.8925830Z Current runner version: '2.315.0'
2024-04-06T20:48:27.8949086Z ##[group]Operating System
2024-04-06T20:48:27.8949821Z Ubuntu
2024-04-06T20:48:27.8950200Z 22.04.4
2024-04-06T20:48:27.8950495Z LTS
2024-04-06T20:48:27.8950894Z ##[endgroup]
2024-04-06T20:48:27.8951288Z ##[group]Runner Image
2024-04-06T20:48:27.8951682Z Image: ubuntu-22.04
2024-04-06T20:48:27.8952186Z Version: 20240403.1.0
2024-04-06T20:48:27.8953230Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240403.1/images/ubuntu/Ubuntu2204-Readme.md
2024-04-06T20:48:27.8954657Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240403.1
2024-04-06T20:48:27.8955596Z ##[endgroup]
```

### Is it regression?

yes

### Expected behavior

see description

### Actual behavior

see description

### Repro steps

the issue is flaky, and i have not been able to reliably reproduce it. please see the logs of the failing test run for example failing cases. (i am happy to provide links to more failing jobs, i have about a dozen since friday).

**Comment by mikhailkoliada** [comment] 2024-04-07 14:37
Moving tp setup-python as we do not install/manage setuptools on the images

**Comment by aparnajyothi-y** [comment] 2024-04-08 15:01
Hello @charles-cooper, Thank you for creating this issue and we will look into it :)

**Comment by charles-cooper** [comment] 2024-04-10 00:16
note as of yesterday or so i am no longer seeing the issue. i noticed a new image in the logs --
```
2024-04-09T20:26:08.1175581Z Current runner version: '2.315.0'
2024-04-09T20:26:08.1199165Z ##[group]Operating System
2024-04-09T20:26:08.1199794Z Ubuntu
2024-04-09T20:26:08.1200094Z 22.04.4
2024-04-09T20:26:08.1200541Z LTS
2024-04-09T20:26:08.1200869Z ##[endgroup]
2024-04-09T20:26:08.1201202Z ##[group]Runner Image
2024-04-09T20:26:08.1201710Z Image: ubuntu-22.04
2024-04-09T20:26:08.1202105Z Version: 20240407.1.0
2024-04-09T20:26:08.1203047Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240407.1/images/ubuntu/Ubuntu2204-Readme.md
2024-04-09T20:26:08.1204572Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240407.1
2024-04-09T20:26:08.1205449Z ##[endgroup]
2024-04-09T20:26:08.1205804Z ##[group]Runner Image Provisioner
2024-04-09T20:26:08.1206373Z 2.0.361.1
2024-04-09T20:26:08.1206708Z ##[endgroup]
```

**Comment by aparnajyothi-y** [comment] 2024-07-10 07:03
Hello @charles-cooper, Thank you again for creating the issue and confirming that the problem is no longer occurring since the runner image update. 
We will proceed to close this issue for now. Please feel free to reach out to us to reopen the issue if the problem reoccurs or if you have any further concerns.

**Closed by aparnajyothi-y** 2024-07-10 07:03 UTC
