### ISSUE TITLE
[Feature Request] Let `python-version` take a list of versions to install/set up

### ISSUE THREAD

**Issue by Cielquan** [actions/setup-python#167] opened 2020-12-11 19:46 UTC
Currently only strings with one version are allowed, which is sufficient for most cases especially when you use a matrix to test different versions of python in different jobs.

Tools like `tox` and `nox` which can create virtual environments for different python versions can be set up to run only one of those in the corresponding job, but I would like to install multiple python versions in one job and let `tox`/`nox` do their thing. Of cause I can specify the `setup-python` action multiple times to achieve that, what I currently do, but I think it would be better to just use the action once and specify a list instead.

**Comment by konradpabjan** [comment] 2020-12-17 16:23
Thank you for opening the issue, closing out as a duplicate of https://github.com/actions/setup-python/issues/98

**Closed by konradpabjan** 2020-12-17 16:23 UTC
Labels: duplicate
