### ISSUE TITLE
Use recommended release strategy

### ISSUE THREAD

**Issue by damccorm** [actions/setup-python#11] opened 2019-08-19 17:38 UTC
We should be using the release strategy specified by https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations

To get there, we need to:
1) Create a `releases/v1` branch and move the `v1` tag and future releases there
2) Warn that we will deprecate the master branch and that you should attach to `v1` instead. We will support master in a warned but deprecated state for ~1 month.
3) Switch the warning to an error on master. Remove `node_modules` from the master branch. We will stay in this state for ~1 month.
4) Remove the error on master.

During steps 2 and 3, we need to be extra careful to not check the warning/error into the releases branch.

**Comment by bryanmacfarlane** [comment] 2019-11-05 21:02
We're not doing this anymore.  We're moving toward ncc.  See javascript-action PRs from me and talk to Josh

**Comment by bryanmacfarlane** [comment] 2019-11-05 21:02
At that point it's just code and branches and the branching is up to you.

**Comment by konradpabjan** [comment] 2019-11-06 20:34
A releases branch, `release/v1` has been created to track of a stable release version. The `v1` tag has also been adjusted to now point to that branch. In the future if there are big changes then `releases/v2` etc. will be created along with new tags. The master branch will remain functional with the latest and greatest changes changes. After changes in the master branch are validated and confirmed to be working they will be ported over to the releases branch.

`Node_modules` have been removed from the master and release branch and we now rely on ncc to create a single js file for release. Since the master branch will continue to function, there is no need for deprecation warnings or error messages. We document that using a reference to the master branch could cause breaking changes in the future so no further action is needed: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsuses

**Closed by konradpabjan** 2019-11-06 20:34 UTC
