### ISSUE TITLE
Python package installed in one workflow visible in another

### ISSUE THREAD

**Issue by zuckerruebe** [actions/setup-python#488] opened 2022-08-24 08:07 UTC
**Description:**
I have two repos `A` and `B`.

`A` does

```
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
```

and then installs some packages, but not package `x`, like so:

```
      - name: Install specific dependencies
        run: pip install -r requirements.txt
```

`B` also does

```
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
```

and then proceeds to install its packages, including package `x`, in the same way as `A`.

To my suprise, in `A`, I could access a script that comes with `x` even though `x` is only installed in `B`.

All the workflows are running on the same self-hosted Ubuntu runner.

**Action version:**
2.295.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
Python 3.9 (and possibly/probably (?) others)

**Repro steps:**  
See description

**Expected behavior:**
Packages installed in one workflow should not be visible to other workflows.

**Actual behavior:**
Packages installed in one workflow are visible to other workflows.

**Comment by e-korolevskii** [comment] 2022-08-24 09:37
Hi @zuckerruebe! 
We will investigate the issue and get back to you.

**Comment by dmitry-shibanov** [comment] 2022-08-24 10:34
Hello @zuckerruebe. Could you please provide a public repository to reproduce the issue ?

**Comment by zuckerruebe** [comment] 2022-08-24 11:04
> Hello @zuckerruebe. Could you please provide a public repository to reproduce the issue ?

Hi Dmitry, I'm afraid the repos involved are private... :(

**Comment by dmitry-shibanov** [comment] 2022-08-24 11:43
I think it is an expected behaviour because you're using the self-hosted that is why it is not getting cleaned after the job is finished. In this case it can find dependencies related to repository B

**Comment by zuckerruebe** [comment] 2022-08-24 12:25
OK, thanks for the info. Would using `venv`'s then be a good way to go, would you say? I think it would be nice to mention this somewhere in the documentation as I've just assumed that I can use `setup-python` in exactly the same way within my self-hosted runner as I would with a Github-hosted one.

**Comment by panticmilos** [comment] 2022-09-29 16:39
Hi @zuckerruebe. This behavior is more related to the [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners). So we don't think it's necessary to include it specifically in the `setup-python` documentation as well.

For now, I am going to close the issue, feel free to continue the conversation here or reopen the issue.

**Closed by panticmilos** 2022-09-29 16:39 UTC
Labels: bug
