### ISSUE TITLE
Wrong Poetry config is used when project is not in repository's root

### ISSUE THREAD

**Issue by oranav** [actions/setup-python#446] opened 2022-06-27 18:21 UTC
**Description:**
When collecting Poetry projects for caching, a `**/poetry.lock` glob is used, meaning the action supports Poetry projects in subfolders.

<https://github.com/actions/setup-python/blob/ffcd00020c213885323d35524aa155f17870b8dd/src/cache-distributions/poetry-cache.ts#L11>

However, in order to process the Poetry configuration, `getPoetryConfiguration` runs the `poetry` command from the repo's root directory; this causes Poetry to return an invalid configuration when there is a Poetry project inside an inner directory.

<https://github.com/actions/setup-python/blob/ffcd00020c213885323d35524aa155f17870b8dd/src/cache-distributions/poetry-cache.ts#L45-L48>

**Action version:**
v4

**Platform:**
- [X] Ubuntu
- [X] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [X] Self-hosted

**Tools version:**

All Poetry versions

**Repro steps:**  
Create a repository with a Poetry project inside a subfolder; use the default action configuration. Matter of fact, even if a specific  `cache-dependency-path` is provided, the resulting Poetry config will still be invalid.

**Expected behavior:**
The correct pyproject.toml and poetry.toml (inside the subfolder) are used.

**Actual behavior:**
The read configuration uses pyproject.toml and poetry.toml from the repository root directory.

**Comment by IvanZosimov** [comment] 2022-06-29 07:38
Hi, @oranav 👋 ! Thank you for this issue! We will investigate it and get back to you with updates 🖨️

**Comment by oranav** [comment] 2022-06-29 07:48
@IvanZosimov I already have a draft PR here: #447, I just have to test it locally first (and maybe add a test)

**Comment by dsame** [comment] 2022-10-31 08:40
Hello @oranav 

Can you please help to reproduce the problem. 
I tried to create the workflow according to the description and it looks like everything works as expected

This [build](https://github.com/akv-demo/setup-python-test/actions/runs/3359696666/jobs/5567997165#step:9:44) creates the cache, you can see it from `Post Run actions/setup-python@v4` step.

And [next run](https://github.com/akv-demo/setup-python-test/actions/runs/3359700718/jobs/5568006451#step:5:33) of the same pipeline definitely uses the cache from the previous step because of the output of  `run` says:

```
Installing dependencies from lock file
No dependencies to install or update
```

I suspect you missed the use of [working-directory](https://github.com/akv-demo/setup-python-test/blob/poetry/.github/workflows/blank.yml#L24) option of `run` action.

I  believe the `working-directory` is the correct solution because it is possible to have few sub-projects and attempting to autodiscovery the sub-project could lead to the wrong decision. 

Do you agree the `working-directory` works for this issue?

**Comment by oranav** [comment] 2022-11-01 20:58
@dsame You're missing a `poetry.toml` file.
The whole point is that the action runs `poetry config` in the root directory, therefore it looks for `poetry.toml` there, instead of looking for it in the project directory.
Run `poetry config --local virtualenvs.in-project true` in the project directory - this will create a `poetry.toml` file. Commit it, and let the action run.
You'll see in its output `virtualenvs.in-project = null`, instead of the expected `virtualenvs.in-project = true`.

**Comment by dsame** [comment] 2023-01-04 08:14
Hello @oranav i am closing this issue because of related PR https://github.com/actions/setup-python/pull/447 has been merged, but please feel free to reopen it or create new one in case if the problem still exists.

**Closed by dsame** 2023-01-04 08:14 UTC
Labels: bug
