### ISSUE TITLE
macOS runners have different min versions for varying Python versions

### ISSUE THREAD

**Issue by pyrito** [actions/setup-python#654] opened 2023-04-19 15:07 UTC
**Description:**
It seems that the python versions in the macOS runners have different min supported versions. This is important for some workflows which rely on this information when creating wheels that should be compatible with older macOS versions.

**Action version:**
4

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
First have a CI job that allows upterm access.
```
name: build
on:
  pull_request:
    branches: [main]
jobs:
  build_wheel:
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get tags
        run: git fetch --tags origin
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
```
You can then log into CI and see then take a look at the min versions via otool:

```bash
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.8.16/x64/python | grep 'minos'
    minos 10.15
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.9.16/x64/python | grep 'LC_VERSION_MIN_MACOSX'
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.9.16/x64/python | grep 'minos'
    minos 11.7
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.10.11/x64/python | grep 'minos'
    minos 11.7
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.11.3/x64/python | grep 'minos'
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.11.3/x64/python 
      ....
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.9
      sdk 12.1
      ....
```

**Expected behavior:**
I would expect the versions of python to be compatible back to macOS 10.9 or something along those lines, but that doesn't seem to be the case. When I create a conda environment and use otool I can see that the min macOS version is indeed 10.9.  
**Actual behavior:**
Backwards compatible versions of the python interpreter are newer than expected for 3.8, 3.9, 3.10, but then older again for 3.11.

**Comment by dmitry-shibanov** [comment] 2023-04-20 07:37
Hello @pyrito. Thank you for your report. We'll take a look at this issue.

**Comment by dmitry-shibanov** [comment] 2023-04-25 23:19
Hello @pyrito. It is an expected behaviour because prior to 3.11.0-beta the python versions were built from the source code on the oldest available hosted runner. When `macos-10.15` were deactivated, new versions were built on `macos-11`. Starting with 3.11.0-beta, universal versions of Python are provided for macOS.

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2023-04-25 23:19 UTC
Labels: bug

**Comment by xmatthias** [comment] 2023-05-03 17:46
@dmitry-shibanov any chance this is related to the issue we're seeing here: 
in https://github.com/catboost/catboost/issues/2371?

i did some analysis / tests with different setups - and it seems like get_host_platform returns different outputs - resulting in different wheels (and in this case, rejected wheels and a source installation on 3.8 and 3.7 (ignore them failing, that's a different topic).

looking at the output in Verify-pip (the line `pip gethost`) - which is effectively this: `python -c 'from pip._vendor.distlib.util import get_host_platform; print(f"pip gethost: {get_host_platform()}")'`, it's quite inconsistent throughout the versions.
Wheels for that project are *-macosx_11_0_universal2.whl  - which seems to prevent installation on 3.8 with macosx-10.15 versions (installation seems works fine (from wheel) on a non-github action 3.8 macos though).

Summary of the observations in the above linked ci run:

| Python version| platform| uses Wheel | 
|--------|--------|--------|
|3.7 | macosx-10.15-x86_64 | ❌  |
| 3.8 |  macosx-10.15-x86_64 | ❌  |
| 3.9 | macosx-11.7-x86_64 |✅  |
| 3.10 | macosx-11.7-x86_64 |✅  |
| 3.11 | macosx-10.9-universal2 | ✅  |

**Comment by pyrito** [comment] 2023-05-11 15:55
@ddelange if you are trying to maintain some level of control, I would suggest using conda. That solved most of my problems.

**Comment by ddelange** [comment] 2023-05-11 16:11
thanks @pyrito for the suggestion, but I'm rather writing in the interest of the python community than for my personal projects :)

**Comment by ddelange** [comment] 2023-05-26 05:06
Hi @dmitry-shibanov 👋 

Could you by any chance trigger a re-build of 3.6, 3.7, 3.8 from a recent mac runner?

**Comment by dmitry-shibanov** [comment] 2023-06-05 12:27
Hello @ddelange. We're not planning to rebuild old python versions on a recent mac runner because they were built on older version of macOS and should be compatible with new versions. Besides, some customers still can use self-hosted runners with old macOS versions and rebuilding versions for the recent runner will break builds for them.
