### ISSUE TITLE
PyPy does not install on macOS?

### ISSUE THREAD

**Issue by krassowski** [actions/setup-python#295] opened 2021-12-11 17:05 UTC
**Description:**
PyPy does not install on macOS

**Action version:**
2

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
3.6

**Repro steps:**  
[[A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.](https://github.com/jupyter-lsp/jupyterlab-lsp/runs/4493686615?check_suite_focus=true)](https://github.com/jupyter-lsp/jupyterlab-lsp/runs/4493686615?check_suite_focus=true)

**Expected behavior:**
PyPy installs correcttly

**Actual behavior:**
`Error: PyPy 3.6 not found` is shown

One week ago (MacOS 10.15.7):
![Screenshot from 2021-12-11 16-48-00](https://user-images.githubusercontent.com/5832902/145684821-8dafdb1b-a689-4f78-8e86-882ded2bb780.png)

Today (MacOS 11.6.1):
![Screenshot from 2021-12-11 16-47-50](https://user-images.githubusercontent.com/5832902/145684822-7566bdae-7bb5-4e36-b151-3368bae6541a.png)

Is it related to a new MacOS version, https://github.com/actions/virtual-environments/issues/4060 ?

**Comment by krassowski** [comment] 2021-12-11 17:25
I guess this is mostly about updating the documentation since the Possible Impact section mentions that PyPy: `Version 3.6 was deprecated as it won't receive any updates`.

**Comment by nikita-bykov** [comment] 2021-12-13 11:55
Hello @krassowski! This seems to be a duplicate of #244 . You can find more context there. 
I'm going to close this issue, but feel free to contact us if you have any questions.

**Closed by nikita-bykov** 2021-12-13 11:55 UTC
Labels: bug, needs triage

**Comment by krassowski** [comment] 2021-12-13 12:06
Thanks. This is indeed a duplicate, but it's not clear from the README that this version is not supported. It seems that it is in `version.json` and it is used as an example. I would suggest to clarify it in the PyPy versions section.
